### ISSUE TITLE
FindTBB can't find tbb library under ubuntu 16.04.1

### ISSUE THREAD

**Issue by ingowald** [embree/embree#100]
Building devel on brand-new install of ubuntu 16.04.1 (default compiler, default everything) the FindTBB.cmake couldn't find the tbb that was installed in the system. 

In particular: tbb.h was indeed in /usr/include/, so FindTBB.cmake decided that "/usr" is also the path that libtbb.so and libtbbmalloc.so are supposed to be in, which isn't the case (it's 	/usr/libx86_64-linux-gnu/ under ubuntu). Couldn't manually set these paths, either, had to actually edit the findtbb.cmake and add these search paths to get it to compile ...

**Comment by cbenthin** [comment]
Should be fixed now.
