### ISSUE TITLE
API Description - Triangle Texture Coordinates Interpolation

### ISSUE THREAD

**Issue by SamirAroudj** [embree/embree#101]
The description regarding how to interpolate texture coordinates for triangles using the u and v coordinates of a ray hit seems to be wrong (https://embree.github.io/api.html or supplied readme.pdf).
The stated equation is:
t_uv = (1-u-v)*t0 + u*(t1-t0) + v*(t2-t0)
Shouldn't this be either:
t_uv = t0 + u*(t1-t0) + v*(t2-t0)
or
t_uv = (1-u-v)*t0 + u*t1 + v*t2
??

**Comment by cbenthin** [comment]
Thanks, good catch. Will fix it asap.

**Comment by cbenthin** [comment]
Fixed.
