### ISSUE TITLE
build embree on windows

### ISSUE THREAD

**Issue by lwkobe** [embree/embree#102]
I  have used cmake and ispc and tbb to generate a embree.sln .but when i build the ALL BUILD  i have found a error can't open “....\Debug\embree.lib” and I go to the “....\Debug\” directory. i have found "embree_sse42.lib" and "embree_avx2.lib" under the directory.It doesn't have "embree.lib".Could you give me some advice? Thank you.

**Comment by cbenthin** [comment]
Could you give us some more information on the windows, visual studio, compiler, cmake version etc. Also the complete visual studio build output would be very helpful. Thanks.

**Comment by cbenthin** [comment]
If the issue still persists please reopen the issue.
