### ISSUE TITLE
Error While Building Embree on Windows with MSYS2/MinwGW

### ISSUE THREAD

**Issue by marty1885** [embree/embree#103]
Hello, I'm trying to build Embree on Windows with MSYS2 (and without ISPC). But I failed to do so.
Due to some issue with unknown reason CMake does not find TBB installed by pacman by MSYS2, and setting EMBREE_TASKING_SYSTEM=INTERNAL does not make embree use it's internal tasking system. Therefor I commented CMakeLists.txt line 110~120 and line 125 to froce Embree to use it's internal tasking system.
And running cmake with the fllowing command.
```shell
cmake -DEMBREE_ISPC_SUPPORT=off -G "MSYS Makefiles" ../
```
then run Makefile
```shell
make -j4
```
Then the following error accues
https://gist.github.com/marty1885/f98a1be8ddb2bdc6015011855c9756dd
It seems to be an error related to header locating.

How could I fix this?

Compiler: GCC 6.1.0
CMake: 3.6.1
GNU Make: 4.2.1
OS: Windows 10 with MSYS2 (64 bit)

**Comment by johguenther** [comment]
I fear MSYS is not supported as build-platform by Embree. The problems you see are related to included MSVC compiler flags (starting with `/`), which are translated as paths by MSYS. To circumvent this wrong include and to (hopefully) get further replace
```cmake
INCLUDE (msvc)
```
with 
```CMake
INCLUDE (gcc)
```
around line 153 in the top-level `CMakeLists.txt`.

**Comment by marty1885** [comment]
Thanks johguenther, after modifing `CMakeLists.txt`, the compile starts.
However, The compile still fails with the following error message.
```
C:/msys64/home/ICAT/Documents/embree/common/sys/library.cpp: In function 'void* embree::getSymbol(embree::lib_t, const string&)':
C:/msys64/home/ICAT/Documents/embree/common/sys/library.cpp:43:26: error: invalid conversion from 'FARPROC {aka long long int (*)()}' to 'void*' [-fpermissive]
     return GetProcAddress(HMODULE(lib),sym.c_str());
            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [common/sys/CMakeFiles/sys.dir/build.make:135: common/sys/CMakeFiles/sys.dir/library.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: common/sys/CMakeFiles/sys.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

Adding `-fpermissive` to CMAKE_CXX_FLAGS makes the compile go farther. But still hits the following error.
```
C:/msys64/home/ICAT/Documents/embree/common/sys/thread.cpp: In function 'void embree::setAffinity(HANDLE, ssize_t)':
C:/msys64/home/ICAT/Documents/embree/common/sys/thread.cpp:45:66: error: 'PPROCESSOR_NUMBER' has not been declared
     typedef BOOL (WINAPI *SetThreadIdealProcessorExFunc)(HANDLE, PPROCESSOR_NUMBER, PPROCESSOR_NUMBER);
                                                                  ^~~~~~~~~~~~~~~~~
C:/msys64/home/ICAT/Documents/embree/common/sys/thread.cpp:45:85: error: 'PPROCESSOR_NUMBER' has not been declared
     typedef BOOL (WINAPI *SetThreadIdealProcessorExFunc)(HANDLE, PPROCESSOR_NUMBER, PPROCESSOR_NUMBER);
                                                                                     ^~~~~~~~~~~~~~~~~
C:/msys64/home/ICAT/Documents/embree/common/sys/thread.cpp:74:7: error: 'Pthe ROCESSOR_NUMBER' was not declared in this scope
       PROCESSOR_NUMBER processorNumber;
       ^~~~~~~~~~~~~~~~
C:/msys64/home/ICAT/Documents/embree/common/sys/thread.cpp:75:7: error: 'processorNumber' was not declared in this scope
       processorNumber.Group = group;
       ^~~~~~~~~~~~~~~
make[2]: *** [common/sys/CMakeFiles/sys.dir/build.make:159: common/sys/CMakeFiles/sys.dir/theahread.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:145: common/sys/CMakeFiles/sys.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

After fixing this by pasting the `PROCESSOR_NUMBER` struct into thread.h the compile goes farther. Than the math library goes wrong. Alot of the following types of error happens.
```
In file included from C:/msys64/home/ICAT/Documents/embree/kernels/common/default.h:32:0,
                 from C:/msys64/home/ICAT/Documents/embree/kernels/algorithms/parallel_for.h:19,
                 from C:/msys64/home/ICAT/Documents/embree/common/sys/mutex.cpp:19:
C:/msys64/home/ICAT/Documents/embree/common/math/math.h: In function 'bool embree::finite(float)':
C:/msys64/home/ICAT/Documents/embree/common/math/math.h:53:65: error: '_finite' was not declared in this scope
   __forceinline bool finite ( const float x ) { return _finite(x) != 0; }
```

Can we force Embree think that it is being build on Linux instead of Windows?

**Comment by johguenther** [comment]
You could have a look in `common/sys/platform.h` and override the detected platform (`#define __LINUX__; #undef __WIN32__`). It looks like adding support for MSYS requires significant effort. Alternatively you could also install (the community version of) Visual Studio to compile Embree on Windows.
