### ISSUE TITLE
Embree to Render a single model using multiple devices

### ISSUE THREAD

**Issue by pkudaiyar** [embree/embree#104]
Hi,

Is Embree supports rendering a single model using multiple HWs simultaneously such as multiple CPU, Xeon Phi or both?
if so, can you please refer to right resource?

Thanks,
Perumal Kuppuudaiyar
CSL, Intel Labs Europe

**Comment by cbenthin** [comment]
Embree itself can for example make use of multi-socket (Xeon) devices, but if you are looking for combining the compute resources in a cluster have a look at the OSPRAY project (http://www.ospray.org/) which builds on top of Embree.
