### ISSUE TITLE
HLBVH in embree, and Intel HD Graphics? 

### ISSUE THREAD

**Issue by acterhd** [embree/embree#107]
Hello. I'm sorry for non-standart question. Will support HLBVH in Embree? Will support of int64 sorting and Intel HD Graphics support?

**Comment by cbenthin** [comment]
Hi,

if you mean with "HLBVH" a fast BVH construction method based on Morton codes then the answer is "yes" as Embree supports such a code path for quite a while. The code path is typically executed when setting up the scene and object (e.g. a triangle/quad mesh) as "dynamic". The Morton code-based builder allows for a very high BVH rebuild performance (per frame) which is often a critical feature in an interactive/real-time context.

The internal radix-sort code (common/algorithms/parallel_sort.h) allows for very efficiently sorting 64-bit integers. 

Embree is designed for CPU-based architectures, so we don't support the integrated gfx directly. 

Hope this helps.
