### ISSUE TITLE
Is there any way to compute the smooth normal of a hair geometry?

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#108]
I'm talking about the geometry created with "rtcNewHairGeometry". For line segments, I can do something like this:
```
   const auto idx = mSegmentStart->at(ray.primiveID); 
   const float4& p0 = mPoints->at(idx+0);
   const float4& p1 = mPoints->at(idx+1);
   const float4 p = p0*(1.0f - ray.u) + p1*ray.u;
   info.Ng = info.p - mTransform * p.xyz();
   const float3 tangent = ray.Ng.xyz().normalized();
   info.Ng -= tangent * info.Ng.dot(tangent);
   info.Ng.normalize();
```
However, I can't do this for the hair, since I don't have the exact line that Embree is intersecting. I tried to evaluate the spline, but even with the highest tessellation, it doesn't work properly. Any other ideas?

A side question - why is the ray intersection epsilon so big for hair and line segments? It's 1,1*width in the examples. For hair, I can suspect that it is required because of the Bezier line approximation, but why for line segments also?

**Comment by atafra** [comment]
I'm not quite sure what do you mean by not having the exact line that Embree is intersecting. Embree provides a smooth tangent in ray.Ng for hair, which you can use to compute a smooth normal. This is also how the hair_geometry tutorial computes the normals. Have you looked into that? The code is in hair_geometry_device.cpp/ispc in the renderPixelStandard function.

We're using a big epsilon for hair to surely avoid any shadow ray self intersection artifacts but smaller values should also work well. For example, an epsilon of only 1.01 is sufficient for one scene that I've just tried but it might not be big enough for other scenes. I would suggest to experiment with the epsilon to see what number works best for your use case.

**Comment by ivalylo** [comment]
I mean the same smooth normal Embree is computing for Bezier curve geometry.  Embree is approximating the Bezier curves with lines depending on the tessellation level, right? If I have the exact line segment that was used for intersection + it's intersection t parameter + the intersection point, these can be used to compute cylindrical normal like in the example I posted for line segments. The example in the tutorial is using the view direction to construct the tangent frame, which works for typical hair shaders, but doesn't have the effect of a solid object. I think in Arnold for example, this is called Thick mode, the other one is called Ribbon mode:

https://support.solidangle.com/display/AFMUG/Hair+Rendering

**Comment by atafra** [comment]
The Embree hair geometry was designed for subpixel sized hair, so maybe that's why it doesn't look that good for your use case. Have you tried the new curve geometry (rtcNewCurveGeometry)? That should look like the thick mode in Arnold.
