### ISSUE TITLE
Can we have the distance to the curve in ray.v?

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#110]
Currently ray.v is not filled for hair. Good and cheap parameterization is to store the distance to the curve or directly the squared distance which is already calculated. This distance is important for any physically based hair shading. You can check out these papers, they use the signed distance 'h' to compute the azimuth scattering:

Light scattering from human hair fibers (Figure 9)
An Energy-Conserving Hair Reflectance Mode
A Practical and Controllable Hair and Fur Model for Production Path Tracing

**Comment by etheory** [comment]
In those papers h is not the distance to the curve, but the position across the width of the curve from -1 to 1 (in the bitangent direction). That value is then used along with the arcsin of this value to determine the angle that would have been produced if the hit was on a cylinder. This is because arcsin(h) = gamma where gamma is the angle between the bitangent direction and the hit normal in the plane of the cross-section.

See details here: http://www.graphics.stanford.edu/papers/hair/hair-sg03final.pdf

**Comment by ivalylo** [comment]
Yes, this is what I tried to say. There is a code in pbrt-v3 how to compute 'h' from the distance to the curve. At least if I understand correctly how it's done... I've implement this already and it looks as expected, although it's a complicated shader and it's hard to say if everything is 100% correct. The pbrt source code is in this file - curve.cpp, the Curve::recursiveIntersect() function. There, you can find the variable ptCurveDist which is required to compute 'v'. This 'v' is the parameter they pass to the shader. It's in [0;1], but it's then remapped to [-1;1] like in the paper. ptCurveDist2 looks to me the same thing that is computed already in Embree, and is required to compute 'v'. This is why I said, for performance reasons, it's the minimum that can be passed as 'v', and the rest can be computed in the user code if really required. The more clear way is to compute 'v' like in pbrt, but it will slow down the intersection code, since the real 'h' is a bit more involved to compute.

**Comment by ivalylo** [comment]
Actually, here is the code in question
```
        Vector3f dpcdw;
        Point3f pc = EvalBezier(cp, Clamp(w, 0, 1), &dpcdw);
        Float ptCurveDist2 = pc.x * pc.x + pc.y * pc.y;
        if (ptCurveDist2 > hitWidth * hitWidth * .25) return false;
        Float zMax = rayLength * ray.tMax;
        if (pc.z < 0 || pc.z > zMax) return false;

        // Compute $v$ coordinate of curve intersection point
        Float ptCurveDist = std::sqrt(ptCurveDist2);
        Float edgeFunc = dpcdw.x * -pc.y + pc.x * dpcdw.y;
        Float v = (edgeFunc > 0) ? 0.5f + ptCurveDist / hitWidth
                                 : 0.5f - ptCurveDist / hitWidth;
```

**Comment by ivalylo** [comment]
Externally, user code can compute hitWidth by evaluating the curve. This must be done already to compute the ray epsilon. dpcdw is computed by Embree in ray.Ng as I understand it.

**Comment by svenwoop** [comment]
Embree v2.14.0 will return the v-coordinate and use a better ribbon-intersector for hair.
