### ISSUE TITLE
Get many assertions with out memkind!

### ISSUE THREAD

**Issue by bigdudu** [embree/embree#111]
Testing environment UBUNTU 16.04
# GET MANY ASSERTIONS WITH OUT MEMKIND WHILE OPENNING BIG FILE
  * /embree/common/sys/alloc.cpp:148: void* embree::os_malloc(size_t, int): Assertion `ptr != MAP_FAILED' failed.
  * /embree/common/sys/alloc.cpp:179: size_t embree::os_shrink(void*, size_t, size_t): Assertion `bytesNew <= bytesOld' failed.
# CRASH ON rtcDeleteScene WITH MEMKIND

**Comment by cbenthin** [comment]
Hi,

could you provide some more info on this issue:

- Are you running your application on a Xeon Phi processor? if yes, how much memory has the HW setup and in what memory mode are you running the system (flat, cache mode, etc)?
- How complex is the object you are trying to create (#triangles or #quads)?
- Are you using transparent huge pages or even explicit 2M pages?
- Is there a reason you are using memkind as Embree does not depend/need memkind in any way?

Thanks,

**Comment by bigdudu** [comment]
Hi,
  * The processor is Xeon E5-2686-v4, and the HW has setup 64G memory ;
  * 80,000 times rtcNewTriangleMesh with 10,000,000 triangles;
  * using transparent huge pages;
  * As the assertions appear I tried to use memkind, and the assertions disappear with memkind, but crash on trcDeleteScene

Thanks.

**Comment by cbenthin** [comment]
Hi,

Are the 10M tris per trianglemesh or in total? Also which Embree version are you using?

Thanks.

**Comment by bigdudu** [comment]
Hi,

10M in total. I have tried 2.9, 2.12, 2.13

Thanks.

**Comment by cbenthin** [comment]
OK, I'll try to reproduce it with 2.13. In the meantime, could you try to put all triangles into one or just a few triangle objects (instead of 80k) to see whether this resolves the issue.

Thanks.

**Comment by cbenthin** [comment]
BTW: Are the objects and scene set to "static" or "dynamic"?

**Comment by bigdudu** [comment]
I'll try to put all tris into one or just a few mesh. "static" and "dynamic" all have been tested.

**Comment by cbenthin** [comment]
I've modified the "dynamic_scene" tutorial to create 100k spheres where each sphere has 168 triangles (16.8M tris total) and this works without problems with 2.13. (I've just set numSpheres to 100000 and numPhi to 7 in dynamic_scene_device.cpp).  The assertion 

/embree/common/sys/alloc.cpp:148: void* embree::os_malloc(size_t, int): Assertion `ptr != MAP_FAILED' failed.

indicates that a standard 4k page mmap fails which is very strange as it basically means that no more pages could be allocated on your system.

Could you contact us directly by sending an email to embree_support@intel.com so that we can dig deeper into this issue.

Thanks.

**Comment by cbenthin** [comment]
One more thing which just came to mind: Could you check whether the transparent huge pages mode is *not* set to "always" as otherwise AFAIK every 4K page allocation could be forced into a 2M allocation which could cause problems with 80k small objects (= small 4K page allocations).

**Comment by bigdudu** [comment]
The transparent huge pages mode is "always", I will send an email to embree_support@intel.com.

Thanks.

**Comment by cbenthin** [comment]
Thanks I'll follow up per mail.
