### ISSUE TITLE
Missing debug libs in Windows installer

### ISSUE THREAD

**Issue by Vertexwahn** [embree/embree#113]
I installed embree-2.13.0.x64 using the installer that can be found [here](https://github.com/embree/embree/releases/download/v2.13.0/embree-2.13.0.x64.exe).

When I look into the installation folder (C:\Program Files\Intel\Embree v2.13.0 x64\lib) I can see only four files:

```
embree.dll
embree.lib
tbb.dll
tbbmalloc.dll
```

Is it safe to use these libraries for Debug, Release and RelWithDebInfo builds?
Is it safe to use these files with different Visual Studio versions (Visual Studio 2015 (Update 1) compiler (x64), Visual Studio 2013 (Update 5) compiler (x64), Visual Studio 2012 (Update 4) compiler (x64), and Intel Compiler 16.0.1 (x64))?

Why do you not provide at least a Debug and Release version of these files?
Mixing debug and release code is considered as a bad practice.

My suggestion would be to structure it that way:

```
EMBREE V2.13.0 X64
│   
└───lib
    ├───vs2012
    │   ├───x64
    │   │   ├───Debug
    │   │   │       embreed.lib
    │   │   │
    │   │   ├───Release
    │   │   │       embree.lib
    │   │   │
    │   │   └───RelWithDebInfo
    │   │           embree.lib
    │   │
    │   └───x86
    │       ├───Debug
    │       │       embreed.lib
    │       │
    │       ├───Release
    │       │       embree.lib
    │       │
    │       └───RelWithDebInfo
    │               embree.lib
    │
    ├───vs2013
    │   ├───x64
    │   │   ├───Debug
    │   │   │       embreed.lib
    │   │   │
    │   │   ├───Release
    │   │   │       embree.lib
    │   │   │
    │   │   └───RelWithDebInfo
    │   │           embree.lib
    │   │
    │   └───x86
    │       ├───Debug
    │       │       embreed.lib
    │       │
    │       ├───Release
    │       │       embree.lib
    │       │
    │       └───RelWithDebInfo
    │               embree.lib
    │
    ├───vs2015
    │   ├───x64
    │   │   ├───Debug
    │   │   │       embreed.lib
    │   │   │
    │   │   ├───Release
    │   │   │       embree.lib
    │   │   │
    │   │   └───RelWithDebInfo
    │   │           embree.lib
    │   │
    │   └───x86
    │       ├───Debug
    │       │       embreed.lib
    │       │
    │       ├───Release
    │       │       embree.lib
    │       │
    │       └───RelWithDebInfo
    │               embree.lib
    │
    └───vs2017
        ├───x64
        │   ├───Debug
        │   │       embreed.lib
        │   │
        │   ├───Release
        │   │       embree.lib
        │   │
        │   └───RelWithDebInfo
        │           embree.lib
        │
        └───x86
            ├───Debug
            │       embreed.lib
            │
            ├───Release
            │       embree.lib
            │
            └───RelWithDebInfo
                    embree.lib
```

Linking against a library in Release and a .exe in Debug can cause crashes in Visual Studio. So please fix this our otherwise your installer is complete nonsense.

**Comment by cbenthin** [comment]
Hi,
the problem is that with debug information the size of the binary files will increased significantly. Adding multiple versions for all supported compiler variants under windows VS*, clang, ICC*, ... for x86/x64 will make this only worse. Because of this we only include the release version in the binaries.  If you need debug symbols, is there something preventing you from just recompiling the source in your environment?

**Comment by Vertexwahn** [comment]
Oh, I see. No there is nothing that prevents me from recompiling the source in my environment. I will go this way.

Just for the records:
embree.dll in Debug Build with VS2015 x64 is about 26 MB
