### ISSUE TITLE
Cannot set filter function for Intersect1 and Stream Mode

### ISSUE THREAD

**Issue by sphet** [embree/embree#114]
I want to use the same scene to raycast with both rtcIntersect and rtcIntersect1M. When trying to set filter functions using rtcSetIntersectionFilterFunction and rtcSetIntersectionFilterFunctionN, I get an exception in the error handler: 

"you have to use rtcSetIntersectionFilterFunctionN in stream mode"

But I need to set the callback for both ray cast modes. How can I do this?

**Comment by svenwoop** [comment]
You have to use the stream filter function in ray-stream mode. That function is also called by the rtcIntersect function, thus you can just do all the work there. Please note that for N==1 they RTCRay layout is used, while for N!=1 the RTCRayNt layout. If you use rtcIntersect the filter function will always get called with N=1.
