### ISSUE TITLE
Crash with packet mode disabled

### ISSUE THREAD

**Issue by michalproks** [embree/embree#116]
When the packet mode is disabled in compilation, embree crashes during the call to rtcDeviceNewScene in kernels/bvh/bvh8_factory.cpp on line 544 (BVH8Factory::BVH8Triangle4vIntersectors). The BVH8Triangle4vIntersector4HybridPluecker is nullptr

Happens in both 2.14 and current git version.

Compiled with MSVC 2015 Update 3, with the following CMake settings:

-DEMBREE_ISPC_SUPPORT=OFF
-DEMBREE_STATIC_LIB=ON
-DEMBREE_TUTORIALS=OFF
-DEMBREE_RAY_PACKETS=OFF
-DEMBREE_STATIC_RUNTIME=OFF
-DEMBREE_INTERSECTION_FILTER_RESTORE=ON
-DEMBREE_TASKING_SYSTEM=INTERNAL
-DEMBREE_GEOMETRY_QUADS=OFF
-DEMBREE_GEOMETRY_LINES=OFF
-DEMBREE_GEOMETRY_HAIR=OFF
-DEMBREE_GEOMETRY_SUBDIV=OFF

**Comment by svenwoop** [comment]
Just fixed this issue in the devel branch. As a workaround you can also just delete all lines where an intersector4/8/16/N is set in bvh4_factory.cpp and bvh8_factory.cpp.
