### ISSUE TITLE
Nearest Neighbors

### ISSUE THREAD

**Issue by nitro44x** [embree/embree#117]
Can embree be used for nearest neighbor searches in a point cloud?  I know that it currently cannot do this, but is this something you would consider? It looks like you have a BVH under the hood, so it doesn't seem too bad. And I suppose point geometries would need to be added as well.

Just a thought, but it could conflate the library as well.

**Comment by ingowald** [comment]
Nitro,

Embree itself doesn't do that (for exactly the conflating reason you mentioned), but it "may" be possible to add a library on top of it that does. In fact, for another customer I just added some point-to-surfest-distance library last month...

I'm currently traveling, but would love to chat. Can you send me an email?
