### ISSUE TITLE
Compilation KNL

### ISSUE THREAD

**Issue by timocafe** [embree/embree#121]
Hello,
I am trying to compile embree on my KNL node using intel compiler. On the link libembree.so

/nix/store/kr7syzksynl81klsncyalqlwnpfrjcxq-generated-env-module-icc/bin/c++  -fPIC  -Wall -fPIC -std=c++11 -fvisibility-inlines-hidden -fvisibility=hidden -no-ansi-alias -fasm-blocks -static-intel -no-intel-extensions -DNDEBUG                    -O3 -restrict -no-inline-max-total-size -inline-factor=200 -no-inline-max-per-compile -Wl,--version-script=/home/ewart/embree/kernels/export.linux.map  -Wl,--no-undefined -shared -Wl,-soname,libembree.so.2 -o ../libembree.so.2.15.0 CMakeFiles/embree.dir/common/device.cpp.o CMakeFiles/embree.dir/common/stat.cpp.o CMakeFiles/embree.dir/common/acceln.cpp.o CMakeFiles/embree.dir/common/accelset.cpp.o CMakeFiles/embree.dir/common/state.cpp.o CMakeFiles/embree.dir/common/rtcore.cpp.o CMakeFiles/embree.dir/common/rtcore_builder.cpp.o CMakeFiles/embree.dir/common/scene.cpp.o CMakeFiles/embree.dir/common/alloc.cpp.o CMakeFiles/embree.dir/common/geometry.cpp.o CMakeFiles/embree.dir/common/tasksys.cpp.o CMakeFiles/embree.dir/common/scene_user_geometry.cpp.o CMakeFiles/embree.dir/common/scene_instance.cpp.o CMakeFiles/embree.dir/common/scene_geometry_instance.cpp.o CMakeFiles/embree.dir/common/scene_triangle_mesh.cpp.o CMakeFiles/embree.dir/common/scene_quad_mesh.cpp.o CMakeFiles/embree.dir/common/scene_bezier_curves.cpp.o CMakeFiles/embree.dir/common/scene_line_segments.cpp.o CMakeFiles/embree.dir/subdiv/bezier_curve.cpp.o CMakeFiles/embree.dir/subdiv/bspline_curve.cpp.o CMakeFiles/embree.dir/geometry/primitive.cpp.o CMakeFiles/embree.dir/geometry/instance_intersector1.cpp.o CMakeFiles/embree.dir/geometry/instance_intersector.cpp.o CMakeFiles/embree.dir/builders/primrefgen.cpp.o CMakeFiles/embree.dir/bvh/bvh.cpp.o CMakeFiles/embree.dir/bvh/bvh_statistics.cpp.o CMakeFiles/embree.dir/bvh/bvh4_factory.cpp.o CMakeFiles/embree.dir/bvh/bvh8_factory.cpp.o CMakeFiles/embree.dir/bvh/bvh_rotate.cpp.o CMakeFiles/embree.dir/bvh/bvh_refit.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_hair.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_morton.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_sah.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_twolevel.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_instancing.cpp.o CMakeFiles/embree.dir/bvh/bvh_intersector1_bvh4.cpp.o CMakeFiles/embree.dir/common/scene_subdiv_mesh.cpp.o CMakeFiles/embree.dir/subdiv/tessellation_cache.cpp.o CMakeFiles/embree.dir/subdiv/subdivpatch1base.cpp.o CMakeFiles/embree.dir/subdiv/catmullclark_coefficients.cpp.o CMakeFiles/embree.dir/geometry/grid_soa.cpp.o CMakeFiles/embree.dir/subdiv/subdivpatch1base_eval.cpp.o CMakeFiles/embree.dir/bvh/bvh_builder_subdiv.cpp.o CMakeFiles/embree.dir/common/rtcore_ispc.cpp.o CMakeFiles/embree.dir/bvh/bvh_intersector_single.cpp.o CMakeFiles/embree.dir/bvh/bvh_intersector_hybrid4_bvh4.cpp.o CMakeFiles/embree.dir/bvh/bvh_intersector_stream_filters.cpp.o common/rtcore_ispc.dev.o common/rtcore_ispc.dev_sse2.o common/rtcore_ispc.dev_sse4.o common/rtcore_ispc.dev_avx.o common/rtcore_ispc.dev_avx2.o common/rtcore_ispc.dev_avx512knl.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_for.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_reduce.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_prefix_sum.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_for_for.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_for_for_prefix_sum.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_partition.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_sort.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_set.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_map.cpp.o ../common/algorithms/CMakeFiles/algorithms.dir/parallel_filter.cpp.o ../libembree_sse42.a ../libembree_avx.a ../libembree_avx2.a ../libembree_avx512knl.a ../libsys.a ../libsimd.a ../liblexers.a ../libtasking.a ../libsys.a -lpthread -ldl -ltbb -ltbbmalloc 

I get few pages of missing symbols ....

device.cpp:(.text+0x112): undefined reference to `std::string::_Rep::_S_empty_rep_storage'
device.cpp:(.text+0x34f): undefined reference to `operator delete(void*)'
device.cpp:(.text+0x3a5): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)'
device.cpp:(.text+0x3b0): undefined reference to `std::_Rb_tree_increment(std::_Rb_tree_node_base const*)'
device.cpp:(.text+0x3bb): undefined reference to `std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&)'
device.cpp:(.text+0x3c3): undefined reference to `operator delete(void*)'
device.cpp:(.text+0x4d7): undefined reference to `operator new(unsigned long)'

For my compiler

[ewart@tds002 b]$ icc --version
icc (ICC) 17.0.0 20160721
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

any suggestion ?

best

**Comment by svenwoop** [comment]
You have to set CMAKE_CXX_COMPILER to icpc (C++ compiler) and not to icc (C compiler). Likely your /nix/store/kr7syzksynl81klsncyalqlwnpfrjcxq-generated-env-module-icc/bin/c++  refers to icc.

**Comment by timocafe** [comment]
sure it is done this is nix package from the nix store

**Comment by svenwoop** [comment]
could you try 

/nix/store/kr7syzksynl81klsncyalqlwnpfrjcxq-generated-env-module-icc/bin/c++ --version

This should print icpc (ICC) ...

**Comment by timocafe** [comment]
/nix/store/kr7syzksynl81klsncyalqlwnpfrjcxq-generated-env-module-icc/bin/c++  --version
icc (ICC) 17.0.0 20160721
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

**Comment by svenwoop** [comment]
That is the problem, your c++ refers to the C version of ICC.

**Comment by timocafe** [comment]
nix a just a way to package bin, lib, etc .... However my intel compiler used the header from gcc 4.9.3

**Comment by timocafe** [comment]
I am going to see with the our admin, come back to you soon

**Comment by timocafe** [comment]
Right we find a typo in one of our wrapper icc != icpc, thank you for the support, you can close it, best, ++t
