### ISSUE TITLE
performance issue on scene instance

### ISSUE THREAD

**Issue by rt258** [embree/embree#123]
I have a problem when using the feature of scene instance. (in ISPC mode)
For example if I create a scene without using this feature, the rendering time is about 6000ms.
However, by using the feature of scene instance, I got lower memory cost, while the  rendering time increased to 9000ms for the same scene.
I am wondering is this a common problem ,or did I miss something which could accelerate the rendering or ray intersection?

part of my code which create two-level scene:

 uniform uint instance_id = rtcNewInstance(scene->handle, scene_instance->handle);
    scene->handle2id[instance_id] = id;
    scene->id2handle[id] = instance_id;
    rtcSetTransform(scene->handle, instance_id, RTC_MATRIX_COLUMN_MAJOR,
      (uniform float* uniform)&scene_instance->xfm);
    rtcUpdate(scene->handle, instance_id);

output log in verbose mode:

**log with the feature:**
[INFO] mesh load success, internal: 40, external: 56
[INFO] material load success
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  8.41611ms, 10.2475 Mprim/s, 0.774883 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.51131ms, 7.14613 Mprim/s, 0.535377 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.221807ms, 6.92495 Mprim/s, 0.484458 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.515173ms, 9.44925 Mprim/s, 0.67811 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  7.1996ms, 10.7496 Mprim/s, 0.848812 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  16.5611ms, 10.5829 Mprim/s, 0.754646 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.87395ms, 11.2671 Mprim/s, 0.870835 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  17.2716ms, 8.96323 Mprim/s, 0.701265 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  5.47389ms, 10.8537 Mprim/s, 0.839318 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  5.55458ms, 10.696 Mprim/s, 0.827126 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.588ms, 10.8004 Mprim/s, 0.847617 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.77845ms, 9.64382 Mprim/s, 0.75685 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.58087ms, 10.8491 Mprim/s, 0.851439 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.51245ms, 11.3399 Mprim/s, 0.889958 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  80.0888ms, 10.6878 Mprim/s, 0.79041 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  17.6123ms, 10.7852 Mprim/s, 0.763974 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  6.49512ms, 9.0779 Mprim/s, 0.706288 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0875253ms, 2.69636 Mprim/s, 0.219 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  15.7694ms, 6.25922 Mprim/s, 0.477369 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.546819ms, 10.1021 Mprim/s, 0.7095 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.14467ms, 12.7268 Mprim/s, 0.968691 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  1.76989ms, 8.23101 Mprim/s, 0.626497 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  17.2143ms, 12.5928 Mprim/s, 0.884763 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  17.9515ms, 12.0756 Mprim/s, 0.848426 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.415674ms, 9.11291 Mprim/s, 0.640964 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.565921ms, 10.6411 Mprim/s, 0.774554 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  6.76083ms, 12.8141 Mprim/s, 0.970603 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.210973ms, 3.35588 Mprim/s, 0.267409 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  10.5076ms, 13.3739 Mprim/s, 0.999009 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.100925ms, 3.05177 Mprim/s, 0.22924 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.217815ms, 5.65617 Mprim/s, 0.45837 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  4.03186ms, 12.1656 Mprim/s, 0.923198 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  29.8595ms, 10.8622 Mprim/s, 0.830091 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.277116ms, 4.951 Mprim/s, 0.383262 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.178187ms, 3.12032 Mprim/s, 0.251422 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0681386ms, 3.17001 Mprim/s, 0.224484 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.069279ms, 3.11783 Mprim/s, 0.220788 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0681386ms, 3.17001 Mprim/s, 0.224484 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0681386ms, 3.17001 Mprim/s, 0.224484 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0604409ms, 2.58103 Mprim/s, 0.186893 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  12.2484ms, 12.5437 Mprim/s, 0.88128 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  11.7287ms, 13.0995 Mprim/s, 0.920332 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  12.1692ms, 12.6254 Mprim/s, 0.887019 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  5.0528ms, 11.8065 Mprim/s, 0.907637 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.866415ms, 9.52892 Mprim/s, 0.716627 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.891503ms, 9.26076 Mprim/s, 0.696459 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.011404ms, 1.05226 Mprim/s, 0.0589268 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  32.4112ms, 9.69771 Mprim/s, 0.748744 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  32.1323ms, 10.821 Mprim/s, 0.825036 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.407691ms, 9.03626 Mprim/s, 0.635226 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.098074ms, 2.97734 Mprim/s, 0.241777 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.098359ms, 2.96872 Mprim/s, 0.241076 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  31.8219ms, 11.255 Mprim/s, 0.850479 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  4.86635ms, 12.7044 Mprim/s, 0.966251 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  4.48318ms, 12.509 Mprim/s, 0.972546 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  92.2149ms, 10.6865 Mprim/s, 0.783689 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  15.8729ms, 11.5856 Mprim/s, 0.903912 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  3.00608ms, 12.178 Mprim/s, 0.861454 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  23.3119ms, 9.73278 Mprim/s, 0.744419 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  19.8429ms, 11.4343 Mprim/s, 0.874564 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  8.29323ms, 11.4628 Mprim/s, 0.885591 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  18.7179ms, 11.3542 Mprim/s, 0.874318 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  20.9049ms, 12.1979 Mprim/s, 0.892541 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  20.0886ms, 12.413 Mprim/s, 0.902792 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  21.4782ms, 11.8161 Mprim/s, 0.863459 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.138558ms, 3.24774 Mprim/s, 0.259126 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.267993ms, 5.39567 Mprim/s, 0.410041 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  6.56354ms, 11.6949 Mprim/s, 0.895546 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  39.9298ms, 10.6376 Mprim/s, 0.816804 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.263431ms, 3.64422 Mprim/s, 0.289594 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.00912318ms, 0.219222 Mprim/s, 0.0245528 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0108338ms, 0.553823 Mprim/s, 0.0649819 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.00883808ms, 0.226294 Mprim/s, 0.0253449 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0125444ms, 0.797169 Mprim/s, 0.0918339 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.125158ms, 2.78847 Mprim/s, 0.239824 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0940825ms, 2.80605 Mprim/s, 0.23979 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.05759ms, 2.29207 Mprim/s, 0.192811 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0547389ms, 2.41145 Mprim/s, 0.198762 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.095508ms, 2.76417 Mprim/s, 0.243917 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0564495ms, 2.33837 Mprim/s, 0.200675 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0909464ms, 2.90281 Mprim/s, 0.240669 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.101495ms, 1.30056 Mprim/s, 0.109404 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0935124ms, 2.82316 Mprim/s, 0.234065 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0937975ms, 2.81458 Mprim/s, 0.235742 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0573049ms, 2.30347 Mprim/s, 0.193771 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0957932ms, 2.75594 Mprim/s, 0.222813 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0940825ms, 2.80605 Mprim/s, 0.226865 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0595856ms, 2.2153 Mprim/s, 0.190113 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0946527ms, 2.78914 Mprim/s, 0.238007 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0575899ms, 2.29207 Mprim/s, 0.192812 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0949379ms, 2.78077 Mprim/s, 0.237292 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0567347ms, 2.32662 Mprim/s, 0.195718 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0949379ms, 2.78077 Mprim/s, 0.237292 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0573049ms, 2.30347 Mprim/s, 0.193771 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0567346ms, 2.32662 Mprim/s, 0.195718 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0564495ms, 2.33837 Mprim/s, 0.196707 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0581601ms, 2.2696 Mprim/s, 0.190921 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0937975ms, 2.81458 Mprim/s, 0.233013 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0940826ms, 2.80605 Mprim/s, 0.247612 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0570197ms, 2.31499 Mprim/s, 0.198668 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0575899ms, 2.29207 Mprim/s, 0.196701 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0601558ms, 2.1943 Mprim/s, 0.184587 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0570197ms, 2.31499 Mprim/s, 0.19474 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0573048ms, 2.30347 Mprim/s, 0.193771 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0926571ms, 2.84922 Mprim/s, 0.230355 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0570197ms, 2.31499 Mprim/s, 0.198668 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0105486ms, 1.89598 Mprim/s, 0.106175 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0615813ms, 2.50076 Mprim/s, 0.20058 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.017391ms, 1.38002 Mprim/s, 0.0920016 GB/s
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  0.0185315ms, 1.94264 Mprim/s, 0.122602 GB/s
[INFO] mesh create success
[INFO] exa xml file load success
building BVH4<object> using avx::BVH4BuilderSAH ... [DONE]  0.11461ms, 0.959779 Mprim/s, 0.06352 GB/s
[INFO] scene modeling success
Generating 54 MB of precalculated samples  ................................................................ [DONE]
[INFO] render 0.10 fps, 9886.65 ms, 13.489 mrps
[INFO] render frame process finish: 1, total: 16
[INFO] render 0.10 fps, 9981.09 ms, 13.377 mrps
[INFO] render frame process finish: 2, total: 16
[INFO] render 0.10 fps, 9849.25 ms, 13.567 mrps
[INFO] render frame process finish: 3, total: 16
[INFO] render 0.10 fps, 9917.30 ms, 13.499 mrps
[INFO] render frame process finish: 4, total: 16
[INFO] render 0.10 fps, 9898.81 ms, 13.544 mrps
[INFO] render frame process finish: 5, total: 16
[INFO] render 0.10 fps, 9948.45 ms, 13.538 mrps
[INFO] render frame process finish: 6, total: 16
[INFO] render 0.10 fps, 9951.07 ms, 13.503 mrps
[INFO] render frame process finish: 7, total: 16
[INFO] render 0.10 fps, 10099.44 ms, 13.210 mrps
[INFO] render frame process finish: 8, total: 16
[INFO] render 0.10 fps, 9764.69 ms, 13.591 mrps
[INFO] render frame process finish: 9, total: 16
[INFO] render 0.10 fps, 9782.31 ms, 13.560 mrps
[INFO] render frame process finish: 10, total: 16
[INFO] render 0.10 fps, 9922.40 ms, 13.351 mrps
[INFO] render frame process finish: 11, total: 16
[INFO] render 0.11 fps, 9495.43 ms, 13.892 mrps
[INFO] render frame process finish: 12, total: 16
[INFO] render 0.10 fps, 9598.26 ms, 13.677 mrps
[INFO] render frame process finish: 13, total: 16
[INFO] render 0.10 fps, 9581.43 ms, 13.626 mrps
[INFO] render frame process finish: 14, total: 16
[INFO] render 0.10 fps, 9576.51 ms, 13.622 mrps
[INFO] render frame process finish: 15, total: 16
[INFO] render 0.10 fps, 9553.29 ms, 13.564 mrps
[INFO] render frame process finish: 16, total: 16
[INFO] renderer success

[INFO] scene modeling time : 0.27 ms.
[INFO] render frame time : 156949.25 ms.

**log without the feature**
[INFO] mesh load success, internal: 40, external: 56
[INFO] material load success
[INFO] mesh create success
building BVH8<triangle4> using avx::BVH8BuilderSAH ... [DONE]  893.4ms, 8.86809 Mprim/s, 0.661043 GB/s
[INFO] scene modeling success
Generating 54 MB of precalculated samples  ................................................................ [DONE]
[INFO] render 0.15 fps, 6894.54 ms, 19.636 mrps
[INFO] render frame process finish: 1, total: 16
[INFO] render 0.14 fps, 6999.96 ms, 19.362 mrps
[INFO] render frame process finish: 2, total: 16
[INFO] render 0.14 fps, 7073.44 ms, 19.177 mrps
[INFO] render frame process finish: 3, total: 16
[INFO] render 0.14 fps, 6968.00 ms, 19.507 mrps
[INFO] render frame process finish: 4, total: 16
[INFO] render 0.14 fps, 6929.66 ms, 19.647 mrps
[INFO] render frame process finish: 5, total: 16
[INFO] render 0.14 fps, 6908.93 ms, 19.796 mrps
[INFO] render frame process finish: 6, total: 16
[INFO] render 0.14 fps, 6930.14 ms, 19.686 mrps
[INFO] render frame process finish: 7, total: 16
[INFO] render 0.15 fps, 6842.07 ms, 19.803 mrps
[INFO] render frame process finish: 8, total: 16
[INFO] render 0.15 fps, 6857.00 ms, 19.656 mrps
[INFO] render frame process finish: 9, total: 16
[INFO] render 0.14 fps, 6932.83 ms, 19.427 mrps
[INFO] render frame process finish: 10, total: 16
[INFO] render 0.14 fps, 6907.55 ms, 19.474 mrps
[INFO] render frame process finish: 11, total: 16
[INFO] render 0.14 fps, 6923.48 ms, 19.345 mrps
[INFO] render frame process finish: 12, total: 16
[INFO] render 0.15 fps, 6752.85 ms, 19.735 mrps
[INFO] render frame process finish: 13, total: 16
[INFO] render 0.15 fps, 6717.04 ms, 19.730 mrps
[INFO] render frame process finish: 14, total: 16
[INFO] render 0.15 fps, 6710.42 ms, 19.732 mrps
[INFO] render frame process finish: 15, total: 16
[INFO] render 0.15 fps, 6602.51 ms, 19.920 mrps
[INFO] render frame process finish: 16, total: 16
[INFO] renderer success

[INFO] scene modeling time : 986.75 ms.
[INFO] render frame time : 110088.92 ms.

**Comment by svenwoop** [comment]
This slowdown is to be expected. The slowdown comes from two sources: 1) when using instances the ray need to get transformed when entering an object 2) we use a two level scene hierarchy which always has lower quality then using a single hierarchy over all primitives.

Slowdown mostly comes from 2). You can improve performance by packing as many geometries that are transformed the same way into one scene. E.g. if you have a car consisting of multiple meshes, for best performance you should pack the entire car into one scene, and then instantiate that scene.

**Comment by rt258** [comment]
Dear Sven, thanks for your answer.
I have noticed that when building the top level scene, a BVH4 builder is applied by default. Is it possible for us to use a BVH8 builder instead which I think might improve the performance.

Best,
Rui

**Comment by svenwoop** [comment]
We currently only support BVH4 for instances. Will work on BVH8 support for the next release.
