### ISSUE TITLE
rtcSetBuffer2 tries to read out of bound on Mac

### ISSUE THREAD

**Issue by qnzhou** [embree/embree#124]
I have noticed that the `rtcSetBuffer2` methods tries to read out of bound.  Specifically, this happens when the float buffer fits exactly into memory chunks of multiple of 16 bytes, thus no padding should be necessary.

I have constructed a [minimal example](https://gist.github.com/qnzhou/2edd43d19da27e7c7fea6732b769dbb4) causing the crash.

System settings:

```
      System Version: macOS 10.12.4 (16E195)
      Kernel Version: Darwin 16.5.0
```
and
```
      System Version: OS X 10.11.6 (15G1421)
      Kernel Version: Darwin 15.6.0
```

Compiler tested:
Apple LLVM version 7.0.2
Apple LLVM version 8.1.0 (clang-802.0.42)

The example seems to work fine on Linux.  Windows is not tested.

**Comment by svenwoop** [comment]
This is on purpose. The API documents that the vertices of the vertex buffers have to be padded to 16 bytes, as we access the vertices using SSE instructions. This rtcSetBuffer API calls "check" this by already emulating that read, to let the error occur as soon as possible.

Thus if you have an std::vector just do an vector.reserve(vector.size()+1) to increase the memory storage by one element.

**Comment by qnzhou** [comment]
I don't see why padding is necessary in my example.  The memory footprint of the float array is (25600 * 3 * 4) bytes which is a multiple of 16 bytes.  This last element can be read with SSE instructions.

**Comment by svenwoop** [comment]
If one accesses the base address of the last element 25599 using SSE one reads one float behind the array. This is as the last element is 12 bytes large, but the read is 16 bytes large. The total array size being a multiple of 16 does not help here.

**Comment by qnzhou** [comment]
@svenwoop Thanks for the explanation.

However, if it is the case, won't the code always fail for arrays with size equals to a multiple of 12*16 bytes (i.e. accessing the last vertex will always read 4 extra bytes over the array boundary)?  The interesting thing is that the code consistently seg faults only if the array size is a multiple of 25600 * 3 * 4 bytes.  When the array size is anything else, it never fails.

**Comment by svenwoop** [comment]
No it will not. The reason is that mostly the memory behind the array is still readable. However, if you do large allocations it is likely that malloc puts the allocation to the end of the virtual address space which increases the likelyhood that the out of bound read accesses a non readable page.
