### ISSUE TITLE
Unnecessary rebuilds using cmake

### ISSUE THREAD

**Issue by michalproks** [embree/embree#125]
We're using the attached Windows .bat script (renamed to .txt since github doesn't allow to upload .bat files) to build the embree binaries. When the script is run the second time without making any changes to the embree sources, everything is rebuilt. Third and any subsequent runs of the script then correctly recognize that there is nothing to be rebuilt.

[build-all-2015.txt](https://github.com/embree/embree/files/979051/build-all-2015.txt)

This happens both in 2.15 and 2.15.1 while the same script does not unnecessarily rebuild anything when used with 2.12. We skipped versions 2.13 and 2.14 so I don't know how it behaves with them.

The cmake version we're using is the official Windows 3.8.0 build.

This is obviously only a minor nuisance with low priority.

**Comment by svenwoop** [comment]
This issue seems to be related to a compiler bug workaround. We automatically generate xxx.avx/avx2.cpp files and it appears that these get for some reason regenerated when the second project is build. No idea why this does not happen when everything get build twice.

Could you please try if deleting the 5 CreateISADummyFiles lines in kernels/common/CMakeLists.txt fixes the issue for you.

**Comment by michalproks** [comment]
Yes, deleting those lines fixes the issue. Is it safe to keep these lines removed or will it result in embree lacking the AVX/whatever optimized codepaths this way?

**Comment by svenwoop** [comment]
I just verified this by running the entire script. When disabling these lines the second run of the script does not cause rebuilding, when enabling these lines some part of the code gets rebuild.

We unfortunately still need this workaround, but if you do not compile using ICC you can safely disable the described lines.

**Comment by svenwoop** [comment]
Looks like our comments crossed. As long as you do not use ICC you can remove these lines.

**Comment by michalproks** [comment]
OK, thanks for solving this so quickly.
