### ISSUE TITLE
Build error - ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by ianli-sc** [embree/embree#127]
Hi all, 

As a beginner for ray tracer & cpp. I just installed Embree 2.15.0 from embree-2.15.0.x86_64.dmg to my mac and installed tbb form port. [Demo works well](http://img3.tbcdn.cn/5476e8b07b923/TB149J9RXXXXXaNXFXXXXXXXXXX), so try to create a simple C++ project:
```
#include <iostream>
#include <xmmintrin.h>
#include <pmmintrin.h>
#include <embree2/rtcore.h>
#include <embree2/rtcore_ray.h>

int main(int argc, char* argv[]) {
  std::cout << "start..." << std::flush;
  _MM_SET_FLUSH_ZERO_MODE(_MM_FLUSH_ZERO_ON);
  _MM_SET_DENORMALS_ZERO_MODE(_MM_DENORMALS_ZERO_ON);

  RTCDevice device = rtcNewDevice(NULL);
  RTCScene scene = rtcDeviceNewScene(device, RTC_SCENE_DYNAMIC, RTC_INTERSECT1);
  rtcDeleteScene(scene);
  rtcDeleteDevice(device);
  return 0;
}

```

But get building errors:

```
22:11:47 **** Incremental Build of configuration Debug for project EmbreeIP ****
make all 
Building file: ../src/EmbreeIP.cpp
Invoking: Cross G++ Compiler
g++ -I/opt/local/include -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"src/EmbreeIP.d" -MT"src/EmbreeIP.o" -o "src/EmbreeIP.o" "../src/EmbreeIP.cpp"
Finished building: ../src/EmbreeIP.cpp
 
Building target: EmbreeIP
Invoking: Cross G++ Linker
g++  -o "EmbreeIP"  ./src/EmbreeIP.o   
Undefined symbols for architecture x86_64:
  "_rtcDeleteDevice", referenced from:
      _main in EmbreeIP.o
  "_rtcDeleteScene", referenced from:
      _main in EmbreeIP.o
  "_rtcDeviceNewScene", referenced from:
      _main in EmbreeIP.o
  "_rtcNewDevice", referenced from:
      _main in EmbreeIP.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [EmbreeIP] Error 1

22:11:48 Build Finished (took 598ms)
```
[also the project show in this pic](http://img3.tbcdn.cn/5476e8b07b923/TB135NRRXXXXXbPXVXXXXXXXXXX)

How can I fix this error?

**Comment by svenwoop** [comment]
You have to link against Embree, add -lembree2 to the command line of the linker.

**Comment by ianli-sc** [comment]
It's so difficult to include lib path to `/opt/local/lib` and enable `embree2` lib on Eclipse...I just copy all .dylib files of embree2 to path `/usr/local/lib` to make it work.

so install .dylib files to `/usr/local/lib` and .h files to `/usr/local/include` in the future? And I think the uninstall.command is not safe enough `pkgutil --only-dirs --files com.intel.embree-2.15.0 | grep -e 'opt/local/include/\|opt/local/lib/\|Applications/' | tail -r | tr '\n' '\0' | xargs -n 1 -0 sudo rm -vd`

**Comment by svenwoop** [comment]
Setting CPATH to /opt/local/include and LIBRARY_PATH to /opt/local/lib in your .bash_profile should make Eclipse find Embree in the default install location.

We will improve the uninstall script.
