### ISSUE TITLE
Ng is incorrect when Instancing user geometry.

### ISSUE THREAD

**Issue by qatnonoil** [embree/embree#128]
When I performed isect () on the scene instancing  the User geometry, "tfar" is correct, but it seemed that "Ng" ignored the rotation component added by setTransform.
The API call I made is as follows.

// Create a root scene
rtcDeviceNewScene ()

// Create user geometry scene
rtcDeviceNewScene ()
rtcNewUserGeometry ()
rtcSetUserData ()
rtcSetBoundsFunction ()
rtcSetIntersectFunction ()
rtcSetOccludedFunction ()
rtcCommit ()

// instancing the scene of user gemetory
rtcNewInstance ()
rtcSetTransform ()
rtcUpdate ()
rtcCommit ()

// ray.Ng does not seem to reflect rtcSetTransform ()
RTCRay ray;
rtcIntersect (ray)

thanks.

**Comment by svenwoop** [comment]
We know about this problem. Ng is in object space, thus you have to transform it yourself into world space. We might fix this issue in a later version of the API.

**Comment by qatnonoil** [comment]
I got it. Thanks.
