### ISSUE TITLE
rtcUpdateBuffer(, RTC_VERTEX_BUFFER) broken for subdivision surface meshes.

### ISSUE THREAD

**Issue by tcauchois** [embree/embree#134]
(Tested as recently as 2.16.1).

To reproduce:
- Create a subdivision mesh with rtcNewSubdivisionMesh.  Populate index/crease/hole/vertex buffers and call rtcUpdate(), rtcCommit(), render scene as normal.
- Update only the vertex data (for example, if you're animating a subdivision mesh), using rtcSetBuffer or rtcMapBuffer with RTC_VERTEX_BUFFER.
- Invalidate only the vertex data with rtcUpdateBuffer(RTC_VERTEX_BUFFER).
- rtcCommit(), render the scene: the subdivision mesh doesn't move as new vertex positions are provided.

Calling rtcUpdate() instead of rtcUpdateBuffer(RTC_VERTEX_BUFFER) produces the correct drawing, and that's my current workaround, but that's potentially duplicating any processing embree does on the index buffer, which might have a big impact on frame time if the vertices change much more often than indices.

**Comment by svenwoop** [comment]
I cannot reproduce this. I modified the subdivision_geometry tutorial of Embree the following, but the cube properly moves upwards. Could you please check what you did differently?

diff --git a/tutorials/subdivision_geometry/subdivision_geometry_device.cpp b/tutorials/subdivision_geometry/subdivision_geometry_device.cpp
index acc4be0..430f5d4 100644
--- a/tutorials/subdivision_geometry/subdivision_geometry_device.cpp
+++ b/tutorials/subdivision_geometry/subdivision_geometry_device.cpp
@@ -142,6 +142,13 @@ unsigned int addCube (RTCScene scene_i)
   return geomID;
 }
 
+void updateCube (RTCScene scene_i, int geomID)
+{
+  for (size_t i=0; i<8; i++)
+    cube_vertices[i][1]+=0.1f;
+  rtcUpdateBuffer(scene_i,geomID,RTC_VERTEX_BUFFER);
+}
+  
 /*! updates the tessellation level for each edge */
 void updateEdgeLevelBuffer( RTCScene scene_i, unsigned geomID, const Vec3fa& cam_pos )
 {
@@ -330,6 +337,7 @@ extern "C" void device_render (int* pixels,
   //updateEdgeLevelBuffer(g_scene,1,p);
 
   /* rebuild scene */
+  updateCube(g_scene,1);
   rtcCommit (g_scene);
 
   /* render image */

**Comment by tcauchois** [comment]
I've created the following repro case.  My original problem statement might be wrong?  This renders incorrectly, but if I comment out the rtcSetTessellationRate in updateCube, everything works.

```
+++ b/tutorials/subdivision_geometry/subdivision_geometry_device.cpp
@@ -119,7 +119,7 @@ unsigned int addCube (RTCScene scene_i)
 {
   /* create a triangulated cube with 6 quads and 8 vertices */
   //unsigned int geomID = rtcNewTriangleMesh(scene_i, RTC_GEOMETRY_STATIC, NUM_FACES, NUM_INDICES/3);
-  unsigned int geomID = rtcNewSubdivisionMesh(scene_i, RTC_GEOMETRY_STATIC, NUM_FACES, NUM_INDICES, 8, 0, 0, 0);
+  unsigned int geomID = rtcNewSubdivisionMesh(scene_i, RTC_GEOMETRY_DEFORMABLE, NUM_FACES, NUM_INDICES, 8, 0, 0, 0);
   //unsigned int geomID = rtcNewSubdivisionMesh(scene_i, RTC_GEOMETRY_STATIC, NUM_FACES, NUM_INDICES, 8, 12, 8, 0);
 
   rtcSetBuffer(scene_i, geomID, RTC_VERTEX_BUFFER, cube_vertices, 0, sizeof(Vec3fa  ));
@@ -135,13 +135,32 @@ unsigned int addCube (RTCScene scene_i)
 
   rtcSetBuffer(scene_i, geomID, RTC_USER_VERTEX_BUFFER0, cube_colors, 0, sizeof(Vec3fa));
 
+#if 0
   float* level = (float*) rtcMapBuffer(scene_i, geomID, RTC_LEVEL_BUFFER);
   for (size_t i=0; i<NUM_INDICES; i++) level[i] = EDGE_LEVEL;
   rtcUnmapBuffer(scene_i, geomID, RTC_LEVEL_BUFFER);
+#endif
+  rtcSetTessellationRate(scene_i, geomID, EDGE_LEVEL);
 
   return geomID;
 }
 
+void updateCube(RTCScene scene_i, int geomID)
+{
+  static __aligned(16) float cube_vertices_anim[8][4];
+  static float t = 0.0f;
+  t += 0.01f;
+
+  for (size_t i = 0; i < 8; i++) {
+    cube_vertices_anim[i][0] = cube_vertices[i][0] + cosf(t);
+    cube_vertices_anim[i][1] = cube_vertices[i][1];
+    cube_vertices_anim[i][2] = cube_vertices[i][2] + sinf(t);
+  }
+  rtcSetBuffer(scene_i, geomID, RTC_VERTEX_BUFFER, cube_vertices_anim, 0, sizeof(Vec3fa));
+  rtcUpdateBuffer(scene_i, geomID, RTC_VERTEX_BUFFER);
+  rtcSetTessellationRate(scene_i, geomID, EDGE_LEVEL);
+}
+
 /*! updates the tessellation level for each edge */
 void updateEdgeLevelBuffer( RTCScene scene_i, unsigned geomID, const Vec3fa& cam_pos )
 {
@@ -330,6 +349,7 @@ extern "C" void device_render (int* pixels,
   //updateEdgeLevelBuffer(g_scene,1,p);
 
   /* rebuild scene */
+  updateCube(g_scene,1);
   rtcCommit (g_scene);
 
   /* render image */

```

**Comment by svenwoop** [comment]
v2.16.3-alpha.0 fixes this issue

**Comment by tcauchois** [comment]
Thanks for the speedy response!
