### ISSUE TITLE
SIMD patterning? 

### ISSUE THREAD

**Issue by capitalknew** [embree/embree#135]
Hello. Will embree support of enhanced SIMD streaming patters? For example, 4 for vector ops, and 1-4 (div by 4) for rays?

**Comment by cbenthin** [comment]
You mean whether we use SIMD instructions? If that's the case, the answer is "yes", we use SIMD instructions for the different ISAs (SSE, AVX, AVX2, AVX512,...) quite intensively but we put C++ wrappers around them for more convenience.

**Comment by capitalknew** [comment]
I that AVX2 lanes divides for two rays (four lanes to one ray processing, for example, vector math).

**Comment by cbenthin** [comment]
You mean storing the data for two rays in AOS format in registers? That's possible but IMHO it won't give you anything as the control flow and stack handling gets more complicated that way. We prefer to trace a single ray though a 8-wide BVH on platforms supporting 8-wide SIMD. That keeps the control flow simply and gets good SIMD utilization.

**Comment by capitalknew** [comment]
i.e. you using pure SoA?

**Comment by cbenthin** [comment]
No, single rays are stored in AOS, ray packets in SOA, and streams support both AOS and SOA as input format. Internally, depending on the chosen traversal code path we convert from SOA to AOS or vice versa.

**Comment by capitalknew** [comment]
I tried in GPU (OpenGL 4.5 Compute) AoS layout BVH traverse (i.e. WARP of
32 divides by 4 components per ray), at now very laggy that technique.

**Comment by cbenthin** [comment]
That's interesting and probably an interesting research direction but not directly related to Embree so I'll close the issue for now.
