### ISSUE TITLE
32bit windows binaries

### ISSUE THREAD

**Issue by nitro44x** [embree/embree#139]
Is there any reason why 32-bit windows binaries were excluded from the releases? I don't mind building them myself... but I wasn't sure if they were explicitly excluded for any reason. It is a requirement for my application.

**Comment by nitro44x** [comment]
Ok I'm blind... I didn't see 32-bit under supported platforms the first time around.

**Comment by nitro44x** [comment]
Ok, last comment I promise. It looks like 32-bit was dropped only for v2.16.x. Can we get it back on the release schedule?

**Comment by cbenthin** [comment]
Hi, could you elaborate a bit on your use case for the 32bit windows version? We thinking about deprecating the 32bit version rather sooner than later as its usage its pretty rare and the supporting costs are rather high.
Thanks.

**Comment by nitro44x** [comment]
We are developing a library that will be integrated with 64bit and 32bit application. I've looked through building the code (without TBB) and it seems pretty straight forward. 

Does the static library in your release require the TBB dlls as well?

**Comment by svenwoop** [comment]
You have to build a static library version of Embree yourself. TBB is only provided as DLL version, thus you need the tbb.dll when enabling TBB as tasking system. However, you can get around that dependency by enabling the internal or PPL tasking system in CMake.

**Comment by jessep** [comment]
@cbenthin In my beta of our electron app, we got a lot of complaints from people running 32bit machines when we only released 64bit. Is it really rare that people release 32bit applications? Seems like Slack's default download is 32bit (https://slack.com/downloads/windows)

**Comment by nitro44x** [comment]
@svenwoop  @cbenthin 
We've gone ahead and built the static library (without TBB) and wrapped it in cmake import targets. Wasn't too bad. If and when we need TBB, it might get a bit more hairy. But that's tomorrow me's bridge to cross.

**Comment by amenzies** [comment]
Pre-built 32-bit binaries are nice for the C# wrapper #144.  This allows us to build a nuget package that works in the default "Any CPU" mode used by C#.  "Any CPU" mode defaults to 32-bit mode unless explicitly told to run in 64-bit mode only.  It's nice not to force a 64-bit dependency on consuming projects. 
 I wouldn't say this is a huge issue but it's nice to have as most nuget packages include both 32 and 64 bit native dependencies.

**Comment by cbenthin** [comment]
As there's a workaround to generate a static 32bit lib I'll close this issue for now.
