### ISSUE TITLE
Create a scene from bvh created by the rtcBuildBVH function

### ISSUE THREAD

**Issue by AbhayG27** [embree/embree#140]
Hi, I am using Embree to create a BVH with primitives with my custom memory layout (As shown in the bvh_builder example). I wanted to know if there is a way to create a RTCScene using this bvh and call rtcIntersect using that scene.

**Comment by svenwoop** [comment]
Embree cannot trace rays with your special BVH layout. You need to create an Embree scene with your geometry to trace rays (which will internally build a separate BVH).
