### ISSUE TITLE
Embree 2.16.4 crashes on particular CPU

### ISSUE THREAD

**Issue by ov** [embree/embree#141]
Hi there, we've just got a customer report that two our applications sharing the same version of embree - the latest 2.16.4 - crash on their Mac. Here's the part of the crash report they sent:

```
Operating system: Mac OS X
                  10.10.5 14F2511
CPU: amd64
     family 6 model 23 stepping 6
     8 CPUs

GPU: UNKNOWN

Crash reason:  EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
Crash address: 0x1f0
Process uptime: 3 seconds

Thread 0 (crashed)
 0  libembree.2.dylib + 0x77372
    rax = 0x0000608000132829   rdx = 0x0000608000132829
    rcx = 0x00006080001327a0   rbx = 0x0000000000000000
    rsi = 0x0000000000000001   rdi = 0x0000608000132829
    rbp = 0x0000608000132818   rsp = 0x00007fff5611c630
     r8 = 0x00007fff5611c410    r9 = 0x0000000000004200
    r10 = 0x0000000000003810   r11 = 0x00007fff5611c639
    r12 = 0x00007f94fc033f58   r13 = 0x00007f94fc033ff0
    r14 = 0x00007f94fc033f90   r15 = 0x00007f94fc032c00
    rip = 0x000000010b209372
    Found by: given as instruction pointer in context
 1  libCore.dylib!__ZN5SceneC2ER19IApplicationContextR12CoreInstance + 0x671
    rbx = 0x00007f94fc033f20   rbp = 0x00007fff5611c760
    rsp = 0x00007fff5611c670   r12 = 0x00007f94fc033f58
    r13 = 0x00007f94fc033ff0   r14 = 0x00007f94fc033f90
    r15 = 0x00007f94fc032c00   rip = 0x0000000109dac451
    Found by: call frame info
```

The second stack frame belongs to our application and looks like this:

```c++
auto rtcDevice = rtcNewDevice(nullptr);
auto rtcScene = rtcDeviceNewScene(rtcDevice, RTC_SCENE_DYNAMIC, RTC_INTERSECT1);
rtcCommit(rtcScene);
```

So it basically creates an empty scene for further usage. The code works fine in the field, except for that particular Mac, so I believe it must be something CPU-specific. According to the log above and [this site](http://www.speedtraq.com/) they have `Intel(R) Core(TM)2 Extreme CPU X9775 @ 3.20GHz`, but I am yet to confirm this.

The previous version of embree we shipped was 2.13 and we had no issues like that reported.

Hope this will help to track the issue.

Thank you.

**Comment by svenwoop** [comment]
Hi Vitaly,

I had a look into this and could identify the location where the bug occurs. It is essentially in rtcore.cpp line 250, and rtcore.h line 57. The call to e.what() is done, and afterwards likely reading device from scene seems to crash before calling Device::process_error. Thus is crashes inside the exception handling. The error occurred earlier and is not visible in the stack frame. rtcCommit has few cases where it might throw an exception, but none of these should be triggered for this empty scene.

Having output of  “sysctrl –n machdep.cpu.brand_string” might help. Also if he could put Embree to verbose mode and give us the output, maybe there is some interesting information (he can create an .embree2 file inside the application folder with the verbose=2 content).

Sven

**Comment by ov** [comment]
Hello Sven,

Thanks for your suggestions. I tried it here and got some logging from embree in console, but when I asked the customer to do the same, the log has no embree lines at all. It seems that embree crashes even before it prints something out. The software itself still prints some stuff to console, though, so the logging works.

Regarding the CPU, here's what they have: `Intel Xeon X5472 @ 3GHz`, according to sysctl.

Hope this helps.

I had a look at the rtcore lines you mentioned and it is not that clear what exactly might cause the crash, as we create device, then create a scene on that device and then commit the scene, so if it then access the device via scene, it should already have one assigned.

Any ideas how we can overcome that without waiting for the fix? Or maybe how we can reproduce it here?

Thank you.

**Comment by svenwoop** [comment]
Ok problem found. The issue is that with Embree v2.16.0 we started building our binaries with the lowest supported ISA being SSE4.2. As the customer machine has SSE4.1 support only the rtcNewDevice returns with an error code, which in the and causes the crash in rtcCommit.

Best always check the error code of rtcNewDevice and register some error callback function to safely catch errors that Embree might report.

We will discuss internally whether to enable SSE2 support again in precompiled binaries. You can also build the binaries yourself with SSE2 enabled (by just keeping the default CMake settings).

Regards,

Sven

**Comment by ov** [comment]
Thanks, that makes sense. Could you update this thread when you decide regarding the SSE2 support, please?

**Comment by svenwoop** [comment]
We will be adding SSE2 support again for the next release.

**Comment by ov** [comment]
Thanks for the update, appreciated. It would be nice if you mention minimum CPU requirements somewhere in release notes with every update, so we can keep an eye on it in the future.
