### ISSUE TITLE
C# Wrapper

### ISSUE THREAD

**Issue by amenzies** [embree/embree#144]
I've been looking into calling embree from C#.  I found a repo by TomCrypto with a C# wrapper which I have forked and have been updating to to use embree 2.15.  I have also configured it to build out to a nuget package so that anyone using C# can easily install the package and start ray tracing:
https://github.com/amenzies/Embree.NET/tree/feature/any_cpu_nuget

I wanted to note that having 32-bit binaries as per #139 is really nice because then the nuget package can be built to work in "Any CPU" mode. 

There are still some stability issues with the wrapper when using the 4 or 8 packet intersection options but before getting too deep into it I thought I'd create an issue here to seed some discussion about the C# wrapper and if it is something the embree community is interested in contributing to.

**Comment by jeffamstutz** [comment]
This seems interesting and could be relevant for [ospray](https://github.com/ospray/ospray) too.

Do you have any experience with something like [SWIG](http://www.swig.org/)? It would be nice if it was straightforward to map the API to multiple languages in one go instead of maintaining individual compatibility layers. I'm not well versed in managing API wrappers like this, so I don't have a good sense for how easy it would be to maintain.

**Comment by amenzies** [comment]
I have done a little bit of work with SWIG before.  I'm certainly not an expert so it took me a while to get all the calling conventions correct for more complex parameter types.  Integrating it into the visual studio build process was a bit tricky as well but I think it is probably easier with CMake.  Fortunately, the embree method signatures are all pretty simple.

TomCrypto's wrapper is a bit higher level which is great if you want to follow the interface pattern he lays out but I could definitely see the benefit of having a 1-to-1 direct C# wrapper.  

This is probably a bigger project than I have time for at the moment, but might go pretty quickly if there is a CMake expert out there.

**Comment by amenzies** [comment]
FYI, first version of the C# wrapper has been released on nuget:
https://www.nuget.org/packages/Embree.NET/

**Comment by cbenthin** [comment]
Pretty nice work indeed. Will reopen this issue if there's more interest in C# etc.
