### ISSUE TITLE
Bugs found by address sanitizers

### ISSUE THREAD

**Issue by obfuscated** [embree/embree#145]
I'm trying to find bugs in our application using the address sanitizer that is available in clang-3.9 on linux. Our application uses embree and I'm hitting errors inside embree.

I've tried to reproduce them in standalone embree and I was lucky, so they reproduce in every sample I've tried.
See the attached patch: [embree_asan.patch.zip](https://github.com/embree/embree/files/1208073/embree_asan.patch.zip) for the compiler options needed to reproduce it.

Just compile and then run ./verify.

**Comment by svenwoop** [comment]
Which Embree version do you use?

**Comment by obfuscated** [comment]
Built from commit 66c5b693ae6128c758b6d81554e541907c20a4e2 from the release branch.

**Comment by obfuscated** [comment]
Here is the output of the sanitizers for the verify application:  [embree.verify.sanitizer.output.txt](https://github.com/embree/embree/files/1209071/embree.verify.sanitizer.output.txt)

**Comment by cbenthin** [comment]
We'll have a closer look at this in the next couple of weeks. Need to double-check whether this could be a "false positive". BTW: Does the tool also report issues when using TBB instead of the internal tasking system?

**Comment by obfuscated** [comment]
I have not tried to reproduce the problem with TBB. We don't use TBB for embree...

**Comment by cbenthin** [comment]
Hmm, I've tried the sanitizer with clang-4.0 but get a lot of undefined references errors with compiling Embree, e.g.
 undefined reference to `__asan_report_load4'
undefined reference to `__asan_report_store4'
undefined reference to `__asan_report_load8'
 undefined reference to `__asan_handle_no_return'
...
How did you manage to avoid those errors?

Thanks.

**Comment by obfuscated** [comment]
@cbenthin: Have you tried to applied the patch supplied in the first post?
In short these errors come from -Wl,--no-undefined. You have to remove this linker option.

**Comment by cbenthin** [comment]
Sorry, my bad. Got it running now and the address sanitizer even reports this error when rendering an empty scene in single thread mode (./viewer --threads 1). I've looked into the code but I fail to see any reason for this strange error message.  I've also tried other tools like valgrind and got no error. It seems that this might be a false postive. Does your application crashes inside Embree?

**Comment by obfuscated** [comment]
Nope it doesn't crash. But I want to test it with sanitizers to make sure we don't do something wrong.

The explanation for this is that some lambda is destroyed, but still used, but the code is so complex that it is really hard to reason about it. :(

I'm not sure I could make a simplified repo case which could be given to clang/llvm/asan developers as bug report if this is indeed a false positive.

**Comment by cbenthin** [comment]
It'll probably require some effort to isolate a reproducer and it's unlikely that we'll manage that in the near future. Would be simpler if the app would simply crash or hang ;) I'll probably cross-check with other available mem-access checkers to lower the probability that we have overlooked something. That's probably the best I can offer at this point.

**Comment by jeffamstutz** [comment]
I'm going to tread lightly here, as C++ is a complex language and I'm always learning new things, but...

It's "sort-of" a false positive: technically ```embree::parallel_for()``` is binding the given lambda (an R-value reference) to a const L-value reference, which is then handed deeper into ```TaskScheduler::spawn()```. What ASan is picking up here is that the lifetime of the lambda could *technically* be shorter than the forwards through down to the internal tasking system. Because everything is getting inlined, however, the lifetimes end up OK anyway, hence no observed runtime issue.

This is what Scott Myers calls out the purpose of the "universal reference" is for, and therefore why ```std::forward<>()``` exists.

Now, am I correct? Definitely not sure. Should ```embree::parallel_for()``` take the body ```Func``` parameter as an R-value "universal" reference and use ```std::forward<>()``` instead? Probably. Regardless, not sure if that would fix the issue...but perhaps something to try.

I'm actually surprised that the compiler doesn't complain about the binding of an R-value to an L-value reference there (especially with -Wall enabled), but that could just point to me being full of hot air. :)

**Comment by obfuscated** [comment]
@jeffamstutz Making __forceinline to be just inline fixes the problem for me, so I'm not sure your explanation is correct in the part about inlining...

I'm trying to understand the code, but I'm incapable of digesting all this lambda stuff. Is this really the right approach here? Isn't it possible to make this code a little simpler?

**Comment by jeffamstutz** [comment]
Fair enough, my theory doesn't hold up. ;)

Ironically, the reason for the code looking this way is simplicity. I wrote a [blog post](https://jeffamstutz.io/2017/02/10/thread-parallelism-part-2-a-simple-parallel-for-wrapper/) on why you would want to write parallel code this way. The short answer: multi-threaded programming is hard, and when you want to scale up to hundreds of threads (i.e. Knights Landing), you need abstractions like ```parallel_for()``` to manage the huge amount of complexity behind feeding multi/many-core CPUs.

Regardless, we should probably add running the various built-in compiler sanitizers for both Embree and OSPRay within their respective test suites.

**Comment by svenwoop** [comment]
I found the issue, this was indeed a bug in the internal task scheduler. The commit 27b8903017c95d2c2e91f2309a1a66882a6f2a48 fixes this issue. The other commits below fix further issues that prevented verify to run through when stack sanitizer checks were enabled.

commit 2d44c1c34068f358900725b15bb6cc45440f59d5
Author: Sven Woop <sven.woop@intel.com>
Date:   Fri Oct 6 11:22:03 2017 +0200

    fixed potential memory leak when exception was thrown when using internal tasking system

commit 7b5569e4aed4d04634754b77662212f0bc5b1987
Author: Sven Woop <sven.woop@intel.com>
Date:   Fri Oct 6 11:08:02 2017 +0200

    fixed 16 byte padding of some vertex arrays in verify

commit 27b8903017c95d2c2e91f2309a1a66882a6f2a48
Author: Sven Woop <sven.woop@intel.com>
Date:   Fri Oct 6 10:55:18 2017 +0200

    fixed issue reported by clang address sanitizer
