### ISSUE TITLE
Disable/Remove a single instance

### ISSUE THREAD

**Issue by russgayle** [embree/embree#146]
I'm working on a embree wrapper for an application that uses geometry instancing to mimic the state of a scene graph. It's common for us to disable and remove single instances on the scene graph but I didn't see a good way to do this with embree. 

Right now, I'm just setting the instance's transform to be outside of my area of interest which suffices. But, is there a better way to do this? Did I miss something in the API to support this (other than disabling or deleting the associated scene and/or geometry)?

**Comment by cbenthin** [comment]
Hi,
the intended way to do this is to disable/delete the associated scene/geometry. Does this behaviour cause issues on your side?
Just to get a better understanding: You want to remove single instances from Embree and replace them with new a non-instanced geometry/scene? If this due to expected performance gains?

Thanks.

**Comment by russgayle** [comment]
Hi, 

Not quite; I'm just looking to be able to toggle instances on/off (so that their geometries or their scenes remain active elsewhere), e.g. to simulate the state of a single door as open or closed or to remove a single door in a scenario where other there are many doors. I'd like to use instances so I'm not creating so much additional (identical) geometry. I'm not trying to replace them with anything... 

If I remember correctly from my (limited) testing, deleting the scene or geometry associated with the instance caused all of the instances to be removed, not a single one. 

Thanks!

**Comment by cbenthin** [comment]
If you use geometries and have a "dynamic" scene you should be able to quickly enable/disable individual instances (per frame) using rtcDisable/rtcEnable. I don't think our instance tutorial does something like that but it should actually work.

**Comment by russgayle** [comment]
Ah, ok. From the function signature (`RTCORE_API void rtcEnable (RTCScene scene, unsigned geomID)`) I just assumed that it only applied to geometries (rather than the `unsigned`s that are produced by `rtcNewInstance`). I'll give that a try shortly and see if to works for me. 

Thanks!

**Comment by cbenthin** [comment]
Did it work for your application?

**Comment by russgayle** [comment]
Sorry for the delay! Yes, this did work for what we're doing. Thanks!
