### ISSUE TITLE
Compile warnings in rtcore_ray.h with -Wpendantic

### ISSUE THREAD

**Issue by Anteru** [embree/embree#147]
I'm getting a bunch of warnings in `rtcore_ray.h` -- all of them are trailing ';' which should be easy enough to fix. Attached is the output. This affects libraries using Embree compiled with `-Wpendatic`.

[warnings.txt](https://github.com/embree/embree/files/1254619/warnings.txt)

**Comment by cbenthin** [comment]
Thanks!  Fixed in the devel branch so the next version of Embree will include the changes.
