### ISSUE TITLE
Fatal error LNK1104:can't open file tbb_debug.lib

### ISSUE THREAD

**Issue by yangshuang-developer** [embree/embree#148]
when i compile the embree source code by vs2015 with cmake and tbb( latest binary release) ,i get the error

**Comment by cbenthin** [comment]
I guess you are compiling in "debug" mode and there are no TBB debug libraries on your system. Does the error go away when you compile in "release" mode? BTW: You can grab the latest TBB version including tbb_debug.lib from: https://github.com/01org/tbb/releases

**Comment by yangshuang-developer** [comment]
i use the cmake gui to config the source code ,the default configuration is debug x64 ,and i have checked the tbb_debug.lib is in the directory like tihs embreeroot/tbb/lib/intel64/vcxx/tbb_debug.lib

**Comment by yangshuang-developer** [comment]
the TBB libraries  version is the latest release tbb2017_20170604oss_win.zip

**Comment by cbenthin** [comment]
Hmm, just downloaded the latest tbb2017_20170604oss_win.zip and set EMBREE_TBB_ROOT in cmake to the unpacked TBB directory (../tbb2017_20170604oss) and it works without problems on my end. Did you set EMBREE_TBB_ROOT in cmake? The CMAKE_CONFIGURATION_TYPES should also be left unchanged.

**Comment by johguenther** [comment]
Actually, Embree does not link against `tbb_debug.lib`, but uses `tbb.lib` also in `Debug` mode. Can you please double-check the content of the advanced CMake variable `TBB_LIBRARY`?

**Comment by yangshuang-developer** [comment]
thank you，but i can't find the  TBB_LIBRARY variable while only have the EMBREE_TBB_ROOT variable point to the directory embree_root/tbb ,only have this error in debug x64,the release configuration is work well.

**Comment by yangshuang-developer** [comment]
I try to print the TBB_LIBRARIES variable in the CMakeLists.txt after line 350 where the FIND_PAKAGE(TBB <options>) execute,the output is the directories of tbb.lib and tbbmalloc.lib,all in right directory

**Comment by johguenther** [comment]
`TBB_LIBRARY` is an advance variable and thus not shown per default – click the “Advanced” checkbox in CMake-gui to see it nevertheless. Anyway, your print of `TBB_LIBRARIES` confirms that Embree does not try to link against `tbb_debug.lib`.

So, when does the error happen? When linking `embree.dll`? Can you please double-check the linker arguments when linking failes, e.g. in VS: property page &rarr; Linker &rarr; Command Line?

**Comment by yangshuang-developer** [comment]
No,the reason is that _DEBUG configuration will effect the tbb_config.h

**Comment by yangshuang-developer** [comment]
And it will open the macro __TBB_NO_IMPLTCIT_LINKAGE,then link the ttb_debug.lib

**Comment by johguenther** [comment]
Interesting. However, this still does not explain the error: `__TBB_NO_IMPLTCIT_LINKAGE` is only relevant when `runtime_loader.h` is included, which Embree does not do.

I , too, cannot reproduce the linker error. So again, when does it actually happen?

**Comment by yangshuang-developer** [comment]
Downloaded the latest tbb2017_20170604oss_win.zip and set EMBREE_TBB_ROOT in cmake to the unpacked TBB directory (../tbb2017_20170604oss , i rename the directory to tbb as the readme.md say),and use the CMake GUI to config the embree,then open the embree2.sln with visual studio,it happend.

**Comment by yangshuang-developer** [comment]
when i put the  "ADD_DEFINITIONS(-DTBB_USE_PREVIEW_BINARY)" in CMakeLists.txt ,the error disappear~
 the Release is always work well.

**Comment by yangshuang-developer** [comment]
file "tbb2017_20170604oss/include/tbb/internal/_tbb_windef.h" will link the tbb_debug.lib ,is it the reason?

**Comment by cbenthin** [comment]
Could you try the following and dd the following lines starting at line 30 in taskschedulertbb.h:

#define __TBB_NO_IMPLICIT_LINKAGE 1
#define __TBBMALLOC_NO_IMPLICIT_LINKAGE 1

Thanks.

**Comment by yangshuang-developer** [comment]
@cbenthin I do

**Comment by yangshuang-developer** [comment]
@cbenthin 
I add the macro 
----
#define __TBB_NO_IMPLICIT_LINKAGE 1
#define __TBBMALLOC_NO_IMPLICIT_LINKAGE 1
----
into the "taskschedulertbb.h" ,then it works.
Thank you for you solution,great.
