### ISSUE TITLE
Stream traversal of user geometry

### ISSUE THREAD

**Issue by mathijs727** [embree/embree#150]
Hi,

As mentioned in my other thread (issue #149), I've been experimenting with getting lazy loading to work in Embree.
I got it working in single ray mode (based on the lazy geometry tutorial) but not in stream traversal mode.

After spending a ton of hours determining the bug is not on my side, I tried to add stream traversal to the lazy geometry tutorial.
I removed the shadows (so I dont need to implement the occluded function) and replaced the intersection function by the following:
```cpp
LazyGeometry* instance = (LazyGeometry*) instance_i;

/* create the object if it is not yet created */
if (instance->state != LAZY_VALID)
    lazyCreate(instance);

if (N > 1)
    std::cout << "More than one ray" << std::endl;

std::vector<unsigned int> geomIDs(N);
std::vector<unsigned int> masks(N);
for (size_t i = 0; i < N; i++) {
    geomIDs[i] = RTCRayN_geomID(rays, N, i);
    RTCRayN_geomID(rays, N, i) = RTC_INVALID_GEOMETRY_ID;

    // Disable inactive rays
    masks[i] = RTCRayN_mask(rays, N, i);
    if (!valid[i])
        RTCRayN_mask(rays, N, i) = 0;
}

rtcIntersectNM(instance->object, context, rays, N, 1, item);

for (size_t i = 0; i < N; i++) {
    // Restore original masks
    RTCRayN_mask(rays, N, i) = masks[i];

    if (RTCRayN_geomID(rays, N, i) == RTC_INVALID_GEOMETRY_ID)
    {
        RTCRayN_geomID(rays, N, i) = geomIDs[i];
    } else {
        RTCRayN_geomID(rays, N, i) = instance->userID;
        RTCRayN_instID(rays, N, i) = RTC_INVALID_GEOMETRY_ID;
    }
}
```

To traverse I call rtcIntersect1M on a tile of rays.
However, I now get black stripes through the (lazy loaded) balls.
This also happens while you move around, so it is not a problem with the lazy loading itself (which only happens when an object first appears).
Replacing the call to rtcIntersect1M by a for loop of rtcIntersect calls fixes the issue.

Surprisingly, even with rtcIntersect1M, the N parameter passed to the intersectFuncN is always 1.

Im using Embree 2.16.5 (compiled with GCC 4.8.5).
Here is the updated file (replaces [yourembreepath]/tutorials/lazy_geometry/lazy_geometry_device.cpp):
[lazy_geometry_device.cpp.tar.gz](https://github.com/embree/embree/files/1265291/lazy_geometry_device.cpp.tar.gz)

Is there something wrong with my code or is this a bug in Embree?

Thanks,
Mathijs

**Comment by cbenthin** [comment]
Thanks, I can reproduce the issue and looking into it...

**Comment by cbenthin** [comment]
Unfortunately it seems that we are hitting a GCC compiler bug. I've tested your code with clang 4.x and ICC 17.x and it works fine. Isolating the spot where GCC produces wrong code will take some time though...

**Comment by cbenthin** [comment]
BTW: It works with GCC in DEBUG mode but not in RelWithDebInfo or Release...

**Comment by cbenthin** [comment]
OK, tracked it down and the issue is that the old GCC 4.8.5 compiler produces buggy AVX2 code. As a workaround you can limit the isa by setting the EMBREE_MAX_ISA variable to AVX instead of AVX2. With these changes it works in Release and RelWithDebInfo mode on my system. Nevertheless, I recommend to use a newer GCC version as Embree officially supports only GCC version 5.4.0 or higher.

**Comment by mathijs727** [comment]
Thanks for the quick reponse.
Recompiling the sample with AVX (instead of the default AVX2) does indeed fix the problem.

I compiled Embree with ICC 18.0.0 Beta for the AVX512 support (for testing on a Skylake machine).
This fixes the issue in the tutorial but not with our own application (which is compiled and linked (against thxXe ICC compiled Embree) by GCC4.8.5).
Switching to GCC5.3.1 also did not work, but compiling the user application with GCC 6.3.1 and than linking against the ICC compiled Embree finally fixed the issue.
