### ISSUE TITLE
unsigned type doesn't compile with ispc

### ISSUE THREAD

**Issue by rgba32** [embree/embree#153]
We seem to be running into problems compiling these prototypes. I believe these standalone "unsigned" types should be "unsigned int"?

https://github.com/embree/embree/blob/fbeaa1002fc9c328d14ef06ade213395aff51033/include/embree2/rtcore_geometry.isph#L168

**Comment by rgba32** [comment]
(We're using ISPC 1.9.1 btw)

**Comment by svenwoop** [comment]
We also use ISPC 1.9.1 for testing. Weird that we do not see errors. I replaced all unsigned usages in the ISPC code by unsigned int, which will fix this in the next Embree release. Just also replace each problematic unsigned type.

**Comment by rgba32** [comment]
I not sure why we see these errors and you don't. Perhaps we're using different options somewhere in the build process since we ported the build steps to scons. After we made the unsigned int changes locally, we were able to build again. Anyway, thanks for the fix Sven!

**Comment by jeffamstutz** [comment]
By any chance are you using ISPC from the Arch linux package manager? I've seen issues when enabling AVX512SKX targets using _their_ compiled version of ISPC: it doesn't crash when using the official ISPC pre-built binary packages.

Just a hunch...perhaps there's a way to compile ISPC in a way that doesn't like Skylake targets. (?)
