### ISSUE TITLE
build fails on Ubuntu 17.04

### ISSUE THREAD

**Issue by ingowald** [embree/embree#155]
Just tried building embree on a newly installed Ubuntu 17 machine, but build fails because TBB can't be found - and worse than that, it fails even after trying to manually set TBB variables. 

Root problem is that ubuntu 17 installs libtbb*.so into /usr/lib/x86_x64-linux-gnu/, which is neither in the defautl search paths, nor in the explicit search path list. Even worse, the cmake file _continues_ to fail even if I manually set the cmake variables for the tbb libs in the cmake dialog - i can enter the right paths/file names, but as soon as i press 'c' the embree build scritps reset those values, and again fail with 'not found'.

Interestingly, the build _does_ run through if - as root - i manually symlink /usr/lib/x86_..../libtbb* to /usr/lib/ (symlinking to /lib64 does not work, though).

**Comment by johguenther** [comment]
Fixed in f34b975.

**Comment by svenwoop** [comment]
The EMBREE_TBB_ROOT path has precedence over the TBB_LIBRARY variables. If you want to specify the path to TBB by hand set EMBREE_TBB_ROOT to the empty string.
