### ISSUE TITLE
Remove glut dependency

### ISSUE THREAD

**Issue by ingowald** [embree/embree#156]
Latest master branch fails to build if glut isn't installed. Manually setting "BUILD_TUTORIALS" fixes this, but this might not be immediately obvious to the average user.

Would suggest the following change: Embree tries to find GLUT, and if it doesn't it a) warns about it, and b) turns off the tutorials (the rest of embree doesn't require glut, anyway).

**Comment by svenwoop** [comment]
Fixed in devel branch.
