### ISSUE TITLE
Improve documentation of BVH builder

### ISSUE THREAD

**Issue by florianlink** [embree/embree#158]
I want to use Embree to create my own BVH2 (for GPU traversal, so I don't want the BVH4/8).

I got the tutorial bvh builder running, but have some questions about it, which I think would make sense to be added to the documentation of the Embree API:

a) How is the memory of the nodes managed/who owns it? They are allocated with the RTCThreadLocalAllocator. Does the Embree BVH own it and destroy it when the BVH is deleted via Embree API?

b) Internally I saw that the primitives are kept in range<size_t>, but in RTCCreateLeafFunc, one only gets

const RTCBuildPrimitive* prims, size_t numPrims

Is it safe to calculate the start offset by using the prims pointer (and the original primitive pointer that was passed into the function?), because I want to store the range in my LeafNode? Is it safe to assume that the range will not change afterwards (that the primitives in the range will not change/be sorted) or do I need to copy the primitive ids at that time?

c)  I guess the input primitives are modified when calling the rtcBuildBVH, right? Can I free the memory after building the BVH, or does it still reference the primitives somehow? (except for the ranges that I would store in my leafs).

(I hope it is ok to write this as an issue?)

**Comment by florianlink** [comment]
My questions have been answered on this thread:

https://software.intel.com/en-us/forums/embree-photo-realistic-ray-tracing-kernels/topic/746462 

I think it would be great to add this to the API documentation so that other people can benefit from it.

**Comment by cbenthin** [comment]
Thanks, we'll add them to the doc.

**Comment by cedricp** [comment]
Hi,
I'm looking for a function that ray-intersects a custom BVH structure, maybe am I missing something in the documentation ?

**Comment by svenwoop** [comment]
You can use the BVH builder API to build a BVH of a custom layout. However, Embree provides no way of traversing such a custom BVH. For traversal you have to use the internal BVH layouts by creating a scene and tracing rays through that scene.

**Comment by cedricp** [comment]
Okay, that's what I wanted to know. Thank you. Is there any example on how to achieve the traversal ?

**Comment by cbenthin** [comment]
You mean "traversal example" of a custom layout BVH (which obviously depends on the exact layout) or the traversal of the internal BVHs?

**Comment by svenwoop** [comment]
Could you describe what you are trying to calculate? Do you really need a custom BVH?
