### ISSUE TITLE
Static scene changes without affecting the BVH structure?

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#161]
I'm not sure if this makes sense since I don't know the Embree internals. But there are functions like
rtcSetIntersectionFilterFunction
rtcSetOcclusionFilterFunction
rtcSetUserData
rtcSetMask

which don't affect directly the BVH structure. I understand that the static Embree scenes (RTC_GEOMETRY_STATIC) must bake even those in some way. But if such change is required, what is the best/optimal way to do it? Such way should avoid rebuilding the whole BVH all over again IMO.

**Comment by svenwoop** [comment]
We currently do not bake in these data (but once baked in the mask in the past). We just want to leave us the option to bake these in for static scenes, if we figure out that this makes sense for performance reasons. You can hack the code and just comment out the lines that raise the error when modifying these values.

**Comment by svenwoop** [comment]
BTW, you can also just create a dynamic scene, where modifying these values is supported.
