### ISSUE TITLE
BVHNIntersector1 in Embree 2.13 and Intel Compiler 14.x-16.x

### ISSUE THREAD

**Issue by blu** [embree/embree#162]
Hello,

It seems BVHNIntersector1<N,types,robust,PrimitiveIntersector1>::intersect() from Embree 2.13 experiences major codegen issues under ICL (Intel Compiler for Windows) v14.x through v16.x -- the intersect() method suffers from major register spillage, rendering the intersector ~2x slower than Embree 2.3 for same compilers under similar scenarios. The issue is partially resolved through de-inlining of the primitive intersectors in BVHNIntersector1::intersect(), but that seems like a hack. Is there a known good ICL setup that avoids that? Clarification: I'm building for SSE2 - SSE4.2 targets and I have passed /Qinline-max-total-size- /Qinline-factor=200 to the compiler.

**Comment by cbenthin** [comment]
This also happens for Embree 2.17? Is this for 32bit or 64bit builds? 
Can you render the crown model with the example pathtracer and report the performance together your machine config? 

 I've just tested it with Vs2015 + ICC v17.0.4 and v18.0.0 (64bit builds) and it works fine on my windows 10 machine. Will try v16.x next and get back to you...

**Comment by cbenthin** [comment]
I've tested v2.17 with ICC v16.0.3 and got no regressions versus ICC v17.x or v18.x. I've used the example pathtracer and the crown model from the web page and forced the Embree ISA to sse2 only, e.g.:  ./pathtracer -c crown/crown.ecs  --size 1920 1080 --rtcore isa=sse2 --verbose 2

Do you generate the sln files with cmake or do you use a custom build step? Can you link your app against the binary versions of Embree v2.17 and measure performance again? That should be the expected base-line performance.

**Comment by blu** [comment]
I've localized the issue on my end -- an /Ob2 was creeping into the Embree build flags, whereas /Ob1 is the right flag for avoiding the inlining of the primitive intersector into BVHNIntersector1::intersect(), causing the register allocator calamity in ICL.
