### ISSUE TITLE
Deadlock with displacement

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#163]
I've started to get deadlocks with displacement. Not sure in which version. Seems to happen with both 2.16/2.17.  It's always in SharedLazyTessellationCache. Both reset_state and linkedlist_mtx get locked. Most threads are in allocNextSegment(). There is one in getNextRenderThreadWorkState() and one in sharedLazyTessellationCache.lockThreadLoop(). Subdivision is working fine. I tried also with the official embree build, but the same result. Any ideas?

**Comment by cbenthin** [comment]
Hi,
can you share your displacement shader code or provide binary reproducer which we could use to track the issue down? Does the displacement shader code uses any thread locking or similar mechanism which could potentially stall threads?

In 2.16/2.17 Embree uses per default for static scenes the internal "pregenerate" mode for handling subdivision instead of using the tessellation cache. Do you use a dynamic or static scene?

**Comment by svenwoop** [comment]
Also, do you use rtcInterpolate for subdivs?

**Comment by ivalylo** [comment]
Yes, that was it! I switched to dynamic scene to be able to change the ray filter and mask. There is no problem if I use static scene. I use rtcInterpolate also. There is no locking in the displacement function.

**Comment by ivalylo** [comment]
Any progress on that?
The issue is like you guessed in rtcInterpolate. To reproduce it in the displacement tutorial, just use something like this for the displacement func:

`
  for (unsigned int i=0; i<N; i++) {

     Vec3fa dPdu,dPdv;
   rtcInterpolate(g_scene,g_cube, 0, u[i], v[i],RTC_VERTEX_BUFFER,nullptr,&dPdu.x,&dPdv.x,3);

    const Vec3fa P = Vec3fa(px[i],py[i],pz[i]);
    const Vec3fa Ng = Vec3fa(nx[i],ny[i],nz[i]);
    const Vec3fa dP = displacement(P)*Ng;
    px[i] += dP.x; py[i] += dP.y; pz[i] += dP.z;
  }
`

where
`g_cube  = addCube(g_scene);`

 You need to increase the displacement levels:
`#define EDGE_LEVEL 512.0f`

There is also another issue, maybe related? Even if you have empty displacement func, when using a dynamic scene, the rendering is much slower. On your example, it's something like 30 vs 38 MRays/s on my computer. But in my application with real geometry, the slow down is measured in magnitudes.

**Comment by cbenthin** [comment]
So far it seems the tessellation cache which is used by rtcInterpolate is too small for an edge level of 512. Could you increase its size by 

  rtcDeviceSetParameter1i(g_device,RTC_SOFTWARE_CACHE_SIZE,400*1024*1024);

and try again?

**Comment by ivalylo** [comment]
I can, but:
1) this is bad software design. Slow down to some degree is acceptable. But the application can't just crash/deadlock because of a parameter that needs tweaking. 
2) Sven Woop told me to use a dynamic scene to be able to change ray masks, user data, filter functions, which is currently disabled in static scenes (issue #161). But obviously the dynamic scenes have a performance and memory hit even though the geometry inside is static. I really don't like hacking embree to achieve such general thing.

These are two design issues that look disturbing to me as a software engineer :). Embree is great piece of software, hopefully there is a better solution for those two.

**Comment by cbenthin** [comment]
I'm currently looking into the issue, setting the tess cache to larger size was more intended as a quick workaround. The interesting question is why the default tess cache triggers a deadlock with your config. That's what I'm currently looking at...

**Comment by cbenthin** [comment]
OK, so the internal issue is a combination of multiple things: first the displacement shader calls rtcInterpolate and second the lazy subdiv intersector (used in dynamic mode) and the displacement shader through rtcInterpolate which both use the tess-cache simultaneously are blocking each other as the allocation required by rtcInterpolate is too large (almost filling an entire tess-cache segment). To guarantee forward progress the segment size must be larger than "#threads * maximum allocation size used by rtcInterpolate". Increasing the tess-cache size helps to prevent this but I full agree the user should have to do this.

We'll replace the tess-cache in Embree 3.x to avoid all this hassle with the tess-cache. For now the simplest workaround is to get rid of the lazy subdiv intersector used in the dynamic mode. Could you replace in scene.cpp line 511 the following

      if (isStatic())
        accels.add(device->bvh4_factory->BVH4SubdivPatch1Eager(this));
by
      if (1)
        accels.add(device->bvh4_factory->BVH4SubdivPatch1Eager(this));

and test again. Sorry for the hassle.

**Comment by ivalylo** [comment]
Thank you, that fixed the issue. No deadlock, no slow down.
