### ISSUE TITLE
Location of cmake files

### ISSUE THREAD

**Issue by paulmelis** [embree/embree#164]
The Linux binary tarball (i.e. https://github.com/embree/embree/releases/download/v2.17.0/embree-2.17.0.x86_64.linux.tar.gz) contains two .cmake files. These are located in the root of the tarball, which is somewhat non-standard (they're usually in `lib/cmake/<version>`). E.g. when building ospray you're instructed to point `embree_DIR` to the subdirectory `lib/cmake/embree-2.17.0`, which doesn't exist.

```
paulm@cmstorm:/data/c/ospray-release$ ./.conf.sh 
CMake Error at cmake/ospray_macros.cmake:45 (message):
  We did not find Embree installed on your system.  OSPRay requires an Embree
  installation >= v2.13.0, please download and extract Embree or compile
  Embree from source, then set the 'embree_DIR' variable to
  <embree-install-dir>/lib/cmake/embree-<version>.
Call Stack (most recent call first):
  cmake/configure_embree.cmake:20 (ospray_find_embree)
  cmake/ospray_options.cmake:114 (INCLUDE)
  CMakeLists.txt:50 (INCLUDE)
```

PS Not sure if it really matters for CMake where these files are.

**Comment by johguenther** [comment]
The actual intention is allow CMake to find Embree by just pointing `embree_DIR` to the unpacked root folder (i.e. just `<embree-install-dir>`) rather to some intuitive folder several levels deeper. The above error message has already been updated to reflect that (will be in the soon coming release v1.4.1 of OSPRay).

Please note the the rpm-based distribution still follows the `lib/cmake/<version>` convention.
