### ISSUE TITLE
internal compiler error: in pop_binding, at cp/name-lookup.c:382

### ISSUE THREAD

**Issue by russgayle** [embree/embree#165]
I was trying to build the 2.17.1 tagged release on CentOS 6.9 and am getting the following error (I manually truncated the paths to just embree relevant portions): 
```
In file included from ../embree/common/sys/../algorithms/../tasking/taskscheduler.h:20:0,
                 from ../embree/common/sys/../algorithms/parallel_for.h:19,
                 from ../embree/common/sys/mutex.cpp:19:
../embree/common/sys/../algorithms/../tasking/taskschedulerinternal.h: In lambda function:
../embree/common/sys/../algorithms/../tasking/taskschedulerinternal.h:326:2: internal compiler error: in pop_binding, at cp/name-lookup.c:382
  });
  ^
Please submit a full bug report,
```

For a little more information, we did install an updated version of gcc onto the machine (devtools-2, via software collections rather than the install script). 
```
[build]$ which c++
/opt/rh/devtoolset-2/root/usr/bin/c++
[build]$ c++ --version
c++ (GCC) 4.8.2 20140120 (Red Hat 4.8.2-15)
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
[build]$ uname -r
2.6.32-696.6.3.el6.x86_64
[build]$ cat /etc/redhat-release
CentOS release 6.9 (Final)
```

On a quick google search, I think this is https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63385. For various reasons, it'll be difficult for us to update to a newer 4.8.x version of gcc. Do you know if this is something that can easily be fixed/changed in embree? 

If not, you may want to have the install script pick a more recent version of gcc. (And, 2.16.5 works over here, so we can use that for now.)

Thanks!

**Comment by svenwoop** [comment]
Have no redhat install to reproduce this. One workaround could be to just enable TBB as tasking system. Is this an option?

**Comment by svenwoop** [comment]
Also could you please check if the issue if fixed when renaming the closure input variable to something else. According to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63385 this should work around the issue.

**Comment by russgayle** [comment]
Sorry for taking a while to get back! 

* No, unfortunately we can't use TBB on that platform at this point in time.

* Yep, changing the input variable name (and the associated references to it in the code) did allow me to get through the compilation. I can open a pull request if you'd like? (it only changes a couple of lines)

Thanks!

**Comment by svenwoop** [comment]
Yes please open a pull request.

**Comment by cbenthin** [comment]
Please re-open if the issue still exists.
