### ISSUE TITLE
Pre-tessellated option?

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#166]
This is for the wishlist. Simple option to bake the tessellation for subdivision and displacement. It can be used for smaller tessellation levels which seem to not conserve any memory, but only slow down the rendering. I know there is OpenSubdiv, but it will be less messy if Embree can do it.

**Comment by joesfer** [comment]
Seconding this request - we're currently treating the trivial 0 iterations case (where we just treat the polygon cage as a straight mesh), but low levels of subdivisions would be desirable too.

**Comment by cbenthin** [comment]
That's high on our Embree 3.x todo list to improve memory consumption for low subdiv levels. Would a slighty lower ray tracing performance compared to the case where the application converts the subdiv mesh into a Embree triangle/quad mesh be acceptable in your use cases?

**Comment by ivalylo** [comment]
It depends on the performance I guess. With the current Embree version and this scene (http://www.manujarvinen.com/portfolio/2016_cheese_attack.jpg), I get 950 sec with Embree subdivision vs 750 sec with tessellation done in Blender. The subdivision levels are pretty low (4-6), but affect a lot of small objects. This is from the Visual Studio profiler:

```
Function Name	Inclusive Samples	Exclusive Samples	Inclusive Samples %	Exclusive Samples %
embree::AccelN::intersect	16,703	100	15.61	0.09
embree::AccelN::occluded	54,250	291	50.71	0.27
embree::array_t<embree::CatmullClark1RingT<embree::vfloat<4>,embree::vfloat<4> >,4>::array_t<embree::CatmullClark1RingT<embree::vfloat<4>,embree::vfloat<4> >,4>	10	10	0.01	0.01
embree::array_t<embree::CatmullClark1RingT<embree::vfloat<4>,embree::vfloat<4> >,4>::operator=	641	641	0.60	0.60
embree::avx::BVHNIntersector1<4,1,0,embree::avx::ArrayIntersector1<embree::avx::TriangleMiIntersector1Moeller<4,4,1> > >::intersect	500	417	0.47	0.39
embree::avx::BVHNIntersector1<4,1,0,embree::avx::ArrayIntersector1<embree::avx::TriangleMiIntersector1Moeller<4,4,1> > >::occluded	2,046	2,012	1.91	1.88
embree::avx::BVHNIntersector1<4,1,1,embree::avx::SubdivPatch1EagerIntersector1>::intersect	16,103	16,079	15.05	15.03
embree::avx::BVHNIntersector1<4,1,1,embree::avx::SubdivPatch1EagerIntersector1>::occluded	51,913	50,002	48.52	46.74
embree::avx::FeatureAdaptiveEval<embree::vfloat<4>,embree::vfloat<4> >::eval	3,038	462	2.84	0.43
embree::avx::FeatureAdaptiveEval<embree::vfloat<4>,embree::vfloat<4> >::FeatureAdaptiveEval<embree::vfloat<4>,embree::vfloat<4> >	3,070	32	2.87	0.03
embree::avx::PatchEval<embree::vfloat<4>,embree::vfloat<4> >::eval	4,783	914	4.47	0.85
embree::avx::PatchEval<embree::vfloat<4>,embree::vfloat<4> >::eval_general	2,612	125	2.44	0.12
embree::avx::PatchEval<embree::vfloat<4>,embree::vfloat<4> >::PatchEval<embree::vfloat<4>,embree::vfloat<4> >	5,468	684	5.11	0.64
embree::avx::SubdivMeshISA::interpolate	6,234	766	5.83	0.72
embree::BSplinePatchT<embree::Vec3fa,embree::Vec3fa>::init	120	120	0.11	0.11
embree::BSplinePatchT<embree::vfloat<4>,embree::vfloat<4> >::eval	754	754	0.70	0.70
embree::CatmullClarkPatchT<embree::vfloat<4>,embree::vfloat<4> >::subdivide	1,689	1,689	1.58	1.58

```
The scene is available here:
http://files.manujarvinen.com/cheese_attack_CC0.blend

**Comment by cbenthin** [comment]
The new grid primitive introduced with Embree 3.1 offers a compact way to store displaced subdivs or any other grid-like structure. This might be helpful if your application is already setup to do the subdivision and displacement anyway.

**Comment by ivalylo** [comment]
Looks interesting, but are there any known issues when baking subdivision in this way? How exactly non-quad faces are working? I can see this comment in the tutorial, but can't quite get it:

> each quad becomes one grid, other faces become multiple grids

**Comment by svenwoop** [comment]
If you have a non-quad you would essentially use n-quads to dice the face, e.g. for a pentagon you would create 5 grids, similar to the left figure here https://renderman.pixar.com/resources/RenderMan_20/hierarchsubdiv.html. An example of this can be found in the grid_geometry tutorial. This tutorial also uses the rtcInterpolate API to evaluate the subdivision surface and generate the grids. The tutorial also demonstrates how to use the topology walk API to average neighboring face normal to calculate per vertex shading normals in case of displaced subdiv grids.

**Comment by svenwoop** [comment]
BTW, grids should only be used for larger tessellation levels (8x8 grid and larger) as otherwise the memory savings are low or non existent. For low tessellation levels one should dice into a quad mesh.
