### ISSUE TITLE
An issue in embree2_to_embree3.patch

### ISSUE THREAD

**Issue by akegure** [embree/embree#171]
Thank you for improving embree. I'm trying to use the new version.
When I use cpp-patch.py with embree2_to_embree3.patch to convert my program, rtcSetBuffer2 is rewritten to rtcSetBuffer, but there is no definition of rtcSetBuffer in embree3. I think rtcSetSharedGeometryBuffer is the correct alternative for this function.

Is there a plan to update embree2_to_embree3.patch?

**Comment by svenwoop** [comment]
Yes, you should use rtcSetSharedGeometryBuffer there. I looked at the conversion script, and it seems correct. Could you please send us the original code line with the rtcSetBuffer2 call, such that I can figure out why that function was not replaced properly.

**Comment by akegure** [comment]
The following code is my original code with rtcSetBuffer2.
`rtcSetBuffer2(m_scene, index, (RTCBufferType)RTC_VERTEX_BUFFER, &qm->getVertex().get()[0][0], 0, sizeof(float) * 4, qm->getNumVertex());`

And after applying embree2_to_embree3.patch, it becomes like this.
`		rtcSetBuffer(geom_1
,(RTCBufferType)RTC_BUFFER(RTC_BUFFER_TYPE_VERTEX,0)
,&tm->getVertex().get()[0][0],0,sizeof(float) * 4,tm->getNumVertex())
;	`

Thank you.

**Comment by svenwoop** [comment]
Added a fix for this to the devel branch. Next release will not have this issue.
