### ISSUE TITLE
Error in Windows `embree-config.cmake` with embree 3.0.0 beta

### ISSUE THREAD

**Issue by Gjacquenot** [embree/embree#175]
When I try to use the binary distribution for embree 3.0.0 beta for Windows, I have a CMake error with command

    target_link_libraries(application ${EMBREE_LIBRARY})

It tells me that the `lib/embree.lib` file is not found.

It comes from an error in the `embree-config.cmake` file, where `EMBREE_LIBRARY` is not correctly defined.

It can be easily fixed by replacing the following instructions:

    SET(EMBREE_LIBRARY ${EMBREE_ROOT_DIR}/lib/embree.lib)

with 

    SET(EMBREE_LIBRARY ${EMBREE_ROOT_DIR}/lib/embree3.lib)

It does not seem to the case for Macos

    SET(EMBREE_LIBRARY ${EMBREE_ROOT_DIR}/lib/libembree.3.dylib)

I have not checked for Linux platforms...

**Comment by svenwoop** [comment]
Thanks for reporting, this is broken on all platforms. We will fix this for the final Embree 3 release.
