### ISSUE TITLE
signed/unsigned warning in header

### ISSUE THREAD

**Issue by Anteru** [embree/embree#176]
Line 226 in `rtcore_common.h` reads:

      context->instID[0] = -1;

This causes a compilation warning about signed/unsigned mismatch using Visual Studio 2017:

> warning C4245: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch

In 2.x, Embree did not have any problems with signed/unsigned conversion in the headers, so this is a regression. My framework is compiled with warnings-as-errors and I need to manually work around this. Looks like this is the only case as well, changing that line to read:

    context->instID[0] = (unsigned int)-1;

fixes the issue. Alternatively, this could be `= RTC_INVALID_GEOMETRY_ID;`.

**Comment by svenwoop** [comment]
Thanks for reporting. We will fix this issue in Embree 3.1.
