### ISSUE TITLE
Embree API stated as C99 conform but uses pass-by-reference

### ISSUE THREAD

**Issue by zzador** [embree/embree#179]
In the api documentation it says "The Embree API is a low-level C99 ray tracing API" but the C99 standard misses the following features that are used extensively in the whole API:

- pass-by-reference (e.g.: unsigned someFunc(int &IntReference) )
- "public", and "private" sections within structs
- templates (e.g.: template< int N >)
- parameter defaults (e.g.: unsigned someFunc(int value = -1) )

For this reason Embree can only be compiled with a full C++ Compiler and the statement about "C99" seems wrong. There are some pure C compilers out there, which support C up to the C11 Standard yet are incapable of compiling Embree because of this.

I'm not really affected by this as I'm currently using Embree from Go but as an old C-Programmer (and a big fan of C) this grinds my gears a bit.

**Comment by svenwoop** [comment]
We also realized this. This issue is fixed with Embree 3.0, whose headers also compile with C99 compilers.
