### ISSUE TITLE
Instanced geometry example: instance geometries commited after release?

### ISSUE THREAD

**Issue by zzador** [embree/embree#180]
In the InstancedGeometry tutorial (embree/tutorials/instanced_geometry) within the device_init function you go:
`
rtcAttachGeometry(g_scene,g_instance0);
...
rtcReleaseGeometry(g_instance0);
...
`

however later in the device_render function you commit the released instanced geometries by:
`
rtcCommitGeometry(g_instance0);
...
`

**Comment by svenwoop** [comment]
When calling rtcAttachGeometry the scene will also hold a reference to the instance, thus this code works. However, it is probably cleaner to release the instance at the end of the application.
