### ISSUE TITLE
Custom BVH structure building?

### ISSUE THREAD

**Issue by elviras9t** [embree/embree#182]
I interesting about creation of custom BVH structure building. 
1. No right/left index, but "prefix" for point to siblings (left or right can be chosen by "`|1`" operator), identifier "branch/leaf", parent prefix and _reserved value in "ivec4" BVH nodes (with siblings - "ivec8"). 
2. Dedicated AABB buffer (4x4 floats), with transposed layout, and optimized for dual, SIMD-like, intersection 
How I can make custom BVH layout?

**Comment by svenwoop** [comment]
Please look at the bvh_builder tutorial for an example of building your own BVH with Embree.
