### ISSUE TITLE
Signed/unsigned mismatch in rtcore_common.h

### ISSUE THREAD

**Issue by DrGr4f1x** [embree/embree#183]
I'm upgrading my project to v3.0.0 (from v2.17.0).  I'm on Win10, VS 2017.  I have warnings as errors enabled, and I'm getting a signed/unsigned mismatch in rtcore_common.h at line 226:
```
RTC_FORCEINLINE void rtcInitIntersectContext(struct RTCIntersectContext* context)
{
  context->flags = RTC_INTERSECT_CONTEXT_FLAG_INCOHERENT;
  context->filter = NULL;
  context->instID[0] = -1;  // <-- Signed/unsigned mismatch, warning 4245
}
```
It would be nice to explicitly cast that -1 to unsigned, so I don't have to push/pop pragmas around my includes.

**Comment by svenwoop** [comment]
Already fixed in devel branch. Will be in next release.
