### ISSUE TITLE
Runtime failure when using instruction set AVX512 

### ISSUE THREAD

**Issue by XBOOS** [embree/embree#184]
We have compiled the Embree successfully and when we run it on the server based on AVX512 instruction set, it failed. But our server with CPU Intel Xeon shows it supports the AVX512F instruction set.  What is the problem and how can we solve it?   Below is the command line and runtime error and our server CPU details.
![2 1](https://user-images.githubusercontent.com/6872538/38465248-045ad960-3b4c-11e8-97cb-9fd72392da03.png)
![1](https://user-images.githubusercontent.com/6872538/38465251-1547b82e-3b4c-11e8-9a73-103fce073aff.png)

`

**Comment by svenwoop** [comment]
Which Windows version are you using?

**Comment by cbenthin** [comment]
And can you try to remove the "-isa avx512knl" command line option?

**Comment by XBOOS** [comment]
we are using Windows server 2012

**Comment by svenwoop** [comment]
Windows server 2012 is likely not supporting AVX512. Could you please print the variables xmm_enabled, ymm_enabled, zmm_enabled in the getCPUFeatures function in embree/common/sysinfo.cpp. I assume zmm_enabled is false.

**Comment by XBOOS** [comment]
Thank you! We have found out that Windows server 2012 is not supporting and matrial shows Windows Server 2016 may support  AVX512. We will try 2016 then.
