### ISSUE TITLE
inexistent INTERSECT property and wrong docs (switching from 2.17 o 3.10)

### ISSUE THREAD

**Issue by u56237z** [embree/embree#189]
We're facing an issue transitioning from 2.17 to the latest 3.1.0.. the "upgrading from 2.x to 3.x" script modified the following line(s):

rtcDeviceParameteri(device,RTC_CONFIG_INTERSECT4)

with

rtcGetDeviceProperty(device,RTC_DEVICE_PROPERTY_INTERSECT4_SUPPORTED)

but it seems like the RTC_DEVICE_PROPERTY_INTESECT4_SUPPORTED enum does not exist.

Looking into the rtcIntersect4 and rtcOccluded4 API docs, I find: "use these functions only after checking whether they are available by using an **rtcGetDeviceParameter** query". unfortunately, it seems like there is no such function in the API.

Would I be safe to assume that there is a typo in the docs, and that the correct way of checking wether 4/8/16 intersect/occluded functions are available would be by calling rtcGetDevicePorperty, with values of RTC_DEVICE_PROPERTY_NATIVE_RAY4_SUPPORTED (and also /8/16)?

**Comment by svenwoop** [comment]
Yes, this is a bug in the documentation. The rtcIntersect4/8/16 functions are now always available. However, they may change the ray packet size and reorder the rays in the packet in general. However, if you enabled ray packet support in cmake (enabled by default), enabled the ISA corresponding to the packet size (e.g. AVX for 8-wide packets) and the machine you are running on supports that ISA, then packets are keps as is. Whether Embree changes packets can be queries using the RTC_DEVICE_PROPETY_NATIVE_RA4/8/16_SUPPORTED queries.

**Comment by u56237z** [comment]
Oh I see, Thanks
