### ISSUE TITLE
std::bad_alloc in embree worker thread on win32 with low memory

### ISSUE THREAD

**Issue by ov** [embree/embree#19]
First of all, thanks for the amazing library guys!

We're having an issue with embree 2.3.3 on 32-bit windows configuration in the low-memory conditions. We basically allocate some large buffers, load large textures and there's no much memory left for embree's internal structures, so when we call `rtcCommit()` we get the `std::bad_alloc` exception somewhere inside the embree worker thread.

![image](https://cloud.githubusercontent.com/assets/151412/5353162/8f6d7504-7fd8-11e4-863c-abc4ba6ad22d.png)

Unfortunately, there is no way for us to catch it somehow to handle and report to the user. Application simply crashes. `rtcSetErrorFunction()` doesn't help, as the callback doesn't get called at all.

It would be really nice if you somehow handled this inside the `rtcCommit()` call and simply return an error code.

**Comment by svenwoop** [comment]
This issue is solved in Embree v2.5.0. Some exception thrown during build time will now properly terminate the rtcCommit function with some error code.

**Comment by ov** [comment]
great, thank you!
