### ISSUE TITLE
Out of bounds read in getWorld2Local(float) when numTimeSegments is 1

### ISSUE THREAD

**Issue by ezillinger** [embree/embree#191]
While running embree 3.1 under Dr. Memory I'm seeing `Error #1: UNADDRESSABLE ACCESS beyond heap bounds` from `embree3.dll!embree::Instance::getTransform`. 

The error occurs when you set the number of time steps to 1 and then call rtcGetGeometryTransform. It seems that getWorld2Local(float) always assumes there's more than 1 time step:

```            
 __forceinline AffineSpace3fa getWorld2Local(float t) const 
    {
      float ftime;
      const unsigned int itime = getTimeSegment(t, fnumTimeSegments, ftime);
      return rcp(lerp(local2world[itime+0],local2world[itime+1],ftime));
    }
```

The result is still correct (assuming t=0.0f), but it'd still be nice to fix. I'm not sure if the correct fix is allocating one more slot in this case, or if something should be calling getWorld2Local(void) instead.

**Comment by svenwoop** [comment]
We will fix this in Embree 3.2 which will get released soon.
