### ISSUE TITLE
Implement "Robust Iterative Find-Next-Hit Ray Traversal"

### ISSUE THREAD

**Issue by skwerner** [embree/embree#192]
Not sure if this is on the Embree roadmap yet, but I'd be thrilled if a future version of Embree could include support for the next-hit traversal algorithm presented in this publication:

http://www.sci.utah.edu/~wald/Publications/2018/nexthit-pgv18.pdf

**Comment by kabukunz** [comment]
http://www.sci.utah.edu/~wald/Publications/2018/nexthit/nexthit-pgv18.pdf

Hello, just to amend the link

**Comment by cbenthin** [comment]
As we have now a tutorial on getting the next hit, I'll close this issue.
