### ISSUE TITLE
crown.ecs to ply file

### ISSUE THREAD

**Issue by Woking-34** [embree/embree#198]
Hi,

This issue is not directly related to embree.
I would like to export the crown model to a ply file. I am using the viewer tutorial project (SceneLoadingTutorialApplication). Unfortunately, in my final export some mesh instances seem to have flipped normals.

I have inserted simple vertex and index collection and dumping code to the void TutorialScene::add(Ref<SceneGraph::GroupNode> group) method.

Can you guys help me figure it out? Thanks!

![crown_ply_normals](https://user-images.githubusercontent.com/17589258/40806069-acd3ed40-6520-11e8-9d4e-1f75e5a12502.jpg)

**Comment by cbenthin** [comment]
It might be that the original model already contained the flipped normals (not sure though). The tutorials (if necessary) flip the normals during rendering.

**Comment by cbenthin** [comment]
You could probably use Blender or a similar tool to load the model and correct the normals.
