### ISSUE TITLE
Could not build with Intel C++ Compiler 18.0

### ISSUE THREAD

**Issue by PooyaEimandar** [embree/embree#202]
I couldn't build embree with Intel C++ Compiler 18.0 and VS2017 x64. I need to build it with AVX512.

**Comment by cbenthin** [comment]
Hi,
which Embree version did you use and could you post the compiler errors?

Thanks.

**Comment by PooyaEimandar** [comment]
Hi

embree version: 3.2
CPU: Intel i7 7700
OS: Windows 10 64-bit build 17134
[build.txt](https://github.com/embree/embree/files/2136588/build.txt)

Bests

**Comment by cbenthin** [comment]
It compiles fine with VS 2017 15.7.4 and the Intel C++ Compiler 18.0.3 in Release mode on my end. Note that the Debug mode might cause problems (compiler "forgets" to inline intrinsics), better use the RelWithDebInfo mode for debugging, or the Release mode. Which version of VS are you using exactly, and did you configure the Intel compiler over the toolset option in the cmake dialog?

**Comment by PooyaEimandar** [comment]
@cbenthin 
Yes, I did.

`Set(CMAKE_GENERATOR_TOOLSET "Intel C++ Compiler 18.0" CACHE STRING "Platform Toolset" FORCE)`

**Comment by cbenthin** [comment]
Any updates on this?

**Comment by PooyaEimandar** [comment]
Problem solved.
Thanks
