### ISSUE TITLE
Embree 3.3 alpha changelog?

### ISSUE THREAD

**Issue by oscarbg** [embree/embree#204]
Hi,
I notice 3.3 alpha's have begun appearing but I can't see any changelog anywhere..
Assume this is a Siggraph release, but can post some changelog in the meanwhile..
thanks..

**Comment by cbenthin** [comment]
There are some new advanced motion blur features in this pre-release, not sure we can get it out of alpha state before Siggraph though. We'll provide updates as soon as possible.

**Comment by oscarbg** [comment]
thanks for info!
