### ISSUE TITLE
Wrong libraries in cmake file for static builds

### ISSUE THREAD

**Issue by skwerner** [embree/embree#209]
When building with with `EMBREE_STATIC_LIB=ON`, the embree-config.cmake file contains references to the wrong libraries. It sets `EMBREE_LIBRARIES=libembree3.so.3.20`, pointing to a non-existent dynamic library where it should be set to the static .a libraries that are actually built.

**Comment by cbenthin** [comment]
I could not reproduce this issue with the latest 3.5.2 version when setup for static lib mode. If the issue still persists with the latest version please re-open.
