### ISSUE TITLE
instanced geometry doesn't support displacement map?

### ISSUE THREAD

**Issue by XBOOS** [embree/embree#211]
i am using embree-2.17.1 to support displacement map, but it seems that the **instanced geometry** doesn't support it. 
 The details are:  the arguments in **displacementFunction** only include **geomID** and **primID**, but not **insID**. so that I can't map back to the instanced geometry which contains the displacement texture.
 
Do I have any misunderstanding here ? Could anyone help to figure it out?

**Comment by svenwoop** [comment]
You have also access to the geometry user pointer (ptr argument). Just set the geometry user pointer to the data structures you need to displace the surface and access this data inside the callback.
