### ISSUE TITLE
embree3 v3.2.1 x64 for Windods have libmmd.dll dependancy

### ISSUE THREAD

**Issue by iOrange** [embree/embree#213]
Hi!

Seems like Embree3 v3.2.1 x64 for Windows (at least the one from the zip archive) comes with **libmmd.dll** dependancy.

The documentations doesn't mention that, and it's not clear if we should obtain **libmmd.dll** from somewhere else.

Sergii

**Comment by svenwoop** [comment]
We have a fix for this in place and will make it available with Embree 3.2.2 which will get released in the next days.
