### ISSUE TITLE
TBB-related error for software compiled with Embree 3.2.2

### ISSUE THREAD

**Issue by joerosenthal** [embree/embree#215]
Since updating to Embree 3.2.2, my software has the following issue with embree3.dll:

<img width="622" alt="screen shot 2018-10-10 at 7 31 04 pm" src="https://user-images.githubusercontent.com/5945165/46773449-0dfa5a00-ccc3-11e8-9b96-64063c2dace4.png">

**Comment by svenwoop** [comment]
From which version did you upgrade to 3.2.2?

**Comment by joerosenthal** [comment]
3.2.1 was the last version I installed prior to upgrading. I’ve uninstalled Embree entirely and installed 3.2.2 again, but the error persists.

**Comment by svenwoop** [comment]
Does this problem also show up when you just start the tutorials?

**Comment by joerosenthal** [comment]
Those seem to be working.

**Comment by joerosenthal** [comment]
I should mention that I've installed Embree through the MSI. Trying to
compile it now, and it looks like the EMBREE TBB ROOT is not found.

**Comment by cbenthin** [comment]
This seems to be a TBB installation issue. Just follow svenwoop's suggestion to fix it. Closing this issue for now please re-open if it still persists.
