### ISSUE TITLE
Issue about Beam Tracing with Embree

### ISSUE THREAD

**Issue by Hao-HUST** [embree/embree#217]
Hi,

Thanks for your great work. 

I tested your single ray tracing API, it is super faster than other ray tracing framework. I have two question about the Embree:

1. The advanced features on Embree are very clear, but if I need to know the details, for example, why the single ray interaction on Embree is so fast, is there any materials or document available to describe the algorithm with more details?

2. The Embree provide the single/multiple ray interaction API, but if I need to implement the interaction between beam and scene (the basic element is replaced from the ray to the beam), how should I do? (The beam is defined by three edge rays that intersect in the focus of the beam, as the figure below shows)

I am appreciated for your help. Thanks again.

![beam](https://user-images.githubusercontent.com/10823967/47414538-c9cb8700-d7a3-11e8-9284-80f64eff3110.PNG)

**Comment by svenwoop** [comment]
There is the paper "Embree: A Kernel framework for efficient CPU Ray Tracing" which describes some aspects of the system. The performance comes from a high quality BVH build using SAH, from leveraging SIMD trough a 4-wide (or 8-wide) BVH and 4 triangles per leaf, and from low level optimizations in the traversal kernel.

There is no way to directly trace a beam through the Embree API. However, if you use the stream API (rtcIntersectNM function) and set the intersection context flag to RTC_INTERSECT_CONTEXT_COHERENT then we internally build a frustum from the rays and trace this.
