### ISSUE TITLE
Embree build complexity

### ISSUE THREAD

**Issue by xelatihy** [embree/embree#221]
It is  very easy to integrate Embree in a code base without installing it due to the complexity of both building it and linking it statically.

It would be great to have a simple way to build Embree from source and generate _one_ static library. This would avoid significant issues in integration.

**Comment by syoyo** [comment]
> It is very easy

very difficult?

FYI here is minimal static Embree build configuration for CMake. It won't give absolute performance, but integration should work well with minimal issues.

```
  -DCMAKE_INSTALL_PREFIX=$HOME/local/embree3 \
  -DCMAKE_C_COMPILER=xyz \
  -DCMAKE_CXX_COMPILER=xyz++ \
  -DEMBREE_STATIC_LIB=On \
  -DEMBREE_ISPC_SUPPORT=Off \
  -DEMBREE_TASKING_SYSTEM=Internal \
  -DEMBREE_TUTORIALS=Off \
  -DEMBREE_MAX_ISA=SSE2 \
  -Bbuild -H.
```

**Comment by cbenthin** [comment]
Thanks syoyo for the minimal build configuration. I'm not sure whether there's a real issue with the Embree build configuration. If there is please re-open the issue.
