### ISSUE TITLE
Return back the hit node

### ISSUE THREAD

**Issue by Hao-HUST** [embree/embree#223]
Hi.

Is that possible to return back the hit node, when we make coherent package ray-triangle interaction ( the coherent ray package represent by frustum)? If it is not available for current API, it there a good way to develop custom API functions under the embree framework?

Thanks!

**Comment by svenwoop** [comment]
There is no way to return the hit node, and this would also not help you much as Embree uses different leaf layouts in different modes. Could you please describe what you want to achieve?

**Comment by Hao-HUST** [comment]
Ok, thanks for replying.

The coherent ray package is represented as a frustum on Embree. If my understanding is correct,  such frustum is traced on the BVH until the leaf node is hit by such frustum. 

For Embree, the next step is to make ray-triangle interaction operation, according to the triangles contained by the hit leaf node.
For me, I need to subdivide the frustum(beam-triangle interaction), according to the triangles contained by the hit leaf node.

**Comment by svenwoop** [comment]
The triangle could be accessed by registering an intersection filter function. That one could be used to gather all the triangles that are hit by the rays. However, the beam might hit more triangles. Best hack Embree and extent it with returning the hit leaf.
