### ISSUE TITLE
char -> signed char or use int8_t for better portability

### ISSUE THREAD

**Issue by syoyo** [embree/embree#225]
`char` is used for storing quantized bounds into signed 8bit at hair(curve) intersection(e.g. https://github.com/embree/embree/blob/master/kernels/geometry/curveNi.h#L175) , but `char` is not always `signed char` on some architecture. For example, `unsigned char` is default on ARM architecture: http://www.keil.com/support/man/docs/armcc/armcc_chr1359125009502.htm)   

This results in broken hair intersection on ARM architecture.

https://github.com/lighttransport/embree-aarch64/issues/3

Possible solution is either use `signed char`(for backward compatibility) or `int8_t`(for better portability if we assume C99 or C++11 compiler).

I can send PR either `signed char` or `int8_t` version. Which is preferred ? > @svenwoop

**Comment by ingowald** [comment]
I _think_ "int8_t" is not specific to C99 or C++11; it's generally a type defined in stdint.h, and should thus be available to any compiler and standard. So in short, int8_t/uint8_t should be the way better type... (and in case there _was_ an arch that didn't offer it, you could always typedef it to unsigned char :-) ).

**Comment by syoyo** [comment]
> int8_t/uint8_t should be the way better type... 

I see. I found `stdint.h` is included in `common/sys/platform.h`, thus should be OK to use `int8_t`. I will try to create PR with `int8_t`!

**Comment by svenwoop** [comment]
Just fixed this internally. Fix will come into next release.

**Comment by syoyo** [comment]
Awesome! Thanks! > Just fixed this internally. Fix will come into next release.
