### ISSUE TITLE
Building Embree on Ubuntu 18.04

### ISSUE THREAD

**Issue by jdpipe** [embree/embree#226]
Building Embree on Ubuntu 18.04 should be pretty straightforward...

```
cd ~/src
wget http://sourceforge.net/projects/ispcmirror/files/v1.9.2/ispc-v1.9.2-linux.tar.gz
tar zxvf ispc-v1.9.2-linux.tar.gz
cd ispc-v1.9.2-linux
./ispc  --version
```
 followed by

```
cd ~/src
sudo apt-get install libtbb-dev libglfw3-dev cmake
git clone https://github.com/embree/embree.git
cd embree
git checkout v3.3.0
cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DEMBREE_ISPC_EXECUTABLE=$HOME/src/ispc-v1.9.2-linux/ispc -DCMAKE_INSTALL_PREFIX=/usr/local .
make -j4
sudo make install
```
However, following these instructions, I get many compiler errors from Clang/GCC as follows:

```
john@novo:~/src/embree$ make
[  1%] Building CXX object common/sys/CMakeFiles/sys.dir/sysinfo.cpp.o
In file included from /home/john/src/embree/common/sys/sysinfo.cpp:17:
In file included from ./sysinfo.h:28:
In file included from ./../math/../sys/platform.h:31:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/cstring:42:
In file included from ./string.h:20:
In file included from ./../math/vec2.h:19:
In file included from ./../math/math.h:20:
./../math/../sys/intrinsics.h:219:3: error: unknown type name '__forceinline'
  __forceinline void __cpuid(int out[4], int op) {
  ^
./../math/../sys/intrinsics.h:219:17: error: expected unqualified-id
  __forceinline void __cpuid(int out[4], int op) {
                ^
./../math/../sys/intrinsics.h:223:3: error: unknown type name '__forceinline'
  __forceinline void __cpuid_count(int out[4], int op1, int op2) {
  ^
./../math/../sys/intrinsics.h:223:17: error: expected unqualified-id
  __forceinline void __cpuid_count(int out[4], int op1, int op2) {
                ^
./../math/../sys/intrinsics.h:229:3: error: unknown type name '__forceinline'
  __forceinline uint64_t read_tsc()  {
  ^
./../math/../sys/intrinsics.h:229:25: error: expected ';' after top level declarator
  __forceinline uint64_t read_tsc()  {
                        ^
In file included from /home/john/src/embree/common/sys/sysinfo.cpp:17:
```

I also get the same errors if I attempt to use Clang 6.0.

If I switch to GCC, I get heaps and heaps of errors like this:

```
./../math/vec3fa.h:308:3: error: ‘__forceinline’ does not name a type; did you mean ‘__finite’?
   __forceinline float  rcp_length ( const Vec3fa& a )                { return rsqrt(dot(a,a)); }
   ^~~~~~~~~~~~~
   __finite
```

What's happening here? Can anyone provide a simple (tested) process that builds Embree successfull on Ubuntu 18.04?

**Comment by syoyo** [comment]
Even though I haven't experienced to compile Embree3 on Ubuntu 18.04,

> In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0/../../../../include/c++/7.3.0/cstring:42:
> In file included from ./string.h:20:

According to the message, `cstring` system header is reading Embree's `string.h` for some reason.
(probably a reason is you are doing in-source build)

> cmake -DCMAKE_C_COMPILER=clang-3.9 -DCMAKE_CXX_COMPILER=clang++-3.9 -DEMBREE_ISPC_EXECUTABLE=$HOME/src/ispc-v1.9.2-linux/ispc -DCMAKE_INSTALL_PREFIX=/usr/local .

In-source build is problematic. It is highly recommended to create **build** directory for cmake build, as described in
 https://github.com/embree/embree#linux-and-macos

**Comment by cbenthin** [comment]
Just tried to compile Embree 3.5.2 on Ubuntu 18.04.2 LTS + GCC / Clang and using a separate build directory. It works without problems. Will close the issue for now, please re-open if it still persists.
