### ISSUE TITLE
Documentation build fails due to obsolete pandoc parameter

### ISSUE THREAD

**Issue by mfvescovi** [embree/embree#228]
Hi!

While test building embree 3.4.0 to get it in Debian, I faced the following issue:
> pandoc --smart --email-obfuscation=none -f markdown tmp/links_web.md tmp/images_local_png.md tmp/overview.md src/resources.html tmp/support.md tmp/changelog.md tmp/acknowledgement.md --template tmp/webtemplate -V select_index -o www/index.html
--smart/-S has been removed.  Use +smart or -smart extension instead.
For example: pandoc -f markdown+smart -t markdown-smart.
Try pandoc --help for more information.
make[2]: *** [Makefile:75: www/index.html] Error 2
rm tmp/images_local.md
make[2]: Leaving directory '/<<BUILDDIR>>/embree-3.4.0+dfsg/doc'
make[1]: *** [debian/rules:24: override_dh_auto_build-indep] Error 2
make[1]: Leaving directory '/<<BUILDDIR>>/embree-3.4.0+dfsg'
make: *** [debian/rules:8: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

Since pandoc v2.0 the "--smart" option has been removed and embree code still uses it when documentation is built from source, making the process fail.
So, https://github.com/embree/embree/blob/master/doc/Makefile#L68 should be fixed.

Thanks in advance for the efforts spent on this.

**Comment by mfvescovi** [comment]
Hi @johguenther !
Probably you already noticed, but even https://github.com/embree/embree/blob/master/doc/Makefile#L70 has to be updated the same way.

**Comment by svenwoop** [comment]
Just fixed this. The fix will go into Embree v3.5.0.

**Comment by johguenther** [comment]
"smart" is still supported, but now needs to be specified as format modifier (i.e. as part of `-f` and `-t`). I'll look into this in the context of a larger documentation infrastructure update.

**Comment by mfvescovi** [comment]
@johguenther wrote:

> "smart" is still supported, but now needs to be specified as format modifier (i.e. as part of `-f` and `-t`). I'll look into this in the context of a larger documentation infrastructure update.

Yes, at https://paste.debian.net/1065540 I've prepared a draft diff for the fix. Probably it's not complete. Still testing.

**Comment by johguenther** [comment]
You can also have a look at https://github.com/ospray/ospray/blob/master/doc/Makefile#L151, where this is already implemented. "`smart`" applies only to `markdown` (and `latex`), not to `html` formats, and one has to pay attention whether to enable or disable "`smart`":
> If you are writing Markdown, then the smart extension has the reverse effect: what would have been curly quotes comes out straight.

**Comment by mfvescovi** [comment]
@johguenther wrote: 
> You can also have a look at https://github.com/ospray/ospray/blob/master/doc/Makefile#L151, where this is already implemented. "`smart`" applies only to `markdown` (and `latex`), not to `html` formats, and one has to pay attention whether to enable or disable "`smart`":
> 
> > If you are writing Markdown, then the smart extension has the reverse effect: what would have been curly quotes comes out straight.

That way, this is what I get (failing snippet only): https://paste.debian.net/1065636

**Comment by johguenther** [comment]
Yes, our custom filters are another issue I need to fix when going to a newer pandoc version.

**Comment by mfvescovi** [comment]
@johguenther wrote: 
> Yes, our custom filters are another issue I need to fix when going to a newer pandoc version.

It would be awesome if you could share that fix so I can go on packaging embree for Debian. TIA.

**Comment by johguenther** [comment]
Are you already using pandoc v2.6 (in case there are some incompatibilities to earlier versions)?

Sure I will share the fixes, let's see whether I get it done this week.

**Comment by mfvescovi** [comment]
@johguenther wrote: 
> Are you already using pandoc v2.6 (in case there are some incompatibilities to earlier versions)?
> 
> Sure I will share the fixes, let's see whether I get it done this week.

At the moment, Debian is still on v2.2.1 (see 'unstable' version at https://tracker.debian.org/pkg/pandoc)
