### ISSUE TITLE
missing debug information in 2.4

### ISSUE THREAD

**Issue by ov** [embree/embree#23]
We use Google Breakpad to track application crashes. It has a `dump_syms` utillity that processes binaries and fetches all the symbols to a special file, kind of cross-platform PDB-file. It worked just fine until version 2.4 where you have changed something or simply removed the symbols at all.

I see in the logs that you split the built into "release" and "release with symbols". That's fine, but is there a way we can get the second one, please? So far that symbol-less build makes difficult to report bugs like #22, as we have no symbols at all.

Any ideas?

PS: Thanks for the perfect library!

**Comment by svenwoop** [comment]
Enabling the debug symbols in the Release mode is no option under Linux, as the generated binary gets over 50MB in size.

I just checked, and we also did not add debug symbols to neither the release v2.3.3 nor 2.3.2. However, names of all functions are in the binary.

**Comment by ov** [comment]
Could you let me know what has been changed from the building perspective between the latest 2.3 and 2.4? As Google Breakpad symbol dump utility easily handles the old binary, but finds no symbols in the new one.

I see the commit that splits the release and release with symbols version, but as you said there were no symbols in 2.3, I wonder what has happened?

**Comment by svenwoop** [comment]
When using dump_syms on Embree v2.3.3 under Linux I get the following. But these are also only the API symbols no internal symbols.

MODULE Linux x86_64 AC0A286F5A497FB09E7E0B4C6FB842740 libembree.so.2
PUBLIC 1f3e8 0 _init
PUBLIC 220b0 0 ISPCAlloc
PUBLIC 22160 0 ISPCLaunch
PUBLIC 221f0 0 ISPCSync
PUBLIC 23380 0 setSubdivisionLevel
PUBLIC 23390 0 rtcDebug
PUBLIC 233b0 0 rtcNewScene
PUBLIC 234c0 0 rtcCommit
PUBLIC 23860 0 rtcCommitThread
PUBLIC 23f10 0 rtcIntersect
PUBLIC 23f20 0 rtcIntersect4
PUBLIC 23f30 0 rtcIntersect8
PUBLIC 23f40 0 rtcIntersect16
PUBLIC 24210 0 rtcOccluded
PUBLIC 24220 0 rtcOccluded4
PUBLIC 24230 0 rtcOccluded8
PUBLIC 24240 0 rtcOccluded16
PUBLIC 24510 0 rtcDeleteScene
PUBLIC 24880 0 rtcNewInstance
PUBLIC 24ec0 0 rtcSetTransform
PUBLIC 25d20 0 rtcNewUserGeometry
PUBLIC 260b0 0 rtcNewTriangleMesh
PUBLIC 264c0 0 rtcNewHairGeometry
PUBLIC 268d0 0 rtcSetMask
PUBLIC 26fe0 0 rtcMapBuffer
PUBLIC 276d0 0 rtcUnmapBuffer
PUBLIC 27de0 0 rtcSetBuffer
PUBLIC 28590 0 rtcEnable
PUBLIC 28c50 0 rtcUpdate
PUBLIC 29310 0 rtcDisable
PUBLIC 299d0 0 rtcDeleteGeometry
PUBLIC 2a090 0 rtcSetUserData
PUBLIC 2a7a0 0 rtcSetBoundsFunction
PUBLIC 2aeb0 0 rtcSetIntersectFunction
PUBLIC 2b5c0 0 rtcSetIntersectFunction4
PUBLIC 2bcd0 0 rtcSetIntersectFunction8
PUBLIC 2c3e0 0 rtcSetIntersectFunction16
PUBLIC 2caf0 0 rtcSetOccludedFunction
PUBLIC 2d200 0 rtcSetOccludedFunction4
PUBLIC 2d910 0 rtcSetOccludedFunction8
PUBLIC 2e020 0 rtcSetOccludedFunction16
PUBLIC 2e730 0 rtcSetIntersectionFilterFunction
PUBLIC 2ee40 0 rtcSetIntersectionFilterFunction4
PUBLIC 2f550 0 rtcSetIntersectionFilterFunction8
PUBLIC 2fc60 0 rtcSetIntersectionFilterFunction16
PUBLIC 30370 0 rtcSetOcclusionFilterFunction
PUBLIC 30a80 0 rtcSetOcclusionFilterFunction4
PUBLIC 31190 0 rtcSetOcclusionFilterFunction8
PUBLIC 318a0 0 rtcSetOcclusionFilterFunction16
PUBLIC 31fb0 0 rtcNewSubdivisionMesh
PUBLIC 33640 0 rtcSetErrorFunction
PUBLIC 33650 0 rtcGetError
PUBLIC 33820 0 rtcExit
PUBLIC 339c0 0 rtcInit
PUBLIC 3abb0 0 _ZdlPvS_
PUBLIC 8e800 0 _ZNSs12_S_constructIPcEES0_T_S1_RKSaIcESt20forward_iterator_tag
PUBLIC 128120 0 rtcNewScene___unenum[RTCSceneFlags]unenum[RTCAlgorithmFlags]sse2
PUBLIC 128130 0 rtcCommit___un_3C_s[un__RTCScene]_3E_sse2
PUBLIC 128140 0 rtcCommitThread___un_3C_s[un__RTCScene]_3E_unuunusse2
PUBLIC 128150 0 rtcIntersect1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]sse2
PUBLIC 128160 0 rtcIntersect___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]sse2
PUBLIC 1281b0 0 rtcOccluded1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]sse2
PUBLIC 1281c0 0 rtcOccluded___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]sse2
PUBLIC 128210 0 rtcDeleteScene___un_3C_s[un__RTCScene]_3E_sse2
PUBLIC 128220 0 rtcNewInstance___un_3C_s[un__RTCScene]_3E_un_3C_s[un__RTCScene]_3E_sse2
PUBLIC 128230 0 rtcSetTransform___un_3C_s[un__RTCScene]_3E_unuunenum[RTCMatrixType]un_3C_Cunf_3E_sse2
PUBLIC 128240 0 rtcNewTriangleMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunusse2
PUBLIC 128250 0 rtcNewHairGeometry___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunusse2
PUBLIC 128260 0 rtcSetMask___un_3C_s[un__RTCScene]_3E_unuunisse2
PUBLIC 128270 0 rtcMapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]sse2
PUBLIC 128280 0 rtcUnmapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]sse2
PUBLIC 128290 0 rtcSetBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]un_3C_unv_3E_unuunusse2
PUBLIC 1282a0 0 rtcEnable___un_3C_s[un__RTCScene]_3E_unusse2
PUBLIC 1282b0 0 rtcUpdate___un_3C_s[un__RTCScene]_3E_unusse2
PUBLIC 1282c0 0 rtcDisable___un_3C_s[un__RTCScene]_3E_unusse2
PUBLIC 1282d0 0 rtcSetIntersectionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_sse2
PUBLIC 1282e0 0 rtcSetIntersectionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_sse2
PUBLIC 1282f0 0 rtcSetOcclusionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_sse2
PUBLIC 128300 0 rtcSetOcclusionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_sse2
PUBLIC 128310 0 rtcDeleteGeometry___un_3C_s[un__RTCScene]_3E_unusse2
PUBLIC 128320 0 rtcNewSubdivisionMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuunusse2
PUBLIC 128330 0 rtcNewUserGeometry___un_3C_s[un__RTCScene]_3E_unusse2
PUBLIC 128340 0 rtcSetUserData___un_3C_s[un__RTCScene]_3E_unuun_3C_unv_3E_sse2
PUBLIC 128350 0 rtcSetBoundsFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_unuREFs[unRTCBounds]_3E_sse2
PUBLIC 128360 0 rtcSetIntersectFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_sse2
PUBLIC 128370 0 rtcSetIntersectFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_sse2
PUBLIC 128380 0 rtcSetOccludedFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_sse2
PUBLIC 128390 0 rtcSetOccludedFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_sse2
PUBLIC 1283a0 0 rtcInit___un_3C_Cunt_3E_sse2
PUBLIC 1283b0 0 rtcExit___sse2
PUBLIC 1283c0 0 rtcGetError___sse2
PUBLIC 1283d0 0 rtcSetErrorFunction___un_3C____Cunenum[RTCError]un_3C_Cunt_3E__3E_sse2
PUBLIC 1283e0 0 rtcDebug___sse2
PUBLIC 1283f0 0 rtcNewScene___unenum[RTCSceneFlags]unenum[RTCAlgorithmFlags]sse4
PUBLIC 128400 0 rtcCommit___un_3C_s[un__RTCScene]_3E_sse4
PUBLIC 128410 0 rtcCommitThread___un_3C_s[un__RTCScene]_3E_unuunusse4
PUBLIC 128420 0 rtcIntersect1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]sse4
PUBLIC 128430 0 rtcIntersect___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]sse4
PUBLIC 128480 0 rtcOccluded1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]sse4
PUBLIC 128490 0 rtcOccluded___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]sse4
PUBLIC 1284e0 0 rtcDeleteScene___un_3C_s[un__RTCScene]_3E_sse4
PUBLIC 1284f0 0 rtcNewInstance___un_3C_s[un__RTCScene]_3E_un_3C_s[un__RTCScene]_3E_sse4
PUBLIC 128500 0 rtcSetTransform___un_3C_s[un__RTCScene]_3E_unuunenum[RTCMatrixType]un_3C_Cunf_3E_sse4
PUBLIC 128510 0 rtcNewTriangleMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunusse4
PUBLIC 128520 0 rtcNewHairGeometry___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunusse4
PUBLIC 128530 0 rtcSetMask___un_3C_s[un__RTCScene]_3E_unuunisse4
PUBLIC 128540 0 rtcMapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]sse4
PUBLIC 128550 0 rtcUnmapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]sse4
PUBLIC 128560 0 rtcSetBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]un_3C_unv_3E_unuunusse4
PUBLIC 128570 0 rtcEnable___un_3C_s[un__RTCScene]_3E_unusse4
PUBLIC 128580 0 rtcUpdate___un_3C_s[un__RTCScene]_3E_unusse4
PUBLIC 128590 0 rtcDisable___un_3C_s[un__RTCScene]_3E_unusse4
PUBLIC 1285a0 0 rtcSetIntersectionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_sse4
PUBLIC 1285b0 0 rtcSetIntersectionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_sse4
PUBLIC 1285c0 0 rtcSetOcclusionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_sse4
PUBLIC 1285d0 0 rtcSetOcclusionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_sse4
PUBLIC 1285e0 0 rtcDeleteGeometry___un_3C_s[un__RTCScene]_3E_unusse4
PUBLIC 1285f0 0 rtcNewSubdivisionMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuunusse4
PUBLIC 128600 0 rtcNewUserGeometry___un_3C_s[un__RTCScene]_3E_unusse4
PUBLIC 128610 0 rtcSetUserData___un_3C_s[un__RTCScene]_3E_unuun_3C_unv_3E_sse4
PUBLIC 128620 0 rtcSetBoundsFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_unuREFs[unRTCBounds]_3E_sse4
PUBLIC 128630 0 rtcSetIntersectFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_sse4
PUBLIC 128640 0 rtcSetIntersectFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_sse4
PUBLIC 128650 0 rtcSetOccludedFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_sse4
PUBLIC 128660 0 rtcSetOccludedFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_sse4
PUBLIC 128670 0 rtcInit___un_3C_Cunt_3E_sse4
PUBLIC 128680 0 rtcExit___sse4
PUBLIC 128690 0 rtcGetError___sse4
PUBLIC 1286a0 0 rtcSetErrorFunction___un_3C____Cunenum[RTCError]un_3C_Cunt_3E__3E_sse4
PUBLIC 1286b0 0 rtcDebug___sse4
PUBLIC 1286c0 0 rtcNewScene___unenum[RTCSceneFlags]unenum[RTCAlgorithmFlags]avx
PUBLIC 1286f0 0 rtcCommit___un_3C_s[un__RTCScene]_3E_avx
PUBLIC 128700 0 rtcCommitThread___un_3C_s[un__RTCScene]_3E_unuunuavx
PUBLIC 128710 0 rtcIntersect1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]avx
PUBLIC 128720 0 rtcIntersect___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]avx
PUBLIC 1287b0 0 rtcOccluded1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]avx
PUBLIC 1287c0 0 rtcOccluded___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]avx
PUBLIC 128850 0 rtcDeleteScene___un_3C_s[un__RTCScene]_3E_avx
PUBLIC 128860 0 rtcNewInstance___un_3C_s[un__RTCScene]_3E_un_3C_s[un__RTCScene]_3E_avx
PUBLIC 128870 0 rtcSetTransform___un_3C_s[un__RTCScene]_3E_unuunenum[RTCMatrixType]un_3C_Cunf_3E_avx
PUBLIC 128880 0 rtcNewTriangleMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuavx
PUBLIC 128890 0 rtcNewHairGeometry___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuavx
PUBLIC 1288a0 0 rtcSetMask___un_3C_s[un__RTCScene]_3E_unuuniavx
PUBLIC 1288b0 0 rtcMapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]avx
PUBLIC 1288c0 0 rtcUnmapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]avx
PUBLIC 1288d0 0 rtcSetBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]un_3C_unv_3E_unuunuavx
PUBLIC 1288e0 0 rtcEnable___un_3C_s[un__RTCScene]_3E_unuavx
PUBLIC 1288f0 0 rtcUpdate___un_3C_s[un__RTCScene]_3E_unuavx
PUBLIC 128900 0 rtcDisable___un_3C_s[un__RTCScene]_3E_unuavx
PUBLIC 128910 0 rtcSetIntersectionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_avx
PUBLIC 128920 0 rtcSetIntersectionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_avx
PUBLIC 128930 0 rtcSetOcclusionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_avx
PUBLIC 128940 0 rtcSetOcclusionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_avx
PUBLIC 128950 0 rtcDeleteGeometry___un_3C_s[un__RTCScene]_3E_unuavx
PUBLIC 128960 0 rtcNewSubdivisionMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuunuavx
PUBLIC 128970 0 rtcNewUserGeometry___un_3C_s[un__RTCScene]_3E_unuavx
PUBLIC 128980 0 rtcSetUserData___un_3C_s[un__RTCScene]_3E_unuun_3C_unv_3E_avx
PUBLIC 128990 0 rtcSetBoundsFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_unuREFs[unRTCBounds]_3E_avx
PUBLIC 1289a0 0 rtcSetIntersectFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_avx
PUBLIC 1289b0 0 rtcSetIntersectFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_avx
PUBLIC 1289c0 0 rtcSetOccludedFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_avx
PUBLIC 1289d0 0 rtcSetOccludedFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_avx
PUBLIC 1289e0 0 rtcInit___un_3C_Cunt_3E_avx
PUBLIC 1289f0 0 rtcExit___avx
PUBLIC 128a00 0 rtcGetError___avx
PUBLIC 128a10 0 rtcSetErrorFunction___un_3C____Cunenum[RTCError]un_3C_Cunt_3E__3E_avx
PUBLIC 128a20 0 rtcDebug___avx
PUBLIC 128a30 0 rtcNewScene___unenum[RTCSceneFlags]unenum[RTCAlgorithmFlags]avx2
PUBLIC 128a60 0 rtcCommit___un_3C_s[un__RTCScene]_3E_avx2
PUBLIC 128a70 0 rtcCommitThread___un_3C_s[un__RTCScene]_3E_unuunuavx2
PUBLIC 128a80 0 rtcIntersect1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]avx2
PUBLIC 128a90 0 rtcIntersect___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]avx2
PUBLIC 128b00 0 rtcOccluded1___un_3C_s[un__RTCScene]_3E_REFs[unRTCRay1]avx2
PUBLIC 128b10 0 rtcOccluded___un_3C_s[un__RTCScene]_3E_REFs[vyRTCRay]avx2
PUBLIC 128b80 0 rtcDeleteScene___un_3C_s[un__RTCScene]_3E_avx2
PUBLIC 128b90 0 rtcNewInstance___un_3C_s[un__RTCScene]_3E_un_3C_s[un__RTCScene]_3E_avx2
PUBLIC 128ba0 0 rtcSetTransform___un_3C_s[un__RTCScene]_3E_unuunenum[RTCMatrixType]un_3C_Cunf_3E_avx2
PUBLIC 128bb0 0 rtcNewTriangleMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuavx2
PUBLIC 128bc0 0 rtcNewHairGeometry___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuavx2
PUBLIC 128bd0 0 rtcSetMask___un_3C_s[un__RTCScene]_3E_unuuniavx2
PUBLIC 128be0 0 rtcMapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]avx2
PUBLIC 128bf0 0 rtcUnmapBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]avx2
PUBLIC 128c00 0 rtcSetBuffer___un_3C_s[un__RTCScene]_3E_unuunenum[RTCBufferType]un_3C_unv_3E_unuunuavx2
PUBLIC 128c10 0 rtcEnable___un_3C_s[un__RTCScene]_3E_unuavx2
PUBLIC 128c20 0 rtcUpdate___un_3C_s[un__RTCScene]_3E_unuavx2
PUBLIC 128c30 0 rtcDisable___un_3C_s[un__RTCScene]_3E_unuavx2
PUBLIC 128c40 0 rtcSetIntersectionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_avx2
PUBLIC 128c50 0 rtcSetIntersectionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_avx2
PUBLIC 128c60 0 rtcSetOcclusionFilterFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]_3E_avx2
PUBLIC 128c70 0 rtcSetOcclusionFilterFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]_3E_avx2
PUBLIC 128c80 0 rtcDeleteGeometry___un_3C_s[un__RTCScene]_3E_unuavx2
PUBLIC 128c90 0 rtcNewSubdivisionMesh___un_3C_s[un__RTCScene]_3E_unenum[RTCGeometryFlags]unuunuunuunuavx2
PUBLIC 128ca0 0 rtcNewUserGeometry___un_3C_s[un__RTCScene]_3E_unuavx2
PUBLIC 128cb0 0 rtcSetUserData___un_3C_s[un__RTCScene]_3E_unuun_3C_unv_3E_avx2
PUBLIC 128cc0 0 rtcSetBoundsFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_unuREFs[unRTCBounds]_3E_avx2
PUBLIC 128cd0 0 rtcSetIntersectFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_avx2
PUBLIC 128ce0 0 rtcSetIntersectFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_avx2
PUBLIC 128cf0 0 rtcSetOccludedFunction1___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[unRTCRay1]unu_3E_avx2
PUBLIC 128d00 0 rtcSetOccludedFunction___un_3C_s[un__RTCScene]_3E_unuun_3C____un_3C_unv_3E_REFs[vyRTCRay]unu_3E_avx2
PUBLIC 128d10 0 rtcInit___un_3C_Cunt_3E_avx2
PUBLIC 128d20 0 rtcExit___avx2
PUBLIC 128d30 0 rtcGetError___avx2
PUBLIC 128d40 0 rtcSetErrorFunction___un_3C____Cunenum[RTCError]un_3C_Cunt_3E__3E_avx2
PUBLIC 128d50 0 rtcDebug___avx2
PUBLIC 314470 0 sinf
PUBLIC 3144d0 0 sinf.L
PUBLIC 314740 0 sinf.A
PUBLIC 3149c0 0 _mm_malloc
PUBLIC 314a10 0 _mm_free
PUBLIC 314df0 0 _intel_fast_memcpy.A
PUBLIC 314e00 0 _intel_fast_memcpy.J
PUBLIC 314e10 0 _intel_fast_memcpy.M
PUBLIC 314e20 0 _intel_fast_memcpy.P
PUBLIC 314e30 0 _intel_fast_memcpy
PUBLIC 314ea0 0 _intel_fast_memmove.A
PUBLIC 314eb0 0 _intel_fast_memmove.M
PUBLIC 314ec0 0 _intel_fast_memmove.P
PUBLIC 314ed0 0 _intel_fast_memmove
PUBLIC 314f30 0 _intel_fast_memset.A
PUBLIC 314f40 0 _intel_fast_memset.J
PUBLIC 314f50 0 _intel_fast_memset
PUBLIC 314f90 0 __intel_sse2_strlen
PUBLIC 314fc0 0 __intel_sse4_strlen
PUBLIC 314fe0 0 __intel_memcpy
PUBLIC 316790 0 __intel_memset
PUBLIC 317970 0 __intel_ssse3_memcpy
PUBLIC 31a340 0 __intel_ssse3_rep_memcpy
PUBLIC 31ce00 0 __intel_ssse3_memmove
PUBLIC 31f980 0 __intel_ssse3_rep_memmove
PUBLIC 322480 0 __cacheSize
PUBLIC 3230a8 0 _fini

**Comment by ov** [comment]
I've got much more of 2.3.3 on OSX:

```
MODULE mac x86_64 1655B5B5341B33A6BF2C8B9614F753ED0 libembree.2.3.3.dylib
PUBLIC 1f00 0 dyld_stub_binding_helper
PUBLIC 1f14 0 _dyld_func_lookup
PUBLIC 1f20 0 embree::Stat::Stat()
PUBLIC 2020 0 embree::Stat::Stat()
PUBLIC 2120 0 embree::Stat::~Stat()
PUBLIC 2130 0 embree::Stat::~Stat()
PUBLIC 2140 0 embree::Stat::print(std::ostream&)
PUBLIC 2b70 0 __sti__$E
PUBLIC 2d20 0 std::out_of_range::~out_of_range()
PUBLIC 2d40 0 std::out_of_range::~out_of_range()
PUBLIC 2d70 0 std::underflow_error::~underflow_error()
PUBLIC 2da0 0 std::underflow_error::~underflow_error()
PUBLIC 2dc0 0 std::overflow_error::~overflow_error()
PUBLIC 2df0 0 std::overflow_error::~overflow_error()
PUBLIC 2e10 0 std::range_error::~range_error()
PUBLIC 2e40 0 std::range_error::~range_error()
PUBLIC 2e60 0 std::length_error::~length_error()
PUBLIC 2e90 0 std::length_error::~length_error()
PUBLIC 2eb0 0 std::invalid_argument::~invalid_argument()
PUBLIC 2ee0 0 std::invalid_argument::~invalid_argument()
PUBLIC 2f00 0 std::domain_error::~domain_error()
PUBLIC 2f30 0 std::domain_error::~domain_error()
PUBLIC 2f60 0 __sti__$E
PUBLIC 2f90 0 embree::init_globals()
PUBLIC 3c00 0 embree::Alloc::Alloc()
PUBLIC 3cb0 0 embree::Alloc::~Alloc()
PUBLIC 3cd0 0 embree::Alloc::~Alloc()
PUBLIC 3cf0 0 embree::Alloc::size() const
PUBLIC 3d10 0 embree::Alloc::clear()
PUBLIC 3da0 0 embree::Alloc::malloc()
PUBLIC 3e30 0 embree::Alloc::free(void*)
PUBLIC 3fc0 0 __sti__$E
PUBLIC 40e0 0 embree::Alloc::Alloc()
PUBLIC 41a0 0 std::_Vector_base<void*, std::allocator<void*> >::_M_deallocate(void**, unsigned long)
PUBLIC 41b0 0 std::vector<void*, std::allocator<void*> >::~vector()
PUBLIC 41c0 0 std::_Vector_base<void*, std::allocator<void*> >::~_Vector_base()
PUBLIC 41d0 0 std::vector<void*, std::allocator<void*> >::vector(std::allocator<void*> const&)
PUBLIC 41e0 0 embree::Lock<embree::MutexSys>::~Lock()
PUBLIC 41f0 0 std::_Vector_base<void*, std::allocator<void*> >::_M_get_Tp_allocator()
PUBLIC 4200 0 ISPCAlloc
PUBLIC 42b0 0 ISPCLaunch
PUBLIC 4340 0 ISPCSync
PUBLIC 4410 0 embree::ISPCTask::run(unsigned long, unsigned long, unsigned long, unsigned long, embree::TaskScheduler::Event*)
PUBLIC 4450 0 embree::ISPCTask::finish(unsigned long, unsigned long, embree::TaskScheduler::Event*)
PUBLIC 4480 0 __sti__$E
PUBLIC 44c0 0 embree::TaskScheduler::Event::dec()
PUBLIC 4500 0 embree::TaskScheduler::Event::trigger()
PUBLIC 4510 0 embree::TaskScheduler::EventSync::trigger()
PUBLIC 4550 0 embree::ISPCTask::_run(void*, unsigned long, unsigned long, unsigned long, unsigned long, embree::TaskScheduler::Event*)
PUBLIC 4590 0 embree::ISPCTask::_finish(void*, unsigned long, unsigned long, embree::TaskScheduler::Event*) 
```

but nothing for 2.4

**Comment by svenwoop** [comment]
Can you please send me an email at sven.woop@intel.com. Sven

**Comment by svenwoop** [comment]
I found the problem. This is a bug in dump_syms for MacOSX which is triggered if thread local variables are used. Please submit a bugreport for Google Breakpad to have this issue fixed.
