### ISSUE TITLE
Embree with custom TBB location

### ISSUE THREAD

**Issue by dempo93** [embree/embree#232]
If I want to build Embree with a custom TBB build, embree fails to find TBB, even though I pass the correct Cmake argument:
```
-DEMBREE_TBB_ROOT=/path/to/my/custom/tbb/root
```
This happens because of insufficient hints in FindTBB.cmake:125
The line
```
 SET(TBB_HINTS HINTS ${EMBREE_TBB_ROOT}/lib/intel64/gcc4.4 ${EMBREE_TBB_ROOT}/lib ${EMBREE_TBB_ROOT}/lib64 PATHS /usr/libx86_64-linux-gnu/)
```
should also include
```
${EMBREE_TBB_ROOT}/lib/intel64/gcc4.1 
${EMBREE_TBB_ROOT}/lib/intel64/gcc4.7
```

**Comment by svenwoop** [comment]
This will be fixed in the soon released Embree v3.5.1.
