### ISSUE TITLE
New tagged version with correct version set in rtcore_version.h

### ISSUE THREAD

**Issue by jamiesnape** [embree/embree#233]
Since https://github.com/embree/embree/commit/17a4865d21a2f4f2cf5cd8d7264e8c648392cc24 was committed after [`v3.5.1`](https://github.com/embree/embree/tree/v3.5.1) was tagged, would it be possible to release a version 3.5.2 so we have a stable tagged version where the correct version is reported in `rtcore_version.h` and the appropriate CMake files?

**Comment by svenwoop** [comment]
Please try again. The release was just pointing to the wrong hash.
