### ISSUE TITLE
transparent texture miss.

### ISSUE THREAD

**Issue by tom-sakai601220** [embree/embree#236]
![pers](https://user-images.githubusercontent.com/10066597/53938962-25fccb00-40f5-11e9-8b0e-95af99eed7fe.jpg)

Hi,
Why is the shape behind the transparent surface not displayed?
i use embree filterfunction as follows

struct MyIntersectContext : RTCIntersectContext
{
    RSRay& rsray;
    IntersectCallback& cb;
    rf_uint skipTag;
    rf_uint hitCount;
    MyIntersectContext(RSRay& rsray, IntersectCallback& cb)
        : rsray(rsray)
        , cb(cb)
        , skipTag((rf_uint)rsray.skipTag)
        , hitCount(0)
    {}
};

static void RaySkipFilter(const struct RTCFilterFunctionNArguments* args)
{
    Geom* geom = static_cast<Geom*>(args->geometryUserPtr);
    MyIntersectContext* context = (MyIntersectContext*)args->context;
    context->hitCount++;
   RTCRay* ray = (RTCRay*)args->ray;
    RTCHit* hit = (RTCHit*)args->hit;
    if ((geom->ownerIndex + hit->primID) == context->skipTag)
        {
            args->valid[0] = 0;
            return;
        }
        if ("this geom has transparent texture and is transparent" )
        {
            args->valid[0] = 0;
            ray->tfar = rsray.cmaxt;
            return;
        }
    }

**Comment by svenwoop** [comment]
Your code looks correct, at least you properly set args->valid[0]=0 to skip an intersection.

In your image the problem is probably the trees on the left, where you hit the outside of the tree? But the trees on the right look correct? Maybe a problem with your decision when to filter out the hit.

Sven

**Comment by cbenthin** [comment]
Does the issue still persists?

**Comment by cbenthin** [comment]
If the issue persists please re-open.
