### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by xelatihy** [embree/embree#238]
Is there an API for serialising and deserializing Embree data structures to disk?

**Comment by cbenthin** [comment]
No as giving a few CPU cores the BVH build times are typically smaller than loading the serialized data from disk. IMHO it is more beneficial to just store/load the vertex/index data to/from disk and always re-build the BVH.

**Comment by xelatihy** [comment]
I am playing around with Disney Moana island and BVH build time with high quality is not that fast actually. Loading the same amount of memory from SSD is way quicker on my 6 core machine. But this is a very contrived case.

Ok thanks. I'll close this.
