### ISSUE TITLE
Wrong BVH bounding boxes constructed for user defined BVH leaf degree of N elements

### ISSUE THREAD

**Issue by nanzhang790** [embree/embree#240]
Using embree 3.5.0, I'm building a user-defined BVH where each leaf node can hold up to 6 element IDs. For the Morton code based fast BVH builder ( rtcBuildBVHMorton() in rtcore_builder.cpp), the bounding boxes of leaf nodes, which are stored in their immediate parent nodes seem to be wrong. The bounding box stores only the bounds for the first element, not the combined bounds of all the 6 elements. Also, the element IDs are wrong. I've found the problem in the corresponding lambda function. Below is my fix, and I hope that can be merged in. 

    /* lambda function that creates BVH leaves */
            [&](const range<unsigned>& current, const FastAllocator::CachedAllocator& alloc) -> std::pair<void*, BBox3fa>
        {
            /*
            const size_t id = morton_src[current.begin()].index;
            const BBox3fa bounds = prims[id].bounds();
            void* node = createLeaf((RTCThreadLocalAllocator)&alloc,prims_i+current.begin(),current.size(),userPtr);
            return std::make_pair(node,bounds);
            */
            const unsigned int id0 = current.begin();
            RTCBuildPrimitive localprims[16] = { prims_i[morton_src[id0].index] };
            BBox3fa bounds((const BBox3fa &)localprims[0]);
            for (unsigned int i = 1; i < current.size(); i++) {
                localprims[i] = prims_i[morton_src[id0 + i].index];
                bounds.extend((const BBox3fa &)localprims[i]);
            }
            void* node = createLeaf((RTCThreadLocalAllocator)&alloc, localprims, current.size(), userPtr);
            return std::make_pair(node, bounds);
        },

**Comment by cbenthin** [comment]
Thanks a lot of for pointing this out, and yes this is a bug. We going to fix this in the next release.
