### ISSUE TITLE
Subdivision tutorial has zero-length buffers

### ISSUE THREAD

**Issue by prideout** [embree/embree#244]
In the `addCube` function, the `itemCount` argument  passed to `rtcSetSharedGeometryBuffer` is zero for the crease index and crease vertex buffers.  If this is intentional then it should probably be explained with a comment.

Also there are some commented-out codelines in `addCube` which should probably be deleted.

**Comment by cbenthin** [comment]
Thanks for pointing this out, and yes, the explanation is missing. If the itemCount is zero the subdiv code ignores the specific buffer. We'll clean this tutorial up a bit for the next release.
