### ISSUE TITLE
Make RTC_MAX_USER_VERTEX_ATTRIBUTES public

### ISSUE THREAD

**Issue by tcauchois** [embree/embree#246]
RTC_MAX_USER_VERTEX_BUFFERS and RTC_MAX_INDEX_BUFFERS are both hidden in kernels/common/rtcore.h.  It would be great if these could be in a public header.

**Comment by cbenthin** [comment]
We probably could move these constants to the public header but do you really need to query them? There are currently set to ~64k which is a lot. Does you app come even close to these numbers (just curious)?

**Comment by tcauchois** [comment]
We don't get anywhere near that number, but we're loading in lots of data from disk and we assign buffer slots with a for loop.  That for loop has an early out if the buffer count gets too high; it would be nice to have an official constant to use, even though we probably won't hit the check.

**Comment by cbenthin** [comment]
Looked into this a bit more.  RTC_MAX_INDEX_BUFFERS is actually never used and therefore obsolete, while RTX_MAX_USER_VERTEX_BUFFERS only applies to the interpolation code for subdivision surfaces. If you don't deal with vertex interpolation of subdivision surfaces there's actually no limit.
