### ISSUE TITLE
Problem in ccmake

### ISSUE THREAD

**Issue by bjourne** [embree/embree#247]
The following output when configuring:
```CMake Warning (dev) at common/cmake/test.cmake:31 (SET):
   implicitly converting 'INT' to 'STRING' type.
 Call Stack (most recent call first):
   CMakeLists.txt:101 (INCLUDE)
 This warning is for project developers.  Use -Wno-dev to suppress it.

 CMake Error at common/cmake/ispc.cmake:54 (MESSAGE):
   Intel SPMD Compiler (ISPC) not found.  Disable EMBREE_ISPC_SUPPORT or
   install ISPC.
 Call Stack (most recent call first):
   CMakeLists.txt:451 (INCLUDE)
```
This prevents the project from being built.

**Comment by cbenthin** [comment]
Could you provide some more info on the Embree and cmake version and the platform (linux, windows, ..) you used?

**Comment by cbenthin** [comment]
Also it seems that cmake couldn't find the ISPC compiler. If you don't need ISPC support just turn off EMBREE_ISPC_SUPPORT. If you need ISPC support you need to provide a path to the ispc executable by EMBREE_ISPC_EXECUTABLE.

**Comment by bjourne** [comment]
Cmake 3.14.5 and Linux. Embree is from github

**Comment by cbenthin** [comment]
Did turning off ISPC support or setting EMBREE_ISPC_EXECUTABLE work?

**Comment by bjourne** [comment]
yes

**Comment by cbenthin** [comment]
Ok, issue seems to be resolved, closing it.
