### ISSUE TITLE
Fail to create RTC_BUFFER_TYPE_NORMAL buffer

### ISSUE THREAD

**Issue by TH3CHARLie** [embree/embree#251]
Hello! I am writing a program that uses embree to do high performance ray intersection. However, I encounter some problem when loading my triangle mesh. The error originates from the nullptr returned from a failed **rtcSetNewGeometryBuffer**. Here is the detailed description:

My workspace enviroment
- OS: Windows 10
- Compiler: MSVC 16.0 from Visual Studio 2019
- Embree: 3.5.2 (Installed using **embree-3.5.2-x64.vc12.msi**)

In my code, I first create a **RTCGeometry** and then use **rtcSetNewGeometryBuffer** to create vertices, normals and faces buffer respectively. However, the second **rtcSetNewGeometryBuffer** which uses **RTC_BUFFER_TYPE_NORMAL** as format always return nullptr. The detailed code is shown below:
```c++
// creating embree geometry
int create_geometry(RTCDevice device, RTCScene scene,
	const std::vector<glm::vec3>& input_vertices,
	const std::vector<unsigned int>& input_indices,
	const std::vector<glm::vec3>& input_normals) {
    
	RTCGeometry geom = rtcNewGeometry(device, RTC_GEOMETRY_TYPE_TRIANGLE);
	size_t vertex_cnt = input_vertices.size();
	size_t normal_cnt = input_normals.size();
	size_t face_cnt = input_indices.size() / 3;

	// set vertices
	Vertex3f* vertices = (Vertex3f*)rtcSetNewGeometryBuffer(
		geom, RTC_BUFFER_TYPE_VERTEX, 0, RTC_FORMAT_FLOAT3, sizeof(Vertex3f),
		vertex_cnt);
	for (size_t vertex_id = 0; vertex_id < vertex_cnt; vertex_id++) {
		// compute
	}

	// Set normals
	Vertex3f* normals = (Vertex3f*)rtcSetNewGeometryBuffer(
		geom, RTC_BUFFER_TYPE_NORMAL, 0, RTC_FORMAT_FLOAT3, sizeof(Vertex3f),
		normal_cnt);
	for (size_t normal_id = 0; normal_id < normal_cnt; normal_id++) {
		// compute
	}

	// Set triangles.
	auto triangles = (Triangle*)rtcSetNewGeometryBuffer(
		geom, RTC_BUFFER_TYPE_INDEX, 0, RTC_FORMAT_UINT3, sizeof(Triangle),
		face_cnt);
	for (size_t triangle_id = 0; triangle_id < face_cnt; triangle_id++) {
		// compute
	}
	rtcCommitGeometry(geom);
	unsigned int geomID = rtcAttachGeometry(scene, geom);
	rtcReleaseGeometry(geom);
	rtcCommitScene(scene);
	return geomID;
}
```
I used **rtcGetDeviceError** to get the error code and its value is 2 which is **RTC_ERROR_INVALID_ARGUMENT**, so I tried to replace the **RTC_BUFFER_TYPE_NORMAL** into **RTC_BUFFER_TYPE_NORMAL**  and it did succeed, altough meaningless in my case. 

I have read docs from https://www.mankier.com/3/rtcSetGeometryBuffer.3embree3 and it says the API requires a 4-byte alignment and in my case Vertex3f is 12 bytes. And I also search related usage in this repo and find similar usage that creates normal buffer. Is this a potential bug or just my misunderstanding and misuse of the API?

**Comment by svenwoop** [comment]
The RTC_BUFFER_TYPE_NORMAL was just introduced for normal oriented curves, that buffer type is not supported for triangle meshes. There is also no need to pass the normal buffers to Embree, you can just interpolate normal inside the app.
