### ISSUE TITLE
Slight memory leak in regression test registration

### ISSUE THREAD

**Issue by AirGuanZ** [embree/embree#254]
Hi, I meet slight memory leak when using embree 3.5.2 release. I may have found the reason.

There is a global variable in `common/sys/regression.cpp, line 23`:
```
static std::unique_ptr<std::vector<RegressionTest*>> regression_tests;
```
which contains all registered regression tests. However those tests are registered by some global class intances. Global variables in different compilation units are initialized in an unspecified order. For example, test A registers itself before calling ctor of `regression_tests`, which makes the contained `vector<RegressionTest*>` never released. That causes slight memory leak in my usage (detected by [_CrtSetDbgFlag](https://docs.microsoft.com/en-us/visualstudio/debugger/crt-debug-heap-details?view=vs-2019#BKMK_Check_for_heap_integrity_and_memory_leaks)).

I tried to modify `regression_tests` to a local static variable:
```
static std::unique_ptr<std::vector<RegressionTest*>> &get_regression_tests()
{
    std::unique_ptr<std::vector<RegressionTest*>> ret;
    return ret;
}
#define regression_tests (get_regression_tests())
```
to ensure the initialization order, and that does fix the memory leak.

**Comment by svenwoop** [comment]
Thanks for reporting this. I fixed this in our internal development branch. Next release will contain the fix.
