### ISSUE TITLE
Question: how to compute intersection for bilinear patches?

### ISSUE THREAD

**Issue by jiangzhongshi** [embree/embree#255]
I am working on an application that would use ray intersection with bilinear patches, and I think `kernels/subdiv/bilinear_patch.h` could be useful.

However, I couldn't find relevant information in the API. Is there an example for computing the intersection between a ray and a bilinear patch? Any help would be appreciated.

Thank you!

**Comment by cbenthin** [comment]
The API does not expose bilinear patches as API-supported primitive types, and bilinear_patch.h does not include any direct ray-bilinear patch intersection code. In general for non-supported primitive types like bilinear patches it's recommended to use user-defined geometry and implement the ray intersection code yourself. There are some ray-bilinear patch intersection approaches out there, e.g. 
www.sci.utah.edu/~kpotter/publications/ramsey-2004-RBPI.pdf or the recent work by Reshetov et al.

**Comment by jiangzhongshi** [comment]
Thanks for the quick reply!
