### ISSUE TITLE
Are point queries for oriented discs supported?

### ISSUE THREAD

**Issue by benjaminum** [embree/embree#257]
Hi,
the point query function does not seem to get called for this geometry type.
I also could not find an example with oriented discs in the verify tutorial.
Are spheres the only supported point geometry type?

**Comment by freibold** [comment]
Hi,
oriented discs are a variant of RTC_GEOMETRY_TYPE_POINT, which are not yet supported unfortunately. However, it is on the roadmap. As a workaround you could implement the oriented discs as user-defined geometry.

**Comment by benjaminum** [comment]
Thanks for the info!
