### ISSUE TITLE
Error building on Mac OS using GCC

### ISSUE THREAD

**Issue by zomgrolf** [embree/embree#258]
Not sure, if this is a supported build platform (looking at the CMake files suggests it is), but I've run into an error when trying to build Embree on Mac OS (10.13) using GCC 9.2 (installed using Homebrew):

```
[  0%] Building CXX object common/sys/CMakeFiles/sys.dir/sysinfo.cpp.o
g++-9: error: unrecognized command line option '-stdlib=libc++'
make[2]: *** [common/sys/CMakeFiles/sys.dir/sysinfo.cpp.o] Error 1
make[1]: *** [common/sys/CMakeFiles/sys.dir/all] Error 2
make: *** [all] Error 2
```
I believe this is caused by [this line in gnu.cmake](https://github.com/embree/embree/blob/7fd38547d5e15caa947f21b33f2acf140961b137/common/cmake/gnu.cmake#L77):
```CMake 
  SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -stdlib=libc++")             # link against libc++ which supports C++11 features
```
as `stdlib=libc++` is a clang-only parameter.
Removing that line fixes this error.

**Comment by jomeng** [comment]
Thank you for your report!

**Comment by jomeng** [comment]
A small update: We have come to the conclusion that we will not include this fix in our distribution. The reason is that GCC is by default symlinked to Clang in modern macOS distributions. However, we will include a note in the documentation.
Thank you again for your report!
