### ISSUE TITLE
add a CMakeLists.txt option to disable testing altogether

### ISSUE THREAD

**Issue by xelatihy** [embree/embree#263]
In the default CMakeLists there is no reliable manner to disable testing completely. It would suffice to add a CMake option that enables and disables testing and that wraps line 84 (containing `INCLUDE(test)`) in the main CMakeLists.txt. This would allow the project to be included into another without polluting tests names.

**Comment by svenwoop** [comment]
This will be fixed in the next release. You will be able to disable testing through setting the CMake variable BUILD_TESTING to OFF>
