### ISSUE TITLE
Subdivsion patch grid debug

### ISSUE THREAD

**Issue by cedricp** [embree/embree#264]
Hi,

We're refactoring our rendering engine with Embree for raytracing functions, it works really well.
We're wondering if there's a way to access patch grid (quads/tris) information for debugging purpose ? I mean, is it possible after an intersection to know the u and v values for the intersected micropolygon, not the subdiv patch ?

Thank you

**Comment by svenwoop** [comment]
There is no way of getting per quad uv's when using the subdiv primitive. However, you can tessellate the subdiv surface using rtcInterpolate to a grid mesh (or triangle or quad mesh), which will give you the information.
