### ISSUE TITLE
Source checksum changed

### ISSUE THREAD

**Issue by fxcoudert** [embree/embree#266]
The SHA256 checksum for source code `https://github.com/embree/embree/archive/v3.6.1.tar.gz` was `1d82b334114d8784a455fc3d33d3a5860101a4a05a93c79b35cc752509234458` when the release shipped. This was confirmed as part of Homebrew testing.

Now our CI doesn't accept to build this from source anymore, as the checksum for the source release has changed to `9030ab589cf7134b5995af3639b5e3e9aacaab95d839f619817e2c1348c9b51a`. Is this a "legitimate" re-release, or was the code modified for malicious purposes?

**Comment by svenwoop** [comment]
We did a re-release to include signed versions of GLFW library inside the release. This also caused some code changes. Thus this change is from us and nobody tampered with the ZIP file.

**Comment by fxcoudert** [comment]
Thanks for clearing that up.
