### ISSUE TITLE
Installation Issue(Linux)

### ISSUE THREAD

**Issue by adweidh** [embree/embree#267]
While installing Embree unable to set Rpath.

Kindly suggest !!

**Comment by svenwoop** [comment]
Could you please give more details on what you want to do?

**Comment by adweidh** [comment]
"We recommend adding a relative **RPATH** to your application that points to the location where Embree (and TBB) can be found, e.g. $ORIGIN/../lib"

This is required during installation of Embree in Linux. Kindly suggest how to perform above step !!

**Comment by svenwoop** [comment]
If you install embree under Linux using the RPM or ZIP file you do not have to set any rpath to get the tutorials working.

However, if you link against Embree you can set an RPATH if Embree is not in default location. E.g. if you ship an app that installs itself in some folder app_path/bin and puts its shared libraries, including embree into app_path/lib, then you need to set an rpath to your application located in bin folder using the -Wl,rpath,$ORIGIN/../lib GCC compile option in order for the app to find Embree.
