### ISSUE TITLE
Embree 2.4 doesn't compile on gcc 2.4 (standard on centos)

### ISSUE THREAD

**Issue by ospray-owner** [embree/embree#27]
gcc flags specify --std=c++11, which gcc 2.4 doesn't recognize.
removing that flags creates compile errors in parallel_for expressiosns.

**Comment by cbenthin** [comment]
Embree v2.4 depends on some c++11 features which are only supported by gcc 4.8.2 or later. As an alternative you could use Clang 3.4.2 or later. All supported compilers are listed on http://embree.github.io/downloads.html .
