### ISSUE TITLE
Memory leak in common/sys/vector.h

### ISSUE THREAD

**Issue by janm31415** [embree/embree#270]
I think there is a memory leak in lines 70 to 77 in common/sys/vector.h

The current implementation is
`__forceinline vector_t& operator=(vector_t&& other) `
` {`
`  alloc = std::move(other.alloc);`
 `  size_active = other.size_active; other.size_active = 0;`
 `  size_alloced = other.size_alloced; other.size_alloced = 0;`
 `  items = other.items; other.items = nullptr;`
`  return *this;`
`}`

The assigment `items = other.items` can give a leak, as `items` is not necessarily empty and is not cleaned up. A possible fix could be

`__forceinline vector_t& operator=(vector_t&& other) `
` {`
`  vector_t temp(std::move(other));`
`  swap(temp);`
`  return *this;`
`}`

**Comment by svenwoop** [comment]
Thanks for reporting. Just fixed this in our devel branch. This will make it into the next release.
