### ISSUE TITLE
Use of uninitialized variable in Cylinder::intersect

### ISSUE THREAD

**Issue by brechtvl** [embree/embree#274]
`t_o.lower` should be changed to `t0` and `t1`, to match `CylinderN::intersect`
https://github.com/embree/embree/blob/master/kernels/geometry/cylinder.h#L87
https://github.com/embree/embree/blob/master/kernels/geometry/cylinder.h#L95

**Comment by svenwoop** [comment]
Thanks a fix will be in the next release. Embree is not using the geometry normals calculated by that cylinder code, thus this bug cannot get triggered through the API.
