### ISSUE TITLE
Add user pointer to RTCIntersectContext

### ISSUE THREAD

**Issue by vaspoul** [embree/embree#278]
It would be useful for the context to contain a user pointer (void*). This would be accessed during the (secondary) filter callback and would allow for user state to passed to the filter function.

This would be similar to the existing per-geometry mechanism.

The problem with RTCIntersectContext::filter is that it's a raw function pointer which limits the type of functions that can be passed to it (e.g. static or global functions). Having a void* member in RTCIntersectContext would allow class member functions to be passed.

**Comment by svenwoop** [comment]
We guarantee to just pass the intersect context pointer to the callbacks. That means you can just derive a struct from the RTCIntersectContext struct that adds that pointer, or arbitrary additional data to use in the callbacks.

**Comment by vaspoul** [comment]
That's awesome! Thank you :)
I'm really loving this API!
