### ISSUE TITLE
MAP_HUGETLB is Linux-specific (unbreak Embree on *BSD)

### ISSUE THREAD

**Issue by danfe** [embree/embree#280]
Currently, when building Embree under e.g. FreeBSD, the following patch is required.  I was thinking that perhaps it can be upstreamed as it does not pessimize anything and makes the core actually more correct.
```patch
--- common/sys/alloc.cpp.orig
+++ common/sys/alloc.cpp
@@ -249,7 +249,7 @@
         hugepages = true;
         return ptr;
       }
-#else
+#elif defined(MAP_HUGETLB)
       void* ptr = mmap(0, bytes, PROT_READ | PROT_WRITE, MAP_PRIVATE | MAP_ANON | MAP_HUGETLB, -1, 0);
       if (ptr != MAP_FAILED) {
         hugepages = true;
```

**Comment by svenwoop** [comment]
Just added this fix to our internal devel branch. The fix will be in the next release.
