### ISSUE TITLE
Using existing TBB target when building Embree from source

### ISSUE THREAD

**Issue by thonat** [embree/embree#281]
Hi,

In my CMake setup, `Embree` is a dependency built from source (using `add_subdirectory`), and is just another user of a pre-built `TBB` package. 

There is no check in `Embree`'s main CMakeLists (l.455), so if a `find_package(TBB)` call happens before and `TBB`'s targets already exist, CMake will complain about already defined targets:
```
add_library cannot create imported target "TBB::tbb" because another
  target with the same name already exists.
```
A simple fix for that is to add a check in `Embree`'s main CMakeLists:

```
IF(NOT TBB_FOUND)
     FIND_PACKAGE(TBB REQUIRED)
ENDIF()
```

However, with this solution, it seems that `TBB`'s includes are not propagated to `Embree`, and manually doing so in the project's CMakeLists is not supposed to be done according to CMake.
Moreover, the created `Embree` target does not seem to include `Embree`'s include dirs and they have to be manually included to the project target include directories, which makes me believe that I am definitely taking the wrong course of action here. 

So what would be the correct way to have `Embree` use an already defined `TBB` ?

**Comment by syoyo** [comment]
You may need to prepare your own CMakeLists(e.g. by forking embree3) to lookup TBB.

FYI, we've been successfully building embree3 using `add_subdirectory` + external TBB with this setup:
 
https://github.com/lighttransport/embree-aarch64/blob/ccd8a651488708420cb884b633fb59df7171ccdc/CMakeLists.txt#L496

**Comment by freibold** [comment]
Hi,

the newest version of Embree (3.11) will use an existing TBB target if Embree is included using add_subdirectory.

Please reopen, if this still doesn't work for you.

Cheers
