### ISSUE TITLE
Shared library CMake target export

### ISSUE THREAD

**Issue by pshriwise** [embree/embree#282]
I recently noticed that CMake targets are only exported for a static build of the Embree library. I'm curious about why that is and if it might be possible to export targets for shared library builds in the future.

**Comment by svenwoop** [comment]
We already noticed that and will export targets for shared library builds in the future.

**Comment by pshriwise** [comment]
That's great! Would you like me to close this as it's already on your radar or leave it open for now?

Thanks a ton for all the work you and the rest of the embree team have put into this library btw. It's really nice.

**Comment by svenwoop** [comment]
I will close this issue, as we have this internally tracked already.
