### ISSUE TITLE
Missing rpath in libembree3.so.3

### ISSUE THREAD

**Issue by nihofm** [embree/embree#283]
As of version 3.9, embree fails to provide a rpath in the distributed libembree.so.3 on Linux, thus, if available, linking against the system libtbb.so.2 at runtime and failing with a symbol lookup error due to a version mismatch on some distributions (verified on Ubuntu 18.04, Debian 10.3 and Linux Mint 19). It happens to work on distributions providing a more recent version of TBB (i.e. Arch Linux), where the provided libtbb.so.2 is simply ignored.
Via setting the LD_LIBRARY_PATH environment variable, this issue can be worked around, yet the solution is not very nice.

In contrast, OIDN (https://github.com/OpenImageDenoise/oidn), which similarly ships with a provided libtbb.so.2, works out of the box on all tested distributions, due to an included rpath, see below.

$ objdump -x libembree3.so.3 | grep PATH

$ objdump -x libOpenImageDenoise.so.1.2.0 | grep PATH
  RPATH                $ORIGIN:$ORIGIN/../lib

My solution was to compile embree from source with internal threading enabled to avoid the TBB dependency, so if you must rely on TBB, please make sure the rpath setup is working correctly.

**Comment by svenwoop** [comment]
Thanks for reporting. We fix this in the next Embree release.
