### ISSUE TITLE
v3.9.0 fails to build with ISPC 1.13.0

### ISSUE THREAD

**Issue by tweakoz** [embree/embree#284]
because of these errors:
embree/tutorials/common/tutorial/../math/../common.isph:6:18: 
Error: Redefining uint8/uint16/uint32/uint64 type which is part 
of ISPC language since version 1.13. 
Remove this typedef or use ISPC_UINT_IS_DEFINED to detect that these types are defined.

**Comment by svenwoop** [comment]
Thanks for reporting. This will get fixed in the next release.
