### ISSUE TITLE
Behavior Inconsistency of Flag RTC_SCENE_FLAG_CONTEXT_FILTER_FUNCTION

### ISSUE THREAD

**Issue by SilentAntenna** [embree/embree#285]
`rtcIntersect1()` triggers the filter function for scenes without flag `RTC_SCENE_FLAG_CONTEXT_FILTER_FUNCTION`. Same for `rtcIntersect1M()` when the number of rays is 1.

For instanced scenes, the document should state explicitly that one should set the `RTC_SCENE_FLAG_CONTEXT_FILTER_FUNCTION` flag for every scene on the path from root to leaf on the instance tree to get the filter function invoked.

**Comment by svenwoop** [comment]
The RTC_SCENE_CONTECT_FILTER_FUNCTION flag has to get enabled to use a filter function function. That filter function also work in some cases when that flag is not set is on purpose. For some primitive types where we saw a larger overhead of the existance of the intersection filter invokation, we create a special code version without that call. While the call is still present in other codepaths. Adding a check to these non-optimized code path, to only invoke the filter function when the flag is set would just slow that code path down for no benefit to the user.

I will add to the documentation that the flag has to be set also for instanced scenes.
