### ISSUE TITLE
Minimal example not working

### ISSUE THREAD

**Issue by brainsandwich** [embree/embree#289]
I'm new to using embree, but I started by looking at the "minimal" tutorial to learn the basics.

However it does not seem to work. In the example, two rays are cast into the scene ; the first should hit the triangle and the second should miss it.
But none intersect the triangle.

I've got this output : 

```
0.000000, 0.000000, -1.000000: Did not find any intersection.
1.000000, 1.000000, -1.000000: Did not find any intersection.
```

I've tried changing the coordinates to 0.2, 0.2, -1.0 for the first ray (so it should be "more inside" the triangle) but to no avail.

Other examples seem to work (I've tried running curve_geometry and lazy_geometry) so there should only be an issue with the minimal example.

Thank you,
Alexandre

PS -- my config :
Windows 10
Visual Studio 2019
CMake 3.17.1

Summary of cmake options used (looking in generated embree-config.cmake) :
```
SET(EMBREE_VERSION 3.10.0)
SET(EMBREE_VERSION_MAJOR 3)
SET(EMBREE_VERSION_MINOR 10)
SET(EMBREE_VERSION_PATCH 0)
SET(EMBREE_VERSION_NOTE "")

SET(EMBREE_MAX_ISA AVX2)
SET(EMBREE_ISA_SSE2  ON)
SET(EMBREE_ISA_SSE42 ON)
SET(EMBREE_ISA_AVX ON) 
SET(EMBREE_ISA_AVX2  ON)
SET(EMBREE_ISA_AVX512KNL OFF)
SET(EMBREE_ISA_AVX512SKX OFF)

SET(EMBREE_BUILD_TYPE )
SET(EMBREE_ISPC_SUPPORT ON)
SET(EMBREE_STATIC_LIB OFF)
SET(EMBREE_TUTORIALS OFF)

SET(EMBREE_RAY_MASK ON)
SET(EMBREE_STAT_COUNTERS OFF)
SET(EMBREE_BACKFACE_CULLING OFF)
SET(EMBREE_FILTER_FUNCTION ON)
SET(EMBREE_IGNORE_INVALID_RAYS OFF)
SET(EMBREE_TASKING_SYSTEM INTERNAL)
SET(EMBREE_COMPACT_POLYS ON)

SET(EMBREE_GEOMETRY_TRIANGLE ON)
SET(EMBREE_GEOMETRY_QUAD ON)
SET(EMBREE_GEOMETRY_CURVE ON)
SET(EMBREE_GEOMETRY_SUBDIVISION ON)
SET(EMBREE_GEOMETRY_USER ON)
SET(EMBREE_GEOMETRY_POINT ON)

SET(EMBREE_RAY_PACKETS ON)
SET(EMBREE_MAX_INSTANCE_LEVEL_COUNT 1)
```

(I first tried with embree-3.11.0-alpha.0 with the same results)

**Comment by svenwoop** [comment]
You shoot the ray exactly at the triangle edge. In fast mode (default) such a ray may actually miss the triangle. Please enable the RTC_SCENE_FLAG_ROBUST scene flag to fix that issue.

**Comment by brainsandwich** [comment]
Ok I've tried with rtcSetSceneFlags(scene, RTC_SCENE_FLAG_ROBUST) :

```
0.000000, 0.000000, -1.000000: Did not find any intersection.
1.000000, 1.000000, -1.000000: Did not find any intersection.
```

Tried again at origin 0.2, 0.2, -1.0 :

```
0.200000, 0.200000, -1.000000: Did not find any intersection.
1.000000, 1.000000, -1.000000: Did not find any intersection.
```

I've run the tutorial code verbatim at first, and with just this modification so there definitely is some issue.
It might be the CMake options I've set ! I'll try again with the default config.

**Comment by brainsandwich** [comment]
While reading the manual, I stumbled on a link to download a prebuilt version of embree-3.10.0 for msvc140, and this time it worked fine !

I'll use this one for now.
But will try again the minimal example with embree built with default cmake options for the record.

**Comment by brainsandwich** [comment]
Default options work.

It's quite long to build so I'll call it a day, but some options between "default" and the listing I gave broke the minimal example. I don't know embree enough to tell which cmake option I shouldn't have ticked.

**Comment by svenwoop** [comment]
Just looked over your build settings. The reason you found no hit is that you enabled ray masking and the minimal tutorial sets the ray mask to 0. If you set the mask to 1 you will also get the hit with ray masking enabled.
