### ISSUE TITLE
rtcDisableGeometry() does not work if there are no other modified objects in the scene

### ISSUE THREAD

**Issue by dleex** [embree/embree#290]
Seems like disabled geometry isn't considered "modified" so if you disable a geometry in a scene and commit the scene (via rtcCommitScene()), the scene sees no modified object and does nothing.
I think the reason why enable_disable test (in "verify") fails to catch this case is because there's at least 1 object that gets enabled each test iteration, so the scene always commits.

**Comment by cbenthin** [comment]
We have fixed this in our internal branch. Will be included in the next release.
