### ISSUE TITLE
Remove intelstyle folder from embree

### ISSUE THREAD

**Issue by TH3CHARLie** [embree/embree#294]
https://github.com/embree/embree/commit/9ef25db523f0ad852d8b5bb10193aaea580e2176 removed the internal submodule but did not delete the folder for that, causing git clone recursive to fail:

a log from Travis CI where Foo/Bar uses Embree as a submodule
```
git clone --depth=50 --branch=master https://github.com/Foo/Bar.git Foo/Bar
....
Submodule path 'ext/embree': checked out '9ef25db523f0ad852d8b5bb10193aaea580e2176'
fatal: No url found for submodule path 'ext/embree/doc/intelstyle' in .gitmodules
Failed to recurse into submodule path 'ext/embree'
```

A possible fix is to remove the empty folder I think.

**Comment by cbenthin** [comment]
The master branch should have this removed already. Will definitely be gone in the next release.

**Comment by TH3CHARLie** [comment]
@cbenthin Thanks for the help! But checking the GitHub page: https://github.com/embree/embree/tree/master/doc shows intelstyle is still there and my local clone on the latest commit on the master branch also has that empty folder as well.

**Comment by freibold** [comment]
It's weird that the empty folder causes problems for you. Anyways, I deleted the folder on the current master branch. Can you check if recursive cloning works for you now?

**Comment by TH3CHARLie** [comment]
> It's weird that the empty folder causes problems for you. Anyways, I deleted the folder on the current master branch. Can you check if recursive cloning works for you now?

Thanks for the updates! I just verified that recursive cloning works now both locally and on Travis CI.
