### ISSUE TITLE
no intersection reported between primitive and ray if they are planar.

### ISSUE THREAD

**Issue by thebluespecs** [embree/embree#298]
why does embree not report an intersection when a ray intersects with a triangle in the same plane. I crossed checked it with the <code>Minimal</code> tutorial.

**Comment by thebluespecs** [comment]
triangle 000 // 100 // 010 
ray origin : -1, 0.5, 0
ray direction : 1, 0, 0

desired result is tfar = 0.5
but it doesn't report and intersection.

**Comment by cbenthin** [comment]
This is a corner case and Embree follows the convention that it will not report an intersection when the ray and the triangle are in the same plane. Btw: Most ray-triangle intersection algorithms include a step where a division of the distance to the triangle plane is computed. In the above case, the distance is 0 and one would end up with 1 / 0 which is undefined.
