### ISSUE TITLE
Error when creating a large number of Devices

### ISSUE THREAD

**Issue by aurelw** [embree/embree#303]
I need to create a huge number of devices with associated scenes and objects. Total available memory is not the issue. After 1021 devices created within a process the rtcNewDevice function fails with "RTC_ERROR_`UNKNOWN". 

Tested with v3.11

```
#include <iostream>

#include <embree3/rtcore.h>
#include <embree3/rtcore_ray.h>

int main() {
    /* first create over 5k embree devices */
    std::vector<RTCDevice> devices;
    for (int i=0; i<5000; i++) {
        auto device = rtcNewDevice(NULL);
        devices.push_back(device);
        if (rtcGetDeviceError(device) != RTC_ERROR_NONE) {
            std::cout << "Error creating device after " << i 
                      << " devices created." << std::endl;
            return 1;
        }
    }
}
```

I need to cache a large number of raytrees in a single process.... either by creating a huge number of independent devices or, as a workaround, at least thousands of scenes within a single device. Is there a way to increase that limit, or do I have to come up with some pooling to create N devices with M scenes to work around certain limits?

**Comment by svenwoop** [comment]
You can only create about 1024 Embree devices, as it contains a pthread thread local storage object to track per thread error codes for each device.
But creating many Embree devices is not what you should do in the first place. An app should typically just create one Embree device and use that one device. You can create as many scenes as you want in a single device.
