### ISSUE TITLE
Assert triggered in Debug Mode when building embree as static library using Apple Clang with multiple ISAs selected

### ISSUE THREAD

**Issue by KaoCC** [embree/embree#305]
A PR is created to disallow such case #304

**Comment by KaoCC** [comment]
`Assertion failed: (sse2::getISA() <= SSE2), function verify, file /.conan/data/embree3/3.12.0/_/_/build/af669e3d7636a549a364babc5add7131235ce800/source_subfolder/kernels/common/state.cpp, line 163.
`
x86_64 Macos Apple Clang 11.0 Debug static library

**Comment by merwaaan** [comment]
Same issue here ✋
Apple Clang 11 + Debug + static library

**Comment by svenwoop** [comment]
Static library compilation with multiple ISAs enabled is not supported on macOS. There is a linking issue that mixes the symbols from different ISAs in the static library. Please use a shared library when using multiple ISAs or just compile to a single ISA.
