### ISSUE TITLE
Using prebuilt release tarball with system wide TBB

### ISSUE THREAD

**Issue by epsilon-0** [embree/embree#306]
I was wondering if it was possible to use the precompiled releases with a system-wide installation of TBB?

This way embree can be installed in standard locations `/usr/bin /usr/lib64` ?

Thanks,
Aisha

**Comment by svenwoop** [comment]
We once shipped RPMs that were linked to the system TBB install, but we stopped doing this as it is the task of the Linux distributor to package Embree. Which Linux version are you using? With Fedora you can directly install Embree using their package manager.

**Comment by epsilon-0** [comment]
@svenwoop 
I'm a packager for Gentoo and so far we don't have Embree in our database.
I wanted to get started with the prebuilt package first and then give the option to also compile from scratch.
We already have tbb distributed and I was noticing a conflict, so I wanted to know if I could us the system-wide tbb instead.

On gentoo, everything is compiled from scratch so, if I distribute a source version it won't be a problem but thats going to take a bit of time to get done correctly.
Plus precompiled also has other benefits of a faster installation.

Do let me know if I could use the system wide version.

Thanks.

**Comment by svenwoop** [comment]
This conflict is exactly the reason we did not do that. We could link against an old TBB version, which would make the code working also with newer TBB versions. However, we use some new TBB features that should best be enabled if the OS has a newer TBB version. That is why I think it is best if you compile Embree with the same TBB version that the Gentoo distro is using. In that case you could still have prebuild binaries, that you created yourself.
