### ISSUE TITLE
CMake cannot find custom TBB library

### ISSUE THREAD

**Issue by merwaaan** [embree/embree#308]
Hi,

We previously used Embree 3.6.2 and had to **upgrade to 3.12.1** to get new features.
However we now face build issues as **CMake has trouble finding our custom TBB** (static libraries in non-standard paths).

Previously, we just had to setup the build like this:
```
set(EMBREE_TASKING_SYSTEM "TBB")
set(EMBREE_TBB_ROOT "")
set(TBB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../tbb/include") # Our custom TBB headers
```

Source: 
> If your TBB library and headers are in non-default locations, just set TBB_ROOT to "". Then you can set the other TBB variables by hand. ([LINK](https://community.intel.com/t5/Intel-Embree-Ray-Tracing-Kernels/Custom-version-of-TBB-with-CMAKE/m-p/1079013/highlight/true#M576))

After the upgrade, we get this error:

```
-- Looking for TBB components tbb; ()
CMake Error at source/common/cmake/FindTBB.cmake:80 (message):  
Unable to find root directory    
Call Stack (most recent call first):   
source/common/cmake/FindTBB.cmake:450 (rk_tbb_error)
source/common/tasking/CMakeLists.txt:13 (FIND_PACKAGE)
```

**What is the recommended way to find a custom TBB now?**

Thank you

**Comment by jomeng** [comment]
Hi,

you can still set `EMBREE_TBB_ROOT` and `TBB_INCLUDE_DIR`, though the latter would only be required if your include directory is in a nonstandard location relative to the root.
For example, this works for me on 3.12.1:

```shell
cd /path/to/embree/source
mkdir build
cd build
cmake -DEMBREE_TBB_ROOT=/path/to/tbb ..
make
```

Could you please confirm that this does not work for you? I see that you seem to be setting variables in CMake, are you including Embree as a subproject? What's your TBB version based on?

Thank you!

**Comment by jomeng** [comment]
Also, are you able to send us exactly how you are building TBB? Please feel free to use embree_support@intel.com for this!

**Comment by merwaaan** [comment]
Hi @jomeng ,

I can confirm that the snippet you provided results in the same error.

Our custom TBB (2019 U6) is installed with a non-standard layout (for consistency with other dependencies) that looks like this:

- tbb
  - include
    - tbb
       - (headers here)
  - lib
     - Debug
       - tbb_static.lib
       - tbbmalloc_static.lib
     - Release
       - tbb_static.lib
       - tbbmalloc_static.lib

We build TBB with CMake. The only unusual bit is that we "install" files with the layout described above.
This worked well for all our dependencies until now and Embree had no issue with that in the past.

We downgraded to Embree 3.8.0 and it works with that version.

Thanks for your help

**Comment by jomeng** [comment]
Thanks for getting back to us. 
You should be able to set overrides for the individual libraries using these variables for now:

`tbb_LIBRARY_DEBUG`
`tbbmalloc_LIBRARY_DEBUG`
`tbb_LIBRARY_RELEASE`
`tbbmalloc_LIBRARY_RELEASE`

Please let us know if this works!

**Comment by merwaaan** [comment]
@jomeng Unfortunately, setting the paths to the individual libraries does not solve the issue.

Here's the full configuration, with the variables that you suggest:

```
set(EMBREE_TASKING_SYSTEM "TBB")
set(EMBREE_TBB_ROOT "")
set(TBB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../tbb/include") # Our custom TBB headers
set(tbb_LIBRARY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Debug/ttb_static.lib")
set(tbbmalloc_LIBRARY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Debug/ttbmalloc_static.lib")
set(tbb_LIBRARY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Release/ttb_static.lib")
set(tbbmalloc_LIBRARY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Release/ttbmalloc_static.lib")
```

And CMake's output:

```
-- Looking for TBB components tbb; () 
CMake Error at source/common/cmake/FindTBB.cmake:80 (message):
Unable to find root directory
Call Stack (most recent call first):
source/common/cmake/FindTBB.cmake:450 (rk_tbb_error)
source/common/tasking/CMakeLists.txt:13 (FIND_PACKAGE)
--
```

So it seems like TBB libraries in non-default locations do not work anymore with Embree.
I can confirm that **it worked at least until Embree 3.8.0**.

**Comment by jomeng** [comment]
Double checking differences between your version and what I tested I noticed that I had to set 
EMBREE_TBB_ROOT, as well. Leaving it blank did not work. 

So this works for me on Windows:

```
set(EMBREE_TASKING_SYSTEM "TBB")
set(EMBREE_TBB_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/../tbb")
set(TBB_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../tbb/include") # Our custom TBB headers
set(tbb_LIBRARY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Debug/ttb_static.lib")
set(tbbmalloc_LIBRARY_DEBUG "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Debug/ttbmalloc_static.lib")
set(tbb_LIBRARY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Release/ttb_static.lib")
set(tbbmalloc_LIBRARY_RELEASE "${CMAKE_CURRENT_SOURCE_DIR}../tbb/lib/Release/ttbmalloc_static.lib")
``` 
Please let us know if that works for you, as well. 
We'll be thinking about how we can make this simpler again.

**Comment by merwaaan** [comment]
@jomeng We tried setting TBB_ROOT as you suggested but unfortunately it still ends up with:

```
CMake Error at source/common/cmake/FindTBB.cmake:80 (message):
Unable to find root directory
```
Investigated a bit more and it seems that everything worked fine until commit 8f9e0532fc8ad8651bb8e1b1dff087990bd86419 in which the FindTBB script was heavily modified.

**Comment by jomeng** [comment]
I think we are at a point where we need to ask you for a complete reproducer. Could you please send us a minimal CMakeLists.txt file that reproduces this problem for you, along with the command lines required to build it from scratch?
