### ISSUE TITLE
wrong parameter input

### ISSUE THREAD

**Issue by limztudio** [embree/embree#309]
https://github.com/embree/embree/blob/69bd4c272f1ed608494f233ecfff3feec516880b/common/simd/vfloat4_sse2.h#L549

seems **_mm_extract_ps** returns as ***int***, but **_mm_cvtss_f32** parameter is ***__m128***.
is it okay to ignore **_mm_cvtss_f32** then cast to ***float*** from ***int***?

**Comment by svenwoop** [comment]
Indeed that is weird. The compiler would extract into an integer register, and then have to move the value back into a XMM register. That extract version getting a vfloat4 as input is actually not used in Embree. I removed that version and just use a standard shuffle plus __mm_cvtss_f32 now (essentially the version below that code line). Fix will be in next release.
BTW, just dropping the _mm_cvtss_f32 in the above line is definitely wrong.
