### ISSUE TITLE
Embree fails to build with MSVC when /arch:AVX or /arch:AVX is used

### ISSUE THREAD

**Issue by dictoon** [embree/embree#311]
I'm trying to build Embree master (as of today: commit 69bd4c272f1ed608494f233ecfff3feec516880b) with Visual Studio 2019, version 16.8.2.

Embree is a Git submodule of our project, and it gets build together with it. Here is our Embree configuration:

    set(EMBREE_TBB_ROOT "${TBB_DIR}/../")
    set(EMBREE_TUTORIALS OFF CACHE BOOL "" FORCE)
    set(EMBREE_ISPC_SUPPORT OFF CACHE BOOL "" FORCE)
    set(EMBREE_MAX_ISA "AVX2" CACHE STRING "" FORCE)
    set(EMBREE_RAY_MASK ON CACHE BOOL "" FORCE)
    set(EMBREE_BACKFACE_CULLING OFF CACHE BOOL "" FORCE)

When building everything (our project and Embree as a Git submodule) with `/arch:AVX` or `/arch:AVX2` (project-wide settings), Embree fails to build:

```
src\3rdparty\embree\common\simd\vboolf8_avx.h(168,102): error C2665: 'embree::popcnt': none of the 2 overloads could convert all the argument types (compiling source file \src\3rdparty\embree\common\sys\sysinfo.cpp)
```

The cause seems to be that some of Embree's libraries (such as those in `common`) are built without the `__SSE4_2__` preprocessor symbol (among several others).

Is building Embree itself with `/arch:AVX` or `/arch:AVX2` supported?

**Comment by svenwoop** [comment]
You should not set the /arch:AVX for Embree. When configuring Embree with EMBREE_MAX_ISA=AVX2 it will automatically compile with proper flags set. Could you please try again without forcing ISA flags for Embree compile.

**Comment by dictoon** [comment]
Thanks Sven for the quick answer. It makes sense, but then I guess my next questions are the following:

1. Why does Embree specifically require _not_ to be built with AVX/AVX2 code gen?

2. Since we're building Embree as a Git submodule, and we _do_ want to build the rest of our project with AVX or AVX2 code gen, can we safely mix static libraries built with different code gen options?

**Comment by svenwoop** [comment]
If you set EMBREE_MAX_ISA=AVX2, Embree will internally build some .cpp files for SSE2, AVX, and AVX2 ISA. If you overwrite the compile flags to enforce some ISA then this just does not work anymore.
You can just link the Embree static libraries (in increasing ISA order!) to your app without issues. Embree will take care of selecting the correct symbols for the ISA of the CPU that the program got started.

**Comment by dictoon** [comment]
Thanks for your answer Sven.

We'll have to figure out a way to continue building Embree without forcing AVX/AVX2 gen, yet to build the rest of our application with AVX/AVX2. Not yet sure how to do that given that in our case Embree is a Git submodule and it built together with the application.

Another tangential question: we only link with `embree3.lib`, it doesn't appear that we link with any of `embree_sse42.lib`, `embree_avx.lib` or `embree_avx2.lib`, but based on your comment we should? As far as I can tell, Embree uses the AVX backend, at least to build the BVHs, so we're good?

**Comment by svenwoop** [comment]
If you link against Embree as a shared library (DLL), then just linking against embree3.lib is sufficient. If you build Embree as a static library then you have to link against all .lib files in increasing ISA order. I would strongly recommend using shared libraries.

**Comment by dictoon** [comment]
Ok, that clear things up, we use Embree as a shared library. Thanks for the clarification!
