### ISSUE TITLE
get depth value when loading a simple OBJ file into viewer

### ISSUE THREAD

**Issue by fangchuan** [embree/embree#313]
Hi all, I'm new to embree. I follow the tutorial of  Viewer and try to load a mesh file in my local path. The tutorial program viewer render color value of mesh face in default, which can be found in source code:
https://github.com/embree/embree/blob/ae029e2ff83bebbbe8742c88aba5b0521aba1a23/tutorials/viewer/viewer_device.cpp#L239-L311
However, I want to get depth value  of the mesh on each pixel, so I adjust the line 311 from 
https://github.com/embree/embree/blob/ae029e2ff83bebbbe8742c88aba5b0521aba1a23/tutorials/viewer/viewer_device.cpp#L311
into 
![image](https://user-images.githubusercontent.com/8519718/105628932-e8d18b80-5e7a-11eb-9eba-ca7d07ee13d8.png).
I thougth  **the tfar element of Ray struct represent depth value** of mesh in current camera pose, is that right? Anyway, I call this solution based on embree **embree_depth_render**.

Besides, I also have finish a depth render of mesh based on OpenGL, called **opengl_depth_render**, which must need a real screen connected with computer, make it difficult to deploy our code in server.

Then I pass the same camera pose parameters: from, to, up, fov, image_size and so forth, but I find the depth image generate by **embree_depth_render**(first image) is different from o**pengl_depth_render** (second image)
![image](https://user-images.githubusercontent.com/8519718/105629237-c2aceb00-5e7c-11eb-8ab9-262b340b749b.png)
![image](https://user-images.githubusercontent.com/8519718/105629247-d0fb0700-5e7c-11eb-8004-dcec59cc50f6.png)

They cannot be aligned perfectly, and it seems 0_0_embree.png is brighter than the other one, which means depth value generated by embree is greate than the openGL.

I'm confused and cannot figure out the problem, so I turn to you for your help @svenwoop @cbenthin @atafra @johguenther . 
I'm looking forward for your reply, thanks in advance!

**Comment by svenwoop** [comment]
The Embree viewer normalizes the ray direction, while a rasterizer does not do this. If you change

Ray ray(Vec3fa(camera.xfm.p), Vec3fa(normalize(x*camera.xfm.l.vx + y*camera.xfm.l.vy + camera.xfm.l.vz)), 0.0f, inf, RandomSampler_get1D(sampler));

to 

Ray ray(Vec3fa(camera.xfm.p), Vec3fa(x*camera.xfm.l.vx + y*camera.xfm.l.vy + camera.xfm.l.vz), 0.0f, inf, RandomSampler_get1D(sampler));

then it should work.

**Comment by fangchuan** [comment]
I tried, but it doesnt help
