### ISSUE TITLE
Many tests fail with ios_base::clear: unspecified iostream_category error

### ISSUE THREAD

**Issue by danfe** [embree/embree#317]
After successful build, running `ctest` shows that most tests fail for some reason.  The logs show that when programs are executed as e.g. `user_geometry --compare none/reference/user_geometry.tga --mode stream --incoherent`, they fail with `Error: ios_base::clear: unspecified iostream_category error` exception.  When run without arguments, they work fine (display an X11 window with apparently correct contents).

**Comment by svenwoop** [comment]
That error message is a little misleading, it is related to that comparison image file not existing. We do not publish our internal test models repository, thus you cannot perform testing with ctest. If you want to test your Embree build just run ./verify, this performs the most important testing.
