### ISSUE TITLE
Correct and efficient way to terminate ray traversal from intersection filter?

### ISSUE THREAD

**Issue by dictoon** [embree/embree#318]
An intersection filter should be able to decide to terminate traversal. One typical situation where this is useful is when a shadow ray encounters an opaque occluder.

Currently, we terminate traversal with the following code:

    RTCRayN_tfar(args->ray, 1, 0) = -std::numeric_limits<float>::infinity();

Is this the correct and most efficient way to do so? I think the relevant paragraph from the API documentation is the following one, but it doesn't explicitly mention anything about terminating traversal (beside saying that it's legal to decrease `tfar`):

> The filter callback function has the task to check for each valid ray whether it wants to accept or reject the corresponding hit. To reject a hit, the filter callback function just has to write 0 to the integer valid mask of the corresponding ray. To accept the hit, it just has to leave the valid mask set to -1. The filter function is further allowed to change the hit and decrease the tfar value of the ray but it should not modify other ray data nor any inactive components of the ray or hit.

Additionally, we're not expecting any performance penalty by using `-std::numeric_limits<float>::infinity()` because on x64 architectures, SSE handles these values at full speed. Is this assumption correct? What about other architectures, in particular ARM (e.g. Apple M1)?

Finally, as a bonus question, could you confirm that the proper way for an intersection filters to ignore a specific intersection and continue traversal is to do this:

    args->valid[0] = 0;

Do I understand correctly that this doesn't _disable_ the ray, and that other intersections along the ray will be found and processed by the intersection filter?

**Comment by svenwoop** [comment]
What you do is a proper way of terminating a ray traced with rtcIntersect-type calls. If you are shooting shadow rays, you should use rtcOccluded calls, and then you can just accept a hit, which will terminate traversal.

Correct, args->valid[0] = 0 rejects a hit and will continue traversal. This will not disable the ray.
