### ISSUE TITLE
Download link broken?

### ISSUE THREAD

**Issue by Sentient07** [embree/embree#324]
Hello,

I'm trying to download the gz installation file for linux and the [download link](https://github.com/embree/embree/releases/download/v3.13.0-alpha.0/embree-3.13.0-alpha.0.x86_64.linux.tar.gz) seems broken. Can you please provide an alternative way to download the package? Thanks!

**Comment by svenwoop** [comment]
https://github.com/embree/embree/releases/tag/v3.13.0

Will fix webpage soon.
