### ISSUE TITLE
AVX2 instance_intersector build fails with intel 19.1.1 compiler

### ISSUE THREAD

**Issue by semeraro** [embree/embree#326]
I encountered this while building embree 3.6.1 with the intel compiler version 19.1.1.  There seems to be a problem building the AVX2 business. Am I missing a flag or something?

Building CXX object kernels/CMakeFiles/embree_avx2.dir/__/geometry/instance_intersector.cpp.avx2.cpp.o
In file included from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/../common/../../common/sys/mutex.h(20),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/../common/../../common/sys/thread.h(20),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/../common/default.h(21),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/primitive.h(19),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/instance.h(19),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/instance_intersector.h(19),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/instance_intersector.cpp(17),
                 from /work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/build/geometry/instance_intersector.cpp.avx2.cpp(1):
/work2/01197/semeraro/stampede2/Projects/galaxy/third-party/embree/kernels/geometry/../common/../../common/sys/intrinsics.h(237): error #165: too few arguments in function call
      return _tzcnt_u32(v);

**Comment by semeraro** [comment]
Actually this isnt something you guys should have to deal with.

**Comment by cbenthin** [comment]
That's likely a compiler (header) bug, as _tzcnt_u32 does only take a single argument. Does this happen with the latest Embree and the latest Intel compiler?

**Comment by semeraro** [comment]
Im building embree 3.6.1 with Intel 19.1.1. Im off the reservation a bit as I am building static libs. My cxxflags were off and the header file did have to be modified a bit to make it work. I got help from a local embree build expert. To fix this we commented out the section in the common/cmake/cmake.intel file that sets -fPIE and -ftls-model=local-dynamic. we also made the following change to the common/sys/intrinsics.h 
`diff --git a/common/sys/intrinsics.h b/common/sys/intrinsics.h
index 5ec477cfc..f1c5942ef 100644
--- a/common/sys/intrinsics.h
+++ b/common/sys/intrinsics.h
@@ -24,7 +24,7 @@

 #include <immintrin.h>

-#if defined(__BMI__) && defined(__GNUC__)
+#if defined(__BMI__) && defined(__GNUC__) && !defined(__INTEL_COMPILER)
   #if !defined(_tzcnt_u32)
     #define _tzcnt_u32 __tzcnt_u32
   #endif`
   I think we went off the reservation a bit with what we were doing. These minor changes have fixed the problem.
