### ISSUE TITLE
rtcThreadLocalAlloc taking much time

### ISSUE THREAD

**Issue by nbonneel** [embree/embree#329]
While profiling my path tracer, I realized that by far the most compute intensive function is rtcThreadLocalAlloc (taking about 30-40% of the total render time, excluding BVH construction, but including all shading with subsurface scattering, spherical light sources etc.). I am quite surprised as I believed this function was mostly used for BVH construction, but the call graph indicates it is used by all the intersection routines I use (rtcIntersect1, rtcOccluded1 and rtcIntersectNM).

I am using two levels of BVH: I have a scene that consists of instanced scenes. The build quality is RTC_BUILD_QUALITY_HIGH at both levels but that doesn't change this issue. I use the flag RTC_SCENE_FLAG_CONTEXT_FILTER_FUNCTION, and one of my contexts has a filter (though even without this filter, it doesn't change). I do **not** use RTC_SCENE_FLAG_COMPACT, and my scenes are not complex at all (tested with about 320k triangles, the scene is static). I only have triangular meshes. I compile with MSVC 2017 on Windows, and run on a ThreadRipper 2990WX. I profile with Luke Stackwalker and VerySleepy (sampling profilers, code compiled with full optimization).

Any idea ?
Thanks!

**Comment by cbenthin** [comment]
So rtcThreadLocalAlloc is actually only used by the external BVH builder API to provide thread local memory allocation. Do you use the external BVH builder API? If not something strange in the profiler's symbol resolution is going on. Btw: Do you profile just a static scene? If yes then there should be no BVH builder activity at all. Maybe profile with less optimization and or a different tool?

**Comment by nbonneel** [comment]
Thanks ! Yes, the scene is static. I'll try on another system. Here, 2 profilers tell me the same thing, so I think I'll need to try with other compilers or OS.

**Comment by nbonneel** [comment]
ok, I don't know what I did with my dll and pdb files, but upon regenerating them, I do not get this behavior anymore and the most time consuming function is now BVHNIntersector1<...>::occluded and then BVHNIntersector1<...>::intersect, which makes much more sense.
Thanks - case closed!
