### ISSUE TITLE
some impressions regarding version 2.5

### ISSUE THREAD

**Issue by ov** [embree/embree#33]
Hi guys, there are no code-related issues below, just the installation and integration related ones.

- (Windows) please bring back the ZIP files, installers are pain and I believe that in most cases the DLLs and headers end up somewhere in the project subfolder, controlled by VCS. Let us simply unpack the new version there;
- (Windows) please, bundle a proper TBB dlls, or provide at least an URL where to get them. I had to Google for them and hope the one I've downloaded will work fine in all the possible scenarios;
- (Mac) both libtbb.dylib and libtbbmalloc.dylib that you provided require `mac64/libcilkrts.5.dylib` which is not provided, so the files cannot be loaded. I had to replace both files with the other ones from the TBB for OSX I've downloaded, but again - will they work just fine on all the CPUs? Not sure.
- (Mac) It would be really nice to see the file names instead of full paths to TBB dylibs, when you do `otool -L libembree.2.5.0.dylib` - the reason is that all three files will most likely end up in the same folder of a bundle and will hardly be installed in the `/opt/` folder.

Implementing the above will definitely save some time and nerves to the library users.

Thanks for the great library!

**Comment by svenwoop** [comment]
Hi Vitaly,

1) The Windows installer just unpacks the files into the Program Files\Intel\Embree 2.5.0 Folder. We will additionally provide ZIP files again in the next release.

2) The proper Windows TBB Dlls are provided in the Embree 2.5.0\bin folder if you also selected to install the tutorials.

3) We also added the libtbb.dylib from the TBB webpage. However, it looks like there are two versions. I assume you used the libraries in the tbb\lib\libc++ folder? I changed the v2.5.0 ZIP file to contain these libraries now, which makes anyway more sense at libembree.dylib also links again libc++.

4) I also fixed this issue in the v2.5.0 ZIP file for MacOSX.

Sven

**Comment by ov** [comment]
Thanks very much, it looks like all the issues are now fixed. Any chance you re-release version 2.5?

**Comment by svenwoop** [comment]
I added the fixes to the MacOSX release. Just download again and everything should work.

**Comment by ov** [comment]
Got it, thanks :)
