### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by bingkangzhang** [embree/embree#333]
Hi，I'm building open3d from source on mac.But when i compile according the script, it fails and throws the following error:
... ...
[ 32%] Built target 3rdparty_qhullcpp
/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/libpng/src/ext_libpng/arm/arm_init.c:49:4: error: "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"

error "PNG_ARM_NEON_FILE undefined: no support for run-time ARM NEON checks"
^
/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/libpng/src/ext_libpng/arm/arm_init.c:86:27: error: implicit declaration of function 'png_have_neon' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
no_neon = !png_have_neon(pp);
^
2 errors generated.
make[5]: *** [CMakeFiles/png_static.dir/arm/arm_init.c.o] Error 1
make[4]: *** [CMakeFiles/png_static.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [libpng/src/ext_libpng-stamp/ext_libpng-build] Error 2
make[1]: *** [CMakeFiles/ext_libpng.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 34%] Built target glfw
CMake Error at CMakeLists.txt:374 (MESSAGE):
Using Embree as static library is not supported with AppleClang >= 9.0 when
multiple ISAs are selected. Please either build a shared library or enable
only one ISA.

-- Configuring incomplete, errors occurred!
See also "/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/embree/src/ext_embree-build/CMakeFiles/CMakeOutput.log".
See also "/Users/bingkang.zhang/iOSProjects/Open3D-Build/Open3D/build/embree/src/ext_embree-build/CMakeFiles/CMakeError.log".
make[2]: *** [embree/src/ext_embree-stamp/ext_embree-configure] Error 1
make[1]: *** [CMakeFiles/ext_embree.dir/all] Error 2
make: *** [all] Error 2

what can i do now to complete the build?

**Comment by cbenthin** [comment]
This seems to be a problem of the Open3D build environment for MAC so it would be best to contact the Open3D team for support. I'm not familiar with Open3D environment but if there's a build option to build Embree as a shared library instead of a static library one should do this.

**Comment by bingkangzhang** [comment]
> This seems to be a problem of the Open3D build environment for MAC so it would be best to contact the Open3D team for support. I'm not familiar with Open3D environment but if there's a build option to build Embree as a shared library instead of a static library one should do this.

okay，thanks a lot.
