### ISSUE TITLE
Embree crashes when building under VS2013

### ISSUE THREAD

**Issue by GrahamClemo** [embree/embree#34]
Hi, when building Embree 2.5.0 under Visual Studio 2013 and running the verify sample I get an access violation error reading address 0xFFFFffffFFFFffff; the stacktrace is
>	embree.dll!std::allocator<embree::FastAllocator::ThreadLocal2 * __ptr64>::construct(embree::FastAllocator::ThreadLocal2 * * _Ptr, embree::FastAllocator::ThreadLocal2 * const & _Val) Line 593	C++
 	embree.dll!std::allocator_traits<std::allocator<embree::FastAllocator::ThreadLocal2 * __ptr64> >::construct<embree::FastAllocator::ThreadLocal2 * __ptr64,embree::FastAllocator::ThreadLocal2 * __ptr64 const & __ptr64>(std::allocator<embree::FastAllocator::ThreadLocal2 *> & _Al, embree::FastAllocator::ThreadLocal2 * * _Ptr, embree::FastAllocator::ThreadLocal2 * const & <_Args_0>) Line 724	C++
 	embree.dll!std::_Wrap_alloc<std::allocator<embree::FastAllocator::ThreadLocal2 * __ptr64> >::construct<embree::FastAllocator::ThreadLocal2 * __ptr64,embree::FastAllocator::ThreadLocal2 * __ptr64 const & __ptr64>(embree::FastAllocator::ThreadLocal2 * * _Ptr, embree::FastAllocator::ThreadLocal2 * const & <_Args_0>) Line 873	C++
 	embree.dll!std::vector<embree::FastAllocator::ThreadLocal2 * __ptr64,std::allocator<embree::FastAllocator::ThreadLocal2 * __ptr64> >::push_back(embree::FastAllocator::ThreadLocal2 * const & _Val) Line 1261	C++
 	embree.dll!embree::ThreadLocalData<embree::FastAllocator::ThreadLocal2>::get() Line 101	C++
 	embree.dll!embree::FastAllocator::threadLocal2() Line 187	C++
 	embree.dll!embree::avx::CreateAlloc::operator()() Line 47	C++
 	embree.dll!embree::avx::GeneralBVHBuilder<embree::avx::GeneralBuildRecord<embree::range<unsigned __int64>,embree::avx::BinSplit<32> >,embree::avx::HeuristicArrayBinningSAH<embree::PrimRef,32>,int,embree::FastAllocator::ThreadLocal2 * __ptr64,embree::avx::CreateAlloc,embree::avx::CreateBVH8Node,int <lambda>(int, int *, unsigned __int64),embree::avx::CreateLeaf<embree::Triangle4>,void <lambda>(unsigned __int64) >::recurse(embree::avx::GeneralBuildRecord<embree::range<unsigned __int64>,embree::avx::BinSplit<32> > & current, embree::FastAllocator::ThreadLocal2 * alloc, bool toplevel) Line 165	C++
 	embree.dll!embree::avx::GeneralBVHBuilder<embree::avx::GeneralBuildRecord<embree::range<unsigned __int64>,embree::avx::BinSplit<32> >,embree::avx::HeuristicArrayBinningSAH<embree::PrimRef,32>,int,embree::FastAllocator::ThreadLocal2 * __ptr64,embree::avx::CreateAlloc,embree::avx::CreateBVH8Node,int <lambda>(int, int *, unsigned __int64),embree::avx::CreateLeaf<embree::Triangle4>,void <lambda>(unsigned __int64) >::operator()(embree::avx::GeneralBuildRecord<embree::range<unsigned __int64>,embree::avx::BinSplit<32> > & record) Line 255	C++
 	embree.dll!embree::avx::BVHBuilderBinnedSAH::build_reduce<embree::BVH8::NodeRef,embree::avx::CreateAlloc,int,embree::avx::CreateBVH8Node,int <lambda>(int, int *, unsigned __int64),embree::avx::CreateLeaf<embree::Triangle4>,void <lambda>(unsigned __int64) >(embree::BVH8::NodeRef & root, embree::avx::CreateAlloc createAlloc, const int & identity, embree::avx::CreateBVH8Node createNode, embree::avx::BVHBuilderBinnedSAH::build::__l3::int <lambda>(int, int *, unsigned __int64) updateNode, embree::avx::CreateLeaf<embree::Triangle4> createLeaf, embree::avx::BVH8BuilderSAH<embree::TriangleMesh,embree::Triangle4>::build::__l10::void <lambda>(unsigned __int64) progressMonitor, embree::PrimRef * prims, const embree::avx::PrimInfo & pinfo, const unsigned __int64 branchingFactor, const unsigned __int64 maxDepth, const unsigned __int64 blockSize, const unsigned __int64 minLeafSize, const unsigned __int64 maxLeafSize, const float travCost, const float intCost) Line 371	C++
 	embree.dll!embree::avx::BVHBuilderBinnedSAH::build<embree::BVH8::NodeRef,embree::avx::CreateAlloc,embree::avx::CreateBVH8Node,embree::avx::CreateLeaf<embree::Triangle4>,void <lambda>(unsigned __int64) >(embree::BVH8::NodeRef & root, embree::avx::CreateAlloc createAlloc, embree::avx::CreateBVH8Node createNode, embree::avx::CreateLeaf<embree::Triangle4> createLeaf, embree::avx::BVH8BuilderSAH<embree::TriangleMesh,embree::Triangle4>::build::__l10::void <lambda>(unsigned __int64) progressMonitor, embree::PrimRef * prims, const embree::avx::PrimInfo & pinfo, const unsigned __int64 branchingFactor, const unsigned __int64 maxDepth, const unsigned __int64 blockSize, const unsigned __int64 minLeafSize, const unsigned __int64 maxLeafSize, const float travCost, const float intCost) Line 317	C++
 	embree.dll!embree::avx::BVH8BuilderSAH<embree::TriangleMesh,embree::Triangle4>::build(unsigned __int64 __formal, unsigned __int64 __formal) Line 150	C++
 	embree.dll!embree::AccelInstance::build(unsigned __int64 threadIndex, unsigned __int64 threadCount) Line 42	C++
 	embree.dll!embree::AccelN::build(unsigned __int64 threadIndex, unsigned __int64 threadCount) Line 142	C++
 	embree.dll!embree::Scene::build_task() Line 359	C++
 	embree.dll!embree::Scene::build::__l21::<lambda>() Line 546	C++
 	embree.dll!tbb::internal::function_task<void <lambda>(void) >::execute() Line 895	C++
 	tbb.dll!000007fef92c544e()	Unknown
 	embree.dll!tbb::task::wait_for_all() Line 733	C++
 	embree.dll!tbb::internal::task_group_base::wait() Line 140	C++
 	embree.dll!embree::Scene::build(unsigned __int64 threadIndex, unsigned __int64 threadCount) Line 549	C++
 	embree.dll!rtcCommit(__RTCScene * scene) Line 637	C++
 	verify.exe!embree::rtcore_static_scene() Line 1097	C++
 	verify.exe!embree::main(int argc, char * * argv) Line 3011	C++
 	verify.exe!main(int argc, char * * argv) Line 3126	C++
 	[External Code]	

I am using Embree 2.5.0
TBB 4.3.2015.301
Intel(r) SPMD Program Compiler (ispc), 1.8.1 (build  @ Dec 31 2014, LLVM 3.5)
Microsoft Visual Studio Community 2013 Version 12.0.31101.00 Update 4, under Windows 7.
I copied tbb into the embree folder and renamed it to tbb, then used CMake 3.2.1 to generate the build script for Visual Studio 12 2013 Win64, the only change I made was to specify the location of ISPC. Then I built the ALL_BUILD for Debug configuration, copied the TBB DLLs from tbb/bin/intel64/vc12 into the build's Debug folder (tbb.dll, tbb_debug.dll, tbb_preview.dll, tbb_preview_debug.dll, tbbmalloc.dll, tbbmalloc_debug.dll, tbbmalloc_proxy.dll, tbbmalloc_proxy_debug.dll) and ran verify from the VS IDE.
Thanks.

**Comment by svenwoop** [comment]
Thanks for reporting this. The issue only happened in Debug mode. I fixed the issue in the v2.5.0 branch.
