### ISSUE TITLE
Combining Embree 3.13.2 with ISPC 1.16.1 generates compiler warnings

### ISSUE THREAD

**Issue by mikemccarty-vertex** [embree/embree#340]
E.g. 
```
/usr/local/include/embree3/rtcore_scene.isph:145:34: Warning: Typecasting to type "/*unbound*/ 
        struct RTCRayHitN * /*unbound*/" (variability not specified) from "uniform" type "varying struct 
        RTCRayHit * uniform" results in "uniform" variability. 
        In the context of function argument it may lead to unexpected behavior. Casting to "/*unbound*/ struct 
        RTCRayHitN * uniform" is recommended. 
  rtcIntersectNM(scene, context, (struct RTCRayHitN*)rayhit, sizeof(varying float)/4, M, byteStride);
       /usr/local/include/embree3/rtcore_scene.isph:145:34: Warning: Typecasting to type "/*unbound*/ 
        struct RTCRayHitN * /*unbound*/" (variability not specified) from "uniform" type "varying struct 
        RTCRayHit * uniform" results in "uniform" variability. 
        In the context of function argument it may lead to unexpected behavior. Casting to "/*unbound*/ struct 
        RTCRayHitN * uniform" is recommended. 
           rtc I n t e r s e c t N M (  s c e n^e^,^ ^c^o^n^t^e^x^t, ^(^s^t^r^u^c^t^ ^R^T^C^R^a^y^H^i
tN
*)rayhit, sizeof(varying float)/4, M, byteStride);
```

I have no idea if these warnings are meaningful or not.

**Comment by svenwoop** [comment]
I do not see that warning when compiling Embree locally. I added a potential fix to devel branch in github, could you please try if that fixes the warning completely?

**Comment by mikemccarty-vertex** [comment]
Here's a simplification of it:  https://ispc.godbolt.org/z/W736xe3dd

**Comment by mikemccarty-vertex** [comment]
The devel branch version seems to be better:  https://ispc.godbolt.org/z/djhGPGqEG

**Comment by svenwoop** [comment]
But is this really latest devel branch? It should have (struct RTCRayHitN* uniform) and not (struct RTCRayHitN*) in the code.

**Comment by mikemccarty-vertex** [comment]
In the second link (https://ispc.godbolt.org/z/djhGPGqEG), the function named `rtcIntersectVM_devel()` is a cut-n-paste of your devel branch fix.  I left the original in there for comparison.

**Comment by svenwoop** [comment]
Ok thus warning is fixed. I will close the issue. This fix will be in the next release, or just use the devel branch for now.

**Comment by mikemccarty-vertex** [comment]
Is it a significant change or is the compiler just being pedantic?

**Comment by svenwoop** [comment]
Compiler is just pedantic. We use that rtcIntersectVM function at some places in tutorials without issues. Thus generated code is correct also without the fix.
