### ISSUE TITLE
intrinsic bit ops are clearly wrong: "v | (v << i)" to set a bit

### ISSUE THREAD

**Issue by jorgbrown** [embree/embree#343]
Around line 386 of common/sys/intrinsics.h, I see this:

  __forceinline size_t btc(size_t v, size_t i) {
#if defined(__X86_ASM__)
    size_t r = 0; asm ("btc %1,%0" : "=r"(r) : "r"(i), "0"(v) : "flags" ); return r;
#else
    return (v ^ (1 << i));
#endif
  }
  
  __forceinline size_t bts(size_t v, size_t i) {
#if defined(__X86_ASM__)
    size_t r = 0; asm ("bts %1,%0" : "=r"(r) : "r"(i), "0"(v) : "flags"); return r;
#else
    return (v | (v << i));
#endif
  }
  
  The first implementation makes sense "v ^ (1 << i)"
  
  The second implementation makes no sense "v | (v << i)".  Surely that should be "v | (1 << i)" similar to the previous routine.

**Comment by svenwoop** [comment]
This for reporting, this will be fixed in next release.
