### ISSUE TITLE
Instance disappears with motion blur, time ranges and rtcIntersect1M

### ISSUE THREAD

**Issue by pborsutzki** [embree/embree#349]
Hi,

when building a motion blur BVH using quaternions, setting the time range of an instance via `rtcSetGeometryTimeRange` to something smaller than the default range, e.g. to `[0.0, 0.75]`, while using `rtcIntersect1M` with more than 1 ray, the affected instance disappears for good, regardless if the time of the rays matches the visible range or not.

I modified the quaternion motion blur tutorial to reproduce the problem, find [the patch based on Embree 3.13.2 attached](https://github.com/embree/embree/files/7604787/0001-Reproducer-for-motion-blur-problem-with-rtcIntersect.zip). The problem disappears when either setting `motion bvh = off`, setting `start <= 0.0` and `end >= 1.0` or setting `num rays = 1`.

Not shown in this reproducer is that the problem also disappears as soon as there are at least two motion blur enabled instances in the BVH.

Can you please have a look into this? Thanks!

**Comment by freibold** [comment]
Hi,

many thanks for reporting this special case bug! It will be fixed in the next release. In the meantime you can use this
[patch](https://github.com/embree/embree/files/7636567/0001-fix-empty-child-at-beginning-of-child-list.zip). Can you please verify the fix and close the issue?

Thanks!

**Comment by pborsutzki** [comment]
Hi,

many thanks for looking into this! I can confirm that your fix works.

Thanks!
