### ISSUE TITLE
Error in documentation of rtcSetSharedGeometryBuffer

### ISSUE THREAD

**Issue by eggersa** [embree/embree#350]
The paragraph [rtcSetSharedGeometryBuffer](https://github.com/embree/embree#rtcsetsharedgeometrybuffer) says: 

> ...The start address (byteOffset argument) and stride (byteStride argument) must be both aligned to 4 bytes; otherwise the **rtcSetGeometryBuffer** function will fail... 

I assume it should be rtcSet**Shared**GeometryBuffer?

**Comment by svenwoop** [comment]
Yes this is a typo and should be rtcSetSharedGeometryBuffer. We fix this in next release.
