### ISSUE TITLE
Example for tracing ray packets

### ISSUE THREAD

**Issue by eggersa** [embree/embree#356]
The documentation at [Ray Queries](https://github.com/embree/embree#ray-queries) says

>  See tutorial Triangle Geometry for a complete example of how to trace single rays and **ray packets**.

Unfortunately, the Triangle Geometry example does not contain an example of how to query ray packets, nor any other tutorial (at least I didn't find one). Can someone provide me with a simple example of to do a query with ray packets?

Not actually part of the issue, but are they even beneficial for non coherent rays?

**Comment by svenwoop** [comment]
Indeed the triangle geometry tutorial has an ISPC version, which essentially uses ray packets. To use ray packets you just setup the RTCRayHit4 structure and use rtcIntersect4. An example of how to setup these structures is in tutorials/verify/rtcore_helpers.h (look for rtcIntersect4 call). The input buffers have to be properly aligned (e.g. 16 byte alignment for rtcIntersect4 call).

You will only get a benefit for coherent rays (e.g. primary rays). Do not expect a performance benefit for incoherent rays when using ray packets.

**Comment by eggersa** [comment]
Thank you so much!
