### ISSUE TITLE
Is it possible to expose a "thread ID" in RTCCollideFunc?

### ISSUE THREAD

**Issue by ChengduLittleA** [embree/embree#358]
Hi there developers, is it possible to have a "thread ID" in RTCCollideFunc? If so then we are able to record collision result per thread thus not locking access to result data, which could make make it run much smoother?

**Comment by svenwoop** [comment]
You can use thread local storage to assign an ID to each thread. Alternatively, if you use TBB you can use current_thread_index function to get a thread index, see embree/common/taskschedulertbb.h for an example.
