### ISSUE TITLE
Support compiling to WebAssembly using Emscripten

### ISSUE THREAD

**Issue by estollnitz** [embree/embree#359]
When compiling to WebAssembly (WASM) using [Emscripten](https://emscripten.org/), several problems appear. Some are CMake configuration issues, others are limitations in WASM's support for [threads](https://emscripten.org/docs/porting/pthreads.html) or [SIMD intrinsics](https://emscripten.org/docs/porting/simd.html), and still others relate to assumptions Embree code makes about sizes of basic types like `size_t` that don't hold in WASM.

I will open a PR with proposed changes.

**Comment by unicomp21** [comment]
@estollnitz any chance there is a dockerfile which will do the wasm build of embree?

**Comment by estollnitz** [comment]
Not that I know of.

Eric
________________________________

**Comment by unicomp21** [comment]
so just follow the cmake instructions w/ emscripten installed, and the build "just works" @estollnitz ?

**Comment by estollnitz** [comment]
Please see the PR, where I listed the build instructions along with a description of the changes I made and the extent to which I tested the code.

https://github.com/embree/embree/pull/365
________________________________

**Comment by unicomp21** [comment]
thanks!
