### ISSUE TITLE
CMake generation fails in projects that already depend on TBB

### ISSUE THREAD

**Issue by merwaaan** [embree/embree#360]
Hi,

The CMake import script for embree has this line that breaks the generation when the TBB::tbb target already exists.

https://github.com/embree/embree/blob/d7157470e089098b9c7323f608835ed50453e606/common/cmake/embree-config.cmake#L58

This happens to us because our project directly relies on TBB.

**Shouldn't the import script use `find_package(TBB REQUIRED)` instead?**
It's the responsibility of TBB's import script (found via find_package) to define such target, not embree's.

This would also fix the fact that only the SHARED version of TBB is fetched with the current code (we use a static build of TBB).

I can propose a PR with that change.

**Comment by svenwoop** [comment]
Could you please send a PR that works for you.

**Comment by svenwoop** [comment]
Please have a look at latest devel branch. I just removed that problematic lines. If you make find_library(TBB) in your project and link against TBB then it works now.
The static Embree target does not automatically depend on the found TBB, even when I add some find_library in the configure file. Not sure why that is, and why static lib handling is so different in cmake then dynamic libs.

**Comment by merwaaan** [comment]
Hi @svenwoop 
The error about the target being already defined disappeared with the latest devel commits.

However, there's still an issue when using our own TBB:

```bash
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19043.
CMake Error at _deps/embree/import.cmake:11 (find_package):
  Found package configuration file:

    [...]/_deps/embree/lib/cmake/embree-3.13.3/embree-config.cmake

  but it set embree_FOUND to FALSE so package "embree" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing: TBB
```

It seems to be caused by the generated code that checks that all targets have been defined, at the end of `tasking-targets.cmake`.

```cmake
# Make sure the targets which have been exported in some other
# export set exist.
unset(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets)
foreach(_target "TBB" )
  if(NOT TARGET "${_target}" )
    set(${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets "${${CMAKE_FIND_PACKAGE_NAME}_NOT_FOUND_MESSAGE_targets} ${_target}")
  endif()
endforeach()
```

It specifically looks for the "TBB" name because it has been defined as such in the `add_library(TBB INTERFACE)` lines of `FindTBB.cmake` **whereas the "official" export script provided by TBB defines the target as "TBB::tbb"**. 

Manually changing "TBB" to "TBB::tbb" in the generated file fixes the problem but a real fix would be to change the target name in the FindTBB script provided by Embree.
(I'm not sure about the consequences of doing so when using the TBB provided by Embree though)

---

In the meantime, we made it work in our project by creating an intermediary target to match Embree's expectations, but it's not ideal:

```
find_package(TBB REQUIRED)

# Create an TBB interface to match that dependency's naming in Embree
add_library(TBB INTERFACE)
target_link_libraries(TBB INTERFACE TBB::tbb)

set(embree_DIR "${CMAKE_CURRENT_LIST_DIR}/lib/cmake/embree-3.13.3")
find_package(embree REQUIRED)
```

**Comment by svenwoop** [comment]
Which TBB version are you using? In embree/common/tasking/CMakeLists.txt we either use TBB's find script when provided, or use our own find script for old TBB versions. Maybe your TBB version provides a configuration to be found, but we do not use it?

**Comment by merwaaan** [comment]
We use oneTBB 2021.5.0.

It provides a CMake import script that we use before configuring embree (because our project depends on TBB, even without embree).

```
set(TBB_DIR "${CMAKE_CURRENT_LIST_DIR}/../onetbb/lib/cmake/TBB")
find_package(TBB REQUIRED)

# after that, the TBB::tbb target is defined
```

 The issue with Embree seems to be that the FindTBB script doesn't use the same names as their official CMake export.

**Comment by svenwoop** [comment]
Just tried and this works for me with that version. I believe Embree might in your setup not see the TBB_DIR and thus finds an older (e.g. the system) TBB version, which causes it to fall back to its FindEmbree script.

**Comment by merwaaan** [comment]
> I believe Embree might in your setup not see the TBB_DIR and thus finds an older (e.g. the system) TBB version, which causes it to fall back to its FindEmbree script.

We have a single TBB version on our system and the CMake logs confirm that it has been found.

I found that using `find_package(TBB)` from our project instead of relying on `EMBREE_TBB_ROOT` works, as it bypasses the code that looks for TBB in `common/tasking/CMakeLists.txt` and causes issues (it leads to a "TBB" target being created instead of "TBB::tbb").

---

There's still an issue though @svenwoop: after this step, embree attempts to install TBB unconditionally

https://github.com/embree/embree/blob/22683d839f972aaec08ca670af00f6a3dbc0864b/common/cmake/installTBB.cmake#L4-L7

But because we're using our own TBB, this doesn't make sense and breaks the generation (once again because the "TBB" target does not exist).

Should this installation be conditional?
