### ISSUE TITLE
CMake generation of projects importing Embree fails for the static build

### ISSUE THREAD

**Issue by merwaaan** [embree/embree#361]
Hi,

When importing the static build of embree with CMake, we get errors due to missing targets for the kernels:

```
CMake Error at _deps/embree/import.cmake:6 (find_package):
  Found package configuration file:

    [...]/_deps/embree/lib/cmake/embree-3.13.3/embree-config.cmake

  but it set embree_FOUND to FALSE so package "embree" is considered to be
  NOT FOUND.  Reason given by package:

  The following imported targets are referenced, but are missing:
  embree_sse42 embree_avx embree_avx2
```

Indeed, the main import script loads the import scripts for some components (sys, math, simd, etc) but not for the kernels:

https://github.com/embree/embree/blob/d7157470e089098b9c7323f608835ed50453e606/common/cmake/embree-config.cmake#L51-L57

If we manually add something like this in the generated import script, then it works:

```cmake
IF (EMBREE_STATIC_LIB)
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/sys-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/math-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/simd-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/lexers-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/tasking-targets.cmake")

  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/embree_sse42-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/embree_avx-targets.cmake")
  INCLUDE("${EMBREE_ROOT_DIR}/lib/cmake/embree-3.13.3/embree_avx2-targets.cmake")
```

A real fix would be a bit more involved since the includes depend on the ISAs selected during the compilation of Embree.

I can propose a PR to fix that issue and welcome any suggestion on how to achieve that.

**Comment by svenwoop** [comment]
Could you please have a look at latest devel branch. I pushed there a fix.

**Comment by merwaaan** [comment]
@svenwoop I confirm that the missing targets issue has been resolved. Thanks!
