### ISSUE TITLE
Closest point on subdivided geometries

### ISSUE THREAD

**Issue by 93214015** [embree/embree#371]
Is it possible to have a tutorial or explanation of how we should implement ClosestPoint functionality of triangulated meshes for subdivided ones?

**Comment by svenwoop** [comment]
For subdivision geometries closest point queries are essentially not supported, as there is no way you could access the tessellation that Embree performs internally.
We anyway recommend to not use the Embree subdivision primitive, but tessellate the geometry inside the application, e.g. using Embree's rtcInterpolate feature for subdivision surface or OpenSubDiv. This gives you more control and will allow you to implement the closest point query on the subdivided mesh.
