### ISSUE TITLE
Clarification on ray tfar validity in rtcSetGeometryIntersectFunction

### ISSUE THREAD

**Issue by radon199** [embree/embree#372]
In the documentation for the rtcSetGeometryIntersectFunction: https://github.com/embree/embree/blob/0835461a5dd1659696524303dc9cb2f2300ae156/doc/src/api/rtcSetGeometryIntersectFunction.md

It states : 
> The ray component of the rayhit structure contains valid data, in particular the tfar value is the current closest hit distance found. All data inside the hit component of the rayhit structure are undefined and should not be read by the function.

I am however not seeing this as the case. I am tracing against a scene which contains only a single UserGeometry. That user geometry wants to know how far along the ray it is ( generally). I was hoping that the ray would contain the tfar value of the bounds intersect for my UserGeometry performed by the BVH, which is a good enough approximation for my purposes. Instead I get whatever tfar value the Ray was initialized to, in the case of primary rays that being from the far clip of the camera.

Since I know the bounds it was easy enough to write my own AABB intersect function to figure out generally the path length, the only issue being is that Embree and my intersect function don't always agree ( with embree always being the more accepting of intersections ).

What hit distance is the above quote referring to in this context? Would, for example, be limited to the previous hits that were ignored by only custom intersect functions, and not any closest match from the BVH?

**Comment by svenwoop** [comment]
The documentation is correct, the tfar value contains the distance to the current closest hit. In the beginning this is just the tfar value you initialized the ray with, during traversal this may be a closer hit. You should use that tfar value to check if you found a closer hit, and if so update tfar and the hit data fields. Embree does not pass the hit distance to the bounding box of the primitive.
