### ISSUE TITLE
Implementation of "Ray" in "tutorials/common/core/ray.h"

### ISSUE THREAD

**Issue by Beastmaster** [embree/embree#375]
I checked out `Ray` implementation in `tutorials/common/core/ray.h`
```
.........
  public:
    embree::Vec3ff org;       //!< Ray origin + tnear
    //float tnear;              //!< Start of ray segment
    embree::Vec3ff dir;        //!< Ray direction + tfar
    //float time;               //!< Time of this ray for motion blur.
    float tfar;               //!< End of ray segment
    unsigned int mask;        //!< used to mask out objects during traversal
    unsigned int id;          //!< ray ID
    unsigned int flags;       //!< ray flags
  public:
    ...............
```
While `RTCRay` in `include/embree3/rtcore_ray.h`:
```
struct RTC_ALIGN(16) RTCRay
{
  float org_x;        // x coordinate of ray origin
  float org_y;        // y coordinate of ray origin
  float org_z;        // z coordinate of ray origin
  float tnear;        // start of ray segment

  float dir_x;        // x coordinate of ray direction
  float dir_y;        // y coordinate of ray direction
  float dir_z;        // z coordinate of ray direction
  float time;         // time of this ray for motion blur

  float tfar;         // end of ray segment (set to hit distance)
  unsigned int mask;  // ray mask
  unsigned int id;    // ray ID
  unsigned int flags; // ray flags
};
```
Memory map of  tutorial's `Ray` and `RTCRay` are different. `Ray` comments out `near` and `time`. 
While this code cast directly:
```
__forceinline RTCRayHit* RTCRayHit_(Ray& ray) {
  return (RTCRayHit*)&ray;
}
```
Did I miss something?

**Comment by svenwoop** [comment]
The embree::Vec3ff type contains a Vec3f plus an additional float, thus the layouts match. That Vec3ff type is handled with SSE which is slightly faster than using scalar code to handle Vec3f and some float. In your app best use Vec3f + float, as this is easier to handle.

**Comment by Beastmaster** [comment]
Why not use structures in `include` folder? Why not replace official data structures if implementations in tutorial are more efficient?

**Comment by svenwoop** [comment]
The tutorial uses these Vec3f classes from the Embree library, and using these types also in the API would blow up its size. The API should be small, thus it just describes the layout. The app can then choose, to either directly work with these ray definitions, or create the same layout using the apps short vector library. You likely have your own Vec3f implementation in your app anyway, and you probably should use that to build the ray in your side.

**Comment by Beastmaster** [comment]
Thanks!
