### ISSUE TITLE
can we add 4D noise?  (ie animating clouds across time etc.)

### ISSUE THREAD

**Issue by unicomp21** [embree/embree#380]
https://github.com/aqsis/aqsis/blob/master/libs/math/noise1234.cpp#L383

**Comment by unicomp21** [comment]
https://github.com/stegu/webgl-noise/blob/master/src/noise4D.glsl

**Comment by unicomp21** [comment]
this would be useful for worley, voronoi when doing water as well

**Comment by unicomp21** [comment]
maybe there is also an argument for rendering 2D and 3D into repeating noise tiles, ie pnoise, for lookup?  to increase speed?  and use the strategy in 5.5 to increase the non-repeating range of the noise?

https://developer.nvidia.com/sites/all/modules/custom/gpugems/books/GPUGems/gpugems_ch05.html

**Comment by unicomp21** [comment]
@svenwoop

**Comment by svenwoop** [comment]
Embree is not about noise generation, thus I see no reason to add this. Please use these referenced libraries directly.
