### ISSUE TITLE
Back of sphere is hit which should be impossible

### ISSUE THREAD

**Issue by tbhunderbird** [embree/embree#381]
Using pathracer tutorial application and a closed sphere, there are a few hits on the backside of the sphere which should not be possible.
E.g looking from 100 0 0 to 0 0 0 there are a few hits with negative x-value (sphere centered at 0 0 0 with r=5). This also happens for max_path_length==1.

I can provide files for a minimal example (github does not let me upload the zip-files).

**Comment by svenwoop** [comment]
Do you use the default scene settings? If so then this is expected as some performance optimizations are done that reduce robustness. Please try again creating your scene with the RTC_SCENE_FLAG_ROBUST which should fix almost all of these issues.

**Comment by tbhunderbird** [comment]
It got a lot better but there are still a few hits.

**Comment by svenwoop** [comment]
It will not get perfect, but there should not mainly be hits if you exactly hit a vertex, as our ray/triangle intersector cannot handle that case perfectly.
