### ISSUE TITLE
Missing CMake find module in binary download

### ISSUE THREAD

**Issue by jeffamstutz** [embree/embree#39]
The convenient find_package module for CMake appears to not be included in the binary distributions found on http://embree.github.io/downloads.html.

**Comment by svenwoop** [comment]
The scripts were only in the RPM version. I added them also to the tar.gz file for Linux now. Set the EMBREE_dir variable to embree/lib/cmake/embree-2.6.1/. Or just install the RPMs and CMake will find Embree automatically.
