### ISSUE TITLE
Extract color of each triangle of the scene?

### ISSUE THREAD

**Issue by LeHibou2** [embree/embree#390]
Hi,
I have a black and white scene + spotlight and I wish to extract the shadows info out of each triangle generated.
It is not clear to me: how can I do that? 

Thanks

**Comment by LeHibou2** [comment]
I don't have any constraint on the extracted data structure, be it an image or a vector of structs, as long as I can get the info.

**Comment by svenwoop** [comment]
I do not understand the question. You can use rtcOccluded function to test for an occluder along a ray, to check if a point lies on shadow.

**Comment by LeHibou2** [comment]
I was a bit in my head, what I want is a way to extract the shadows occuring in each triangle to further analyze it in my program. 
I need to analyze the gradients the light involves on object.

For example, when a scene is set,if it has a white cube and a light, I want the shadow map of the cube. The easiest way I found is to analyze each triangle of the cube and extract the non white color and pass it to my pipeline.

I basically want the simplest way to extract shadows occuring in a mesh triangle.

Thanks :)

**Comment by LeHibou2** [comment]
The bottom line is light analysis to find the best lighting placement and orientation. To minimize/maximize shadows in a given context

**Comment by LeHibou2** [comment]
My bad, read too fast: it's the renderer I need.
Closing.
Thanks
