### ISSUE TITLE
[Bug] Wrong spatial splits with non Planar Quads

### ISSUE THREAD

**Issue by Hengoo** [embree/embree#399]
According to the documentation for quads: "A quad is internally handled as a pair of two triangles"
(https://github.com/embree/embree#rtc_geometry_type_quad)

Spatial splits with quads only look at the 4 outer edges.
(The code here: https://github.com/embree/embree/blob/master/kernels/builders/splitter.h#L126)
The inner edge v1 - v3 is ignored. For non planar quads this can lead to incorrect split bounds.

Possible fix: add an additional vertex into the QuadSplitter struct and fill them like this:
```
        v[0] = mesh->vertex(quad.v[1]);
        v[1] = mesh->vertex(quad.v[2]);
        v[2] = mesh->vertex(quad.v[3]);
        v[3] = mesh->vertex(quad.v[0]);
        v[4] = mesh->vertex(quad.v[1]);
        v[5] = mesh->vertex(quad.v[3]);
        inv_length[0] = Vec3fa(1.0f) / (v[1] - v[0]);
        inv_length[1] = Vec3fa(1.0f) / (v[2] - v[1]);
        inv_length[2] = Vec3fa(1.0f) / (v[3] - v[2]);
        inv_length[3] = Vec3fa(1.0f) / (v[4] - v[3]);
        inv_length[4] = Vec3fa(1.0f) / (v[5] - v[4]);
```

**Comment by svenwoop** [comment]
Thanks for reporting this. I did just fix that in our devel branch and fix will be in next release. BTW, your inv_length code is not correct, but I fixed that.
