### ISSUE TITLE
How can I solve the problem?

### ISSUE THREAD

**Issue by qaz123w** [embree/embree#404]
![111](https://user-images.githubusercontent.com/75780167/192077614-6cc5495b-c3fd-4fb8-854d-cf04aa5c2e75.png)

**Comment by svenwoop** [comment]
Get rid of EMBREE_INSTALL_DEPENCENCIDES=ON and try again.

**Comment by qaz123w** [comment]
> Get rid of EMBREE_INSTALL_DEPENCENCIDES=ON and try again.

![111](https://user-images.githubusercontent.com/75780167/192208267-47ff76df-6f4d-4d67-ae00-112eea6ee45c.png)
![222](https://user-images.githubusercontent.com/75780167/192208274-b4bee812-ed04-4fee-a002-7d44134fa4e5.png)
![333](https://user-images.githubusercontent.com/75780167/192208285-4deb1b0f-e5e0-40a0-9359-24c5fb6f99d2.png)

**Comment by qaz123w** [comment]
> Get rid of EMBREE_INSTALL_DEPENCENCIDES=ON and try again.

Thank you a lot!
