### ISSUE TITLE
API documentation error

### ISSUE THREAD

**Issue by iraytrace** [embree/embree#41]
In https://embree.github.io/api.html under user defined geometry it indicates that the user should:

unsigned geomID = rtcNewUserGeometry(scene, 2);
rtcSetUserData(scene, geomID, userGeom);
rtcSetBounds(scene, geomID, userBoundsFunction);
rtcSetIntersectFunction(scene, geomID, userIntersectFunction);
rtcSetOccludedFunction(scene, geomID, userOccludedFunction);

The word "Function" is missing from the rtcSetBounds call.

**Comment by svenwoop** [comment]
Thanks for reporting this, We will fix this in the next release.
