### ISSUE TITLE
Embree 4.0 more info and planned beta?

### ISSUE THREAD

**Issue by oscarbg** [embree/embree#411]
Hi,
just curious, yesterday announcement of GPU Max series features a slide showing upcoming Embree GPU support in Embree 4.0 in 2023..
just asking if planned a 4.0 public beta release possibly "much earlier" than stable release in "2023"? 2023 target sounds like Embree 4.0 could be released well into 2023 maybe possibly one year from now..
maybe an early beta in OneAPI 2023 beta release supposedly coming next month (December'22)?
also sad to see no info/update on OpenVKL and OIDN GPU support releases.. some ETA to share? 2023 also? possibly a joint launch of all supported GPU Intel APIs with Embree 4.0 release?
would be nice to start testing on consumer Intel Arc GPUs..
thanks..

**Comment by svenwoop** [comment]
Embree 4.0 with GPU support will come very early in 2023, thus you will not have to wait much longer to try it out.
