### ISSUE TITLE
Bounding box limits issue

### ISSUE THREAD

**Issue by iraytrace** [embree/embree#42]
When creating user defined geometry I find that objects whose bounding box min/max values exceed about 1.5E18 never get intersected.  For example, very large planes don't show up.  Is there some expected limit on the size of a bounding box dimension?

**Comment by svenwoop** [comment]
Yes this is true. Embree explicitely ignores some geometry that would anyway cause arithmetic issues. We skip all geometry with values greater than 1.844E18. With numbers in that range you still can do some usefull arithmetic (like multiplying two numbers and still being able to add a couple of these products).
