### ISSUE TITLE
Questions about model normals.

### ISSUE THREAD

**Issue by qaz123w** [embree/embree#420]
When I use embree to calculate the normal of the model, some models will have problems, such as the teapot model, but some models have no problem, such as the bunny model, and the problematic model can be rendered correctly if I use the normal calculated by myself.
![wenti](https://user-images.githubusercontent.com/75780167/214502601-3f92510b-21e1-492b-8d56-081df2f7461e.png)
![spp255](https://user-imag
![3](https://user-images.githubusercontent.com/75780167/214502801-3728f172-552c-4e40-86af-e17888e5dd3c.png)
es.githubusercontent.com/75780167/214502651-471641f7-cf07-486f-b0cf-07385061fca9.png)

**Comment by qaz123w** [comment]
![spp255](https://user-images.githubusercontent.com/75780167/214502938-3d3edf61-97b1-4a70-9446-36ce13b915c4.png)

**Comment by svenwoop** [comment]
Embree returns the normal in object space, while you need a world space normal for shading. Further the normal returned by Embree is the geometry normal, shading typically uses interpolated shading normals.

**Comment by qaz123w** [comment]
Thank you! But I wonder why the rabbit has no problem but the teapot has a problem. The dragon and Lucy are also fine, but Mitsuba's shader ball has the same problem.
![image](https://user-images.githubusercontent.com/75780167/214515146-eb5d7762-6605-42f2-82a9-783b0b81e2ba.png)
![1234567](https://user-images.githubusercontent.com/75780167/214515298-d5563297-98a2-4604-b184-633a1c9a31cd.png)
![123456](https://user-images.githubusercontent.com/75780167/214515383-39234ede-8c34-4718-a75a-29cbb8a9277f.png)

**Comment by qaz123w** [comment]
I want to know why the normals calculated by some models are correct, and some are not correct, and I use the rtcInterpolate0 function to interpolate the normals read from the model, and there will be problems, maybe I am not using it right. Sorry to bother you, but I really want to figure it out.

**Comment by qaz123w** [comment]
Thank you a lot!
