### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by pengwang123** [embree/embree#43]
/local/scratch/embree-2.6.1/kernels/xeon/builders/../../algorithms/parallel_for_for_prefix_sum.h:44:29: sorry, unimplemented: non-trivial designated initializers not supported
     parallel_for(taskCount, [&](const size_t taskIndex)
                             ^
kernels/xeon/CMakeFiles/embree_avx.dir/build.make:215: recipe for target 'kernels/xeon/CMakeFiles/embree_avx.dir/builders/primrefgen.avx.cpp.o' failed
make[2]: *** [kernels/xeon/CMakeFiles/embree_avx.dir/builders/primrefgen.avx.cpp.o] Error 1
CMakeFiles/Makefile2:359: recipe for target 'kernels/xeon/CMakeFiles/embree_avx.dir/all' failed
make[1]: *** [kernels/xeon/CMakeFiles/embree_avx.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

what should I do?

**Comment by svenwoop** [comment]
Which platform and compiler are you using? You have to upgrade your compiler or use the precompiled binaries.

**Comment by pengwang123** [comment]
hello sir, thanks for your reply. I am using linux and gcc version is 5.1, due to I don't have permission to use apt-get or other tools, I need to compile the source code in a different location, but when I try to compile it, this problem comes out.

**Comment by svenwoop** [comment]
Can you use the precompiled version? There is a tar.gz file on the webpage that you can unpack where you need it.

**Comment by pengwang123** [comment]
thanks again sir!!! I tried the pre-compiled version, when I try to use embree render,
xxxx% ./renderer -c ../models/cornell_box.ecs -spp 16 -o cornell_box.tga
Error: libtbb.so.2: cannot open shared object file: No such file or directory
In embree render, I didn't find tbb's path under ccmake ..
so in this case, what I did wrong? I also download a pre-compiled tbb version

**Comment by svenwoop** [comment]
You have to set the LD_LIBRARY_PATH to the location of the tbb library.

**Comment by pengwang123** [comment]
Many thaks Sir!!!!  
I use setenv LD_LIBRARY_PATH  /XX/XX/lib, it still the error:libtbb.so.2: cannot open shared object file: No such file or directory. 

I download the Stable Releases veison of TBB and then change the export TBBROOTtbbvars.sh:
export TBBROOT= /XX/XX the current tbb file path
then I did 
chmod +x tbbvars.sh, 
 ./tbbvars.sh.
I am quite new to linux also I don't have root permission......., don't know which step I did wrong

**Comment by svenwoop** [comment]
If the LD_LIBRARY_PATH is pointing to libtbb.so.2 it will get found. Looks like your path is not setup properly.
