### ISSUE TITLE
HELP: how to acces the user data from RTCBoundsFunction

### ISSUE THREAD

**Issue by matthiascy** [embree/embree#432]
Accroding to the documentation the `rtcSetGeometryBoundsFunction` function registers a bounding box call-
back function (`bounds` argument) with payload (`userPtr` argument) for the specified user geometry (`geometry` argument). But there is no such pointer availabe in `RTCBoundsFunctionArguments` or in `RTCBoundsFunction`'s parameter list, then how could I access the `userPtr`?
```c
struct RTCBoundsFunctionArguments
{
    void* geometryUserPtr;
    unsigned int primID;
    unsigned int timeStep;
    struct RTCBounds* bounds_o;
};

typedef void (*RTCBoundsFunction)(
    const struct RTCBoundsFunctionArguments* args
);

void rtcSetGeometryBoundsFunction(
    RTCGeometry geometry,
    RTCBoundsFunction bounds,
    void* userPtr
);
```

**Comment by svenwoop** [comment]
This is indeed a bug. We have already some user defined pointer that can get set with rtcSetGeometryUserData(geometryUserPtr) for each geometry, and that geometryUserPtr is available in the callback. I do not think one needs one additional user data pointer.
Do fix this we will remove the userPtr specified to the rtcSetGeometryBoundsFunction, and recommend to use the rtcSetGeometryUserData function instead.
