### ISSUE TITLE
Using Embree to access Intel ARC dGPU RT resources for non-RT tasks

### ISSUE THREAD

**Issue by FCLC** [embree/embree#435]
Hi all! 

Slightly weird issue, but I'm trying to gain access to the RT cores available on ARC Alchemist, as well as any future RT enabled devices. 

As of now the only "public" way of accessing RT capabilities seems to be via an Embree SYCL device. 

I'm trying to access the RT cores to offload work from the SIMT cores in an HPC/ GPGPU application, and all of my Intel contacts have pointed me towards this repository (and its managing team). 

Use case is conceptually similar to offloading matrix multiplies to matrix/tensor cores originally targeted for AI/DL applications, but now used as "generic" matrix accelerators such as Intel AMX, Apple AMX, NV tensor cores, Arm SME etc.

**Comment by svenwoop** [comment]
Hi, yes your are right, if you want to use Arc ray tracing hardware using SYCL, then Embree is the way to go.

**Comment by FCLC** [comment]
Hi Sven,

Am I right in saying that to use the hardware I'd be reliant on shipping the embree/raytracing toolkit on top of the "standard" HPC tool kit (to say nothing of the base OneAPI tool kit?). In an ideal scenario including the capability to target the RT hardware (as well as the XMX cores) within the base OneAPI toolkit would be a very nice to have.

-Felix

________________________________

**Comment by svenwoop** [comment]
Embree is included in the oneAPI Rendering Toolkit https://www.intel.com/content/www/us/en/developer/tools/oneapi/rendering-toolkit.html and the next release of the toolkit will also add SYCL GPU support for Embree.
