### ISSUE TITLE
Does/will embree work on Data Center GPUs?

### ISSUE THREAD

**Issue by bgoglin** [embree/embree#436]
Hello
We're looking at buying some Intel GPUs but we have both HPC and Embree users. HPC people tell us to look at Data Center GPUs (either Flex series now or Max series later) for good oneAPI support. Does Embree work on these GPUs? 
Thanks

**Comment by bgoglin** [comment]
Thanks. Could you clarify that in the documentation? For instance, README.md talks about DC GPUs, but there are only Arc 770/750/730/550 under "Currently the following products are supported and further products will get enabled soon:"

**Comment by svenwoop** [comment]
Yes, we will clarify this in the next release.

**Comment by bgoglin** [comment]
@svenwoop Hello, I see the README was updated to say that DC Flex 170 is supported. We just ordered some DC Flex 140. Are they going to be supported too?

**Comment by svenwoop** [comment]
Yes the Flex 140 will work too, but please use latest compute runtime https://github.com/intel/compute-runtime/releases
