### ISSUE TITLE
Add support for ARM64 on Windows

### ISSUE THREAD

**Issue by hmartinez82** [embree/embree#439]
Since ARM64 is already supported for MacOS, would it be possible to also support ARM64 for Windows?

**Comment by anthony-linaro** [comment]
Hi @hmartinez82, JFYI using https://github.com/embree/embree/pull/454 I am able to natively compile for Windows ARM64 platforms on my Thinkpad X13s, using the following:

From within a vcvarsall native ARM64 window, and the latest LLVM+Clang installed, having made and cd-ed to a `build` folder:
```
cmake -G"Ninja" .. -DCMAKE_C_COMPILER="clang-cl" -DCMAKE_CXX_COMPILER="clang-cl" -DCMAKE_C_FLAGS_INIT="--target=arm64-pc-windows-msvc" -DCMAKE_CXX_FLAGS_INIT="--target=arm64-pc-windows-msvc" -DTBB_ROOT=<path/to/tbb/install/dir> -DCMAKE_BUILD_TYPE=Release
```
Then
```
cmake --build . -j8
```

As a result all tests pass successfully within `embree_verify.exe` :)

One step closer to native blender!
