### ISSUE TITLE
Need constant for bounds checking

### ISSUE THREAD

**Issue by iraytrace** [embree/embree#44]
In issue #42 Sven indicated:
> We skip all geometry with values greater than 1.844E18

Can we get a constant (eg, #define RTC_MAX_BOUND 1.844E18) in the embree headers for this?

Additionally, if embree could somehow signal that the bounds had been exceeded that would be good.

**Comment by iraytrace** [comment]
Documenting this limit in the API documentation and tutorials would also help.

**Comment by svenwoop** [comment]
In the latest Embree releases you can find just change the define FLT_LARGE in common/sys/constants.h. But keep in mind, that models much larger than this can anyway not get processed correctly in all cases.

For which kind of application do you need such large numbers?

**Comment by iraytrace** [comment]
As I think about this more, it isn't really the range, but the precision that is probably more important. 1E18mm is big enough. That's 1E12km for us which makes it ok for terrestrial work. 8-)

Digging deeper, I find that we have a "halfspace" primitive which is where I mostly run up against this.  We currently set the bounding box to something near double-precision limits.  Simply collapsing this back is probably fine for us.
