### ISSUE TITLE
Blockers for NVIDIA acceleration?

### ISSUE THREAD

**Issue by dsvensson** [embree/embree#440]
Jumped into the deep end and built llvm-sycl with NVIDIA support yesterday, updated the compiler flags of embree to target `nvptx64-nvidia-cuda` etc, only to end up failing the build due to missing `intel_get_rt_stack`. Was hoping SYCL would provide all hardware abstractions. As I have no idea what I'm doing I just wanted to ask if embree lacks a big chunk of stuff for NVIDIA to work, or if it's within reach to get it working, and what would be possible steps to achieve this?

**Comment by svenwoop** [comment]
Embree uses an Intel extension to access the ray tracing hardware, thus you cannot just compile that code to Nvidia hardware. Thus enabling NVidia is definitely not in reach and requires significant amount of work.

**Comment by svenwoop** [comment]
That extension will only be supported on Intel GPUs. You will see a significant speedup between a 8 core CPU and A770 when doing ray tracing. Intel Developer Cloud is the way to go to experiments with Intel Arc.

**Comment by tbhunderbird** [comment]
Hi Sven, 
could you please elaborate on what parts of embree are optimized with SYCL?
Is it everything apart from this "intel_get_rt_stack" (ray-tracing extension of Intel?).
And what is this ray-tracing extension of Intel? Is it also available stand alone?
All the best,
Tobias
