### ISSUE TITLE
libtbb osx issues in 2.6.1

### ISSUE THREAD

**Issue by ov** [embree/embree#46]
Hi guys, there's something wrong with libtbb/tbbmalloc files bundled with the latest osx-version of embree (2.6.1). They work fine, but when it comes to various mach-based operations or code-signing, they fail.

Here's what I get when trying install_name_tool on them:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for architecture x86_64 object: libtbb.dylib truncated or malformed object (LC_SEGMENT_64 command 2 fileoff field plus filesize field extends past the end of the file)
```

Here's what codesign tells me:

```
signing libtbb.dylib
libtbb.dylib: replacing existing signature
libtbb.dylib: main executable failed strict validation
```

Replacing the files with the ones from TBB project solves the issue (I used 4.3 update 6), so I guess all you need is to simply update the files.

**Comment by svenwoop** [comment]
Sorry, an older TBB version has found its way into this release. I updated the release with the latest version. Please download again.
