### ISSUE TITLE
installation on Arch Inux

### ISSUE THREAD

**Issue by MASALTA** [embree/embree#465]
Hi, Can anyone tell me how install the Embree on my Arch Linux please? 
Thanks

**Comment by johguenther** [comment]
Embree is available as normal package, just do
```sh
sudo pacman -S embree
```

**Comment by freibold** [comment]
As @johguenther already mentioned, there is an Embree package for Archlinux https://archlinux.org/packages/extra/x86_64/embree/ that you should be able to install using pacman. Alternatively you can download a prebuild version for Linux: https://github.com/embree/embree/releases or you can compile Embree from source on Archlinux, too: https://github.com/embree/embree/blob/master/README.md#linux-and-macos
