### ISSUE TITLE
[HELP] Geometry instancing is not working

### ISSUE THREAD

**Issue by StudenteChamp2** [embree/embree#466]
I implemented geometry instancing inside my renderer. So multiple instances of a same mesh can share the same memory. I tried to do the same thing Embree side. Since now I have been creating an RTCGeometry(RTC_GEOMETRY_TYPE_TRIANGLE) for each mesh regardless they are instances or not. 

I made a simple test. The scene has a single mesh that is a plane. That plane has an identity transform(its origin is (0, 0, 0) no rotation no scale).  Then to render i perform intersect queries(rtcIntersect1) against the scene.

**Without instancing** I get the right result:   
![NoInstancing](https://github.com/embree/embree/assets/144755653/03895390-dfcd-48d5-ac83-a53b0330def6)

**With instancing**, intersection queries fails:  
![Instancing](https://github.com/embree/embree/assets/144755653/4ab89898-a983-45d5-9097-155726f64efa)

**HERE THE CODE WITHOUT INSTANCING(WORKS):**  
```c

// Initialize embree device.
g_device = rtcNewDevice(nullptr);

// Initialize the root scene.
g_scene = rtcNewScene(g_device);

// Read first mesh of test group --> the plane.
const auto group = Model::getMeshGroupPtr_FromEntity(targetEntity);
Model::Mesh* mesh = group->m_meshes[0];

// Create the root geometry.
g_geometry = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_TRIANGLE);

// Set vertices. 
{
	/*struct FullVertex
	{
		Math::Vec3 position;
		Math::Vec3 normal;
		Math::Vec3 tangent;
		Math::Vec3 bitangent;
		Math::Vec2 texCoord;
	};*/
	const std::vector<FullVertex>& meshVertices = mesh->getVertices();

	rtcSetSharedGeometryBuffer(
		g_geometry,
		RTC_BUFFER_TYPE_VERTEX,
		0,
		RTC_FORMAT_FLOAT3,
		meshVertices.data(),
		0,
		sizeof(Graphics::FullVertex),
		meshVertices.size());
}

// Set indices.
{
	const std::vector<unsigned int>& meshIndices = mesh->getIndices();

	rtcSetSharedGeometryBuffer(
		g_geometry,
		RTC_BUFFER_TYPE_INDEX,
		0,
		RTC_FORMAT_UINT3,
		meshIndices.data(),
		0,
		3 * sizeof(unsigned int),
		meshIndices.size() / 3);
}

rtcCommitGeometry(g_geometry);
rtcAttachGeometryByID(g_scene, g_geometry, mesh->getFlatId());
rtcReleaseGeometry(g_geometry);

rtcCommitScene(g_scene);

// Init the intersection context.
m_context = new RTCIntersectContext();
rtcInitIntersectContext(m_context);`
```

**HERE THE CODE WITH INSTANCING(DOESN'T WORKS).** It is based on the [instanced geometry tutorial.](https://github.com/embree/embree/blob/master/tutorials/instanced_geometry/instanced_geometry_device.cpp)  
Check the "NEW" tag to see what is different.  

```c 
// Initialize embree device.
g_device = rtcNewDevice(nullptr);

// Initialize the root scene.
g_scene = rtcNewScene(g_device);

// Read first mesh of test group --> the plane.
const auto group = Model::getMeshGroupPtr_FromEntity(targetEntity);
Model::Mesh* mesh = group->m_meshes[0];

// Initialize the scene to use for instancing.
g_scene1 = rtcNewScene(g_device);// NEW

// Create the root geometry.
g_geometry = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_TRIANGLE);

// Set vertices. 
{
	/*struct FullVertex
	{
		Math::Vec3 position;
		Math::Vec3 normal;
		Math::Vec3 tangent;
		Math::Vec3 bitangent;
		Math::Vec2 texCoord;
	};*/
	const std::vector<FullVertex>& meshVertices = mesh->getVertices();

	rtcSetSharedGeometryBuffer(
		g_geometry,
		RTC_BUFFER_TYPE_VERTEX,
		0,
		RTC_FORMAT_FLOAT3,
		meshVertices.data(),
		0,
		sizeof(Graphics::FullVertex),
		meshVertices.size());
}

// Set indices.
{
	const std::vector<unsigned int>& meshIndices = mesh->getIndices();

	rtcSetSharedGeometryBuffer(
		g_geometry,
		RTC_BUFFER_TYPE_INDEX,
		0,
		RTC_FORMAT_UINT3,
		meshIndices.data(),
		0,
		3 * sizeof(unsigned int),
		meshIndices.size() / 3);
}

rtcCommitGeometry(g_geometry);
rtcAttachGeometryByID(g_scene1, g_geometry, mesh->getFlatId());// NEW
rtcReleaseGeometry(g_geometry);

rtcCommitScene(g_scene1); // NEW

// Create an instance. All block is NEW.
{
	g_instance0 = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_INSTANCE);
	rtcSetGeometryInstancedScene(g_instance0, g_scene1);

	//const glm::mat4& transform = mesh->getTransform()->getMatrix();
	//rtcSetGeometryTransform(g_instance0, 0, RTC_FORMAT_FLOAT4X4_COLUMN_MAJOR, (float*)&transform[0][0]);
	const float transform[] = { 1.0f, 0.0f, 0.0f, 0.0f,
						 0.0f, 1.0f, 0.0f, 0.0f,
						 0.0f, 0.0f, 1.0f, 0.0f,
						 0.0f, 0.0f, 0.0f, 1.0f };

	rtcSetGeometryTransform(g_instance0, 0, RTC_FORMAT_FLOAT4X4_COLUMN_MAJOR, &transform[0]);

	rtcAttachGeometry(g_scene, g_instance0);
	rtcReleaseGeometry(g_instance0);
}

rtcCommitScene(g_scene);

// Init the intersection context.
m_context = new RTCIntersectContext();
rtcInitIntersectContext(m_context);
```

The issue is present on both Embree v3.1.0 and v4.3.0. So it is Embree bug or am I doing something wrong?

**Comment by StudenteChamp2** [comment]
While it may not be relevant, Here the full source code:  
```c
	CPUIntersector::CPUIntersector(const Model::BaseModel* model, const EntityIdentifier& targetEntity)
	: BaseIntersector(IntersectorType::Cpu)
	{
		s_model = model;

		if (!targetEntity)
		{
			// For this test we are only interested by the plane mesh.
			return;
		}

		// Initialize embree device.
		g_device = rtcNewDevice(nullptr);

		// Initialize the root scene.
		g_scene = rtcNewScene(g_device);

		// Read first mesh of test group --> the plane.
		const auto group = Model::getMeshGroupPtr_FromEntity(targetEntity);
		Model::Mesh* mesh = group->m_meshes[0];

		// Initialize the scene to use for instancing.
		g_scene1 = rtcNewScene(g_device);

		// Create the root geometry.
		g_geometry = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_TRIANGLE);

		// Set vertices. 
		{
			/*struct FullVertex
			{
				Math::Vec3 position;
				Math::Vec3 normal;
				Math::Vec3 tangent;
				Math::Vec3 bitangent;
				Math::Vec2 texCoord;
			};*/
			const std::vector<FullVertex>& meshVertices = mesh->getVertices();

			rtcSetSharedGeometryBuffer(
				g_geometry,
				RTC_BUFFER_TYPE_VERTEX,
				0,
				RTC_FORMAT_FLOAT3,
				meshVertices.data(),
				0,
				sizeof(Graphics::FullVertex),
				meshVertices.size());
		}

		// Set indices.
		{
			const std::vector<unsigned int>& meshIndices = mesh->getIndices();

			rtcSetSharedGeometryBuffer(
				g_geometry,
				RTC_BUFFER_TYPE_INDEX,
				0,
				RTC_FORMAT_UINT3,
				meshIndices.data(),
				0,
				3 * sizeof(unsigned int),
				meshIndices.size() / 3);
		}

		rtcCommitGeometry(g_geometry);
		rtcAttachGeometryByID(g_scene1, g_geometry, mesh->getFlatId());
		rtcReleaseGeometry(g_geometry);

		rtcCommitScene(g_scene1);

		// Create an instance.
		{
			g_instance0 = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_INSTANCE);
			rtcSetGeometryInstancedScene(g_instance0, g_scene1);

			//const glm::mat4& transform = mesh->getTransform()->getMatrix();
			//rtcSetGeometryTransform(g_instance0, 0, RTC_FORMAT_FLOAT4X4_COLUMN_MAJOR, (float*)&transform[0][0]);
			const float transform[] = { 1.0f, 0.0f, 0.0f, 0.0f,
						  0.0f, 1.0f, 0.0f, 0.0f,
						  0.0f, 0.0f, 1.0f, 0.0f,
						  0.0f, 0.0f, 0.0f, 1.0f };

			rtcSetGeometryTransform(g_instance0, 0, RTC_FORMAT_FLOAT4X4_COLUMN_MAJOR, &transform[0]);

			rtcAttachGeometry(g_scene, g_instance0);
			rtcReleaseGeometry(g_instance0);
		}

		rtcCommitScene(g_scene);

		// Init the intersection context.
		m_context = new RTCIntersectContext();
		rtcInitIntersectContext(m_context);
	}

	CPUIntersector::~CPUIntersector()
	{
		if (g_scene)
		{
			delete m_context;
			rtcReleaseScene(g_scene);
			rtcReleaseDevice(g_device);
		}
	}

	RTCRayHit nativeRayToEmbree(const Math::Ray& ray)
	{
		RTCRay embreeRay;
		embreeRay.org_x = ray.m_origin.x; embreeRay.org_y = ray.m_origin.y; embreeRay.org_z = ray.m_origin.z;
		embreeRay.dir_x = ray.getDirection().x; embreeRay.dir_y = ray.getDirection().y; embreeRay.dir_z = ray.getDirection().z;

		embreeRay.tnear = 0.0f;
		embreeRay.tfar = ray.m_length;
		embreeRay.time = 0.0f;

		embreeRay.mask = -1;
		embreeRay.id = 0;
		embreeRay.flags = 0;

		RTCRayHit rayHit;
		rayHit.ray = embreeRay;
		rayHit.hit.geomID = RTC_INVALID_GEOMETRY_ID;
		rayHit.hit.primID = RTC_INVALID_GEOMETRY_ID;

		return rayHit;
	}

	IntersectionInfo CPUIntersector::embreeIsectInfoToNative(const glm::vec3& rayOr, const RTCHit& hit, float t)
	{
		IntersectionInfo info;

		if (hit.geomID != RTC_INVALID_GEOMETRY_ID)
		{
			info.meshIntersectData.t = t;
			info.meshIntersectData.primId = hit.primID;

			info.object = s_model->getFlatMeshes()[hit.geomID];
		}
		else
		{
			info.object = nullptr;
		}

		return info;
	}

	bool CPUIntersector::intersect(const Math::Ray& ray, IntersectionInfo& info)
	{
		RTCRayHit isect = nativeRayToEmbree(ray);
		rtcIntersect1(g_scene, m_context, &isect);
	
		info = embreeIsectInfoToNative(ray.m_origin, isect.hit, isect.ray.tfar);

		return info.object != nullptr;
	}
```

**Comment by svenwoop** [comment]
What geometry is the mesh supposed to be? It is likely just the one grass object, which is also seen in the instancing case. I cannot spot any obvious error in your code.

**Comment by freibold** [comment]
You can also take a look at the instance array geometry tutorial 

https://github.com/embree/embree/blob/master/tutorials/forest/forest_device.cpp 

that we added in Embree 4.3.0. This tutorial does almost the same as you want to do but with trees instead of grass/herbs.

**Comment by StudenteChamp2** [comment]
@svenwoop As i said the plane object is the one to be instancied. Not the grass.
I made a simple test. I want to spawn an herb model over a plane. To do so i simply intersect vertical rays to find where the herb should be spawn. For this test the plane mesh is the one be instanced(one instance)

**Comment by StudenteChamp2** [comment]
@freibold  Checking thank you :)

**Comment by StudenteChamp2** [comment]
@svenwoop  @freibold Thanks for helping.  
I updated the question because it can be confusing.
So now the scene has only one mesh: the plane.

To recall I have 2 implementations

### 1) No instancing(WORKS)

-->Create the scene(rtcNewScene)
-->Create a RTCGeometry(RTC_GEOMETRY_TYPE_TRIANGLE)  for the plane
-->Commit the geometry(rtcCommitGeometry)  
-->Attach the geometry to the scene(rtcAttachGeometryByID)  
--> Commit the scene.  

### 2) Instancing(DOESN'T WORK)

-->Create the root scene()
`g_scene = rtcNewScene(g_device)`  

-->Create the instanced scene
`g_scene1 = rtcNewScene(g_device)`  

-->Create a RTCGeometry  for the plane
`g_geometry = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_TRIANGLE);`  

-->Commit the geometry 
`rtcCommitGeometry(g_geometry)`  

-->Attach the geometry to the instanced scene
`rtcAttachGeometryByID(g_scene1, g_geometry, mesh->getFlatId())`  
 
--> Commit the instanced scene
`rtcCommitScene(g_scene1)`  

-->Create a geometry instance.
`g_instance0 = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_INSTANCE)`

**Comment by svenwoop** [comment]
Could you please provide a reproducer by modifying the instance geometry tutorial? It is not obvious what is wrong there and we would need a small reproducer to debug this.

**Comment by StudenteChamp2** [comment]
I managed to have it working by doing the same steps as what it is in the instanced geometry tutorial.  It look like this:
 
-->**Create the root scene**
`g_scene = rtcNewScene(g_device)`  

-->**Create the instanced scene**
`g_scene1 = rtcNewScene(g_device)`  

-->**Create a RTCGeometry  for the plane**
`g_geometry = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_TRIANGLE);`  

-->**Set the geometry vertex and index buffers.**  

-->**Commit the geometry** 
`rtcCommitGeometry(g_geometry)`  

-->**Attach the geometry to the instanced scene**
`rtcAttachGeometryByID(g_scene1, g_geometry, mesh->getFlatId())`  
 
-->**Release the geometry** 
`rtcReleaseGeometry(g_geometry);`  

--> **Commit the instanced scene**
`rtcCommitScene(g_scene1)`  

-->**Create a geometry instance.**
`g_instance0 = rtcNewGeometry(g_device, RTC_GEOMETRY_TYPE_INSTANCE)`  

-->**Attach the geometry instance to the root scene**
`rtcAttachGeometry(g_scene, g_instance0)`  

-->**Release the geometry instance** 
`rtcReleaseGeometry(g_instance0);`  


-->**Set the instance transform**
`
const float transform[] = { 1.0f, 0.0f, 0.0f, 0.0f,
				 0.0f, 1.0f, 0.0f, 0.0f,
				0.0f, 0.0f, 1.0f, 0.0f,
				0.0f, 0.0f, 0.0f, 1.0f };  

rtcSetGeometryTransform(g_instance0, 0, RTC_FORMAT_FLOAT4X4_COLUMN_MAJOR, &transform[0]))`  

--> **Commit the instance geometry**
`rtcCommitScene(g_instance0)`  

-->**Commit the root scene**
`rtcCommitScene(g_scene))`

**Comment by StudenteChamp2** [comment]
@svenwoop How does **rtcReleaseGeometry** works?
Here we create the instance geometry then we free it inside the same function(_device_init_ ):  
https://github.com/embree/embree/blob/master/tutorials/instanced_geometry/instanced_geometry_device.cpp#L123

Then we later use the same geometry(we released) and we commit it:
https://github.com/embree/embree/blob/master/tutorials/instanced_geometry/instanced_geometry_device.cpp#L339

**Comment by svenwoop** [comment]
The rtcReleaseGeometry decreases the reference counter on the geometry handle, thus you should not use that handle anymore. However, if you previously attach the handle to some scene, then the object itself will still be alive, as the scene itself increases the reference count on that geometry.
