### ISSUE TITLE
Unable to compile Embree on Windows 10

### ISSUE THREAD

**Issue by StudenteChamp2** [embree/embree#467]
I am trying to compile Embree via Cmake. I use the following command to generate the VS solution:
cmake -G "Visual Studio 15 2017 Win64"

 I first tried to follow the readme steps(**Building Embree Applications**)  
 1) There is no embree_config.cmake on my system but a embree-config.cmake instead.
 2) I downloaded and installed oneAPi TBB. There is no TBB-config.cmake coming with it
 

So I decided to fix the build errors one by one.
Unfortunately i had 2 errors.  

### Error 1(Fixed)
Cmakes first complains about not finding **TBB_ROOT**.  
![root](https://github.com/embree/embree/assets/144755653/4157dab4-0dda-475d-84a4-675060b74e8e)

 I fixed it by installing oneApi TBB and setting the **TBB_ROOT** environment variable to  _C:\Program Files (x86)\Intel\oneAPI\tbb\2021.10.0_ 
This error is gone.

### Error 2(can't fix)
Cmakes now complains about not finding **TBB_INCLUDE_DIR**
![Inc](https://github.com/embree/embree/assets/144755653/0f9abc5d-abda-4e6f-997c-bc37445bfd9b)

I downloaded  [the TBB package from github](https://github.com/oneapi-src/oneTBB/releases/tag/v2021.10.0). I unziped the package then I set the **TBB_INCLUDE_DIR** environment variable to point to the include folder _D:\oneapi-tbb-2021.10.0-win\include_

Cmakes still complains about now finding **TBB_INCLUDE_DIR**. Why?

Thanks for helping :)

**Comment by svenwoop** [comment]
I think problem is that your TBB_ROOT does not point to the TBB config file, try pointing TBB_ROOT  to TBB_ROOT=path_to_tbb\lib\cmake\tbb

**Comment by StudenteChamp2** [comment]
It worked thank you :)
