### ISSUE TITLE
Building with glibc 2.5

### ISSUE THREAD

**Issue by stygianguest** [embree/embree#47]
Currently embree cannot be built with glibc 2.5 only because it uses the `CPU_COUNT()` macro introduced in glibc 2.6. The workaround used in https://github.com/rmanzoni/TauHlt/blob/master/HLTrigger/Timer/src/CPUAffinity.cc also works for embree, at least for gcc.

**Comment by svenwoop** [comment]
I just removed this dependency. A next Embree release will also work with older glibc versions.

**Comment by stygianguest** [comment]
Thanks for the speedy fix!
