### ISSUE TITLE
FindTBB.cmake script overwrites user variables

### ISSUE THREAD

**Issue by stygianguest** [embree/embree#48]
In order to build with custom TBB libraries, the cmake `FindTBB.cmake` script has the variables `TBB_INCLUDE_DIR` `TBB_LIBRARY` and `TBB_LIBRARY_MALLOC`  that previously allowed users to build with a different version of TBB. Now, however, they are always overwritten with `*-NOTFOUND` strings. Removing the `SET(TBB_LIBRARY TBB_LIBRARY-NOTFOUND)` command from the cmake script works around the problem. I'm not sure if it is a good solution in general though..

**Comment by svenwoop** [comment]
Just set the TBB_ROOT variable to /usr or some other folder containing your TBB installation will work. The other TBB_XXX variables are set automatically. We introduced that as we had issues on some machines, where the header and libraries found were incompatible when multiple TBB versions were lying around.

**Comment by stygianguest** [comment]
Thanks for your quick response. Although you might not want to support this usecase, for us these variables are necessary because the directory structure we use for our tbb package is different than the official one. Thus setting `TBB_ROOT` is insufficient.

Finally, in case you insist on having everything defined by `TBB_ROOT`, you might want to set the `TBB_*` variables that are always overwritten anyway to `CACHE INTERNAL` so that they don't appear as an option in cmake(-gui).

Of course we'd prefer to have the `TBB_*` overwrite those found in `TBB_ROOT`.

**Comment by svenwoop** [comment]
I will make these variables adjustable for the next release when setting TBB_ROOT to the empty string.
