### ISSUE TITLE
Limit isa to available isa

### ISSUE THREAD

**Issue by stygianguest** [embree/embree#50]
When initializing embree with for example "isa=avx", embree will happily assume the system has avx and crash while executing an illigal instruction. It would be nice to prevent such an initialization with something like

    void setCPUFeatures(int features) {
      cpu_features = features & getCPUFeatures();
    }

in `common/sys/sysinfo.cpp`. Right now we end up doing the same on our side, although we would just like to limit the system to `avx` (not use `avx2`).

**Comment by louisfeng** [comment]
We have situations where the build target ISA is different than the current machine's available ISA. 

An easy work around (alternative to what you are doing) is to modify the cmake config and set the ISA to your desired type by default.

**Comment by stygianguest** [comment]
This is about the runtime configuration, we also compile for different architectures. The workaround would work though and is what we used before, but we prefer to use your `icc` built binary package. I can't image a situation where one wants to execute embree with an instruction not supported by the cpu; it would always lead to a crash.

**Comment by svenwoop** [comment]
I will add that change to the setCPUFeatures function for the next release.

**Comment by svenwoop** [comment]
The next Embree release will have an max_isa option for rtcInit that will limit the ISA used, e.g. rtcInit("max_isa=avx") will limit Embree to use at most AVX. The rtcInit("isa=avx") will continue to force Embree to use AVX, without testing if supported by the machine.
