### ISSUE TITLE
gcc 5.1

### ISSUE THREAD

**Issue by romp13** [embree/embree#56]
Hi,

When compiling embree with gcc 5.1 (default on Fedora 22), I get this kind of errors:
**embree/kernels/xeon/builders/../../algorithms/parallel_for_for_prefix_sum.h:47:51: error: redeclaration of ‘const size_t& taskCount’**
       const size_t k1 = (taskIndex+1)*state.size()/taskCount

**embree/kernels/xeon/builders/../../algorithms/parallel_for_for_prefix_sum.h:44:29: sorry, unimplemented: non-trivial designated initializers not supported**
     parallel_for(taskCount, \[&\](const size_t taskIndex)

This is compiling fine with older version of GCC and this was reported and will be fixed in gcc 5.2 (see here https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65843)

I can work fix the problem by explicitly listing the parameters to capture instead of capturing everything, i.e. using "[&state,&taskCount,...]" instead of "[&]". This has to be done in multiple files from the "algorithms" folder.
I know gcc 5 is not officially supported but I figured this could affect other people and might be helpful.

Best,
Romain

**Comment by cbenthin** [comment]
It seems that only a single GCC version is causing the issue. GCC 4.8.* and GCC 5.3.1 (Fedora 23) seem to work fine (just tested). I don't think it is worth the effort to change the code in this regard.
