### ISSUE TITLE
Enhancement: Julia etc. binding/wrapper

### ISSUE THREAD

**Issue by MrMormon** [embree/embree#58]
Anything to make this more high-level (since the OSPRay plugins aren't really alpha yet). I'm with IntelLabs on rooting for Julia the most, but some communities may prefer Lua, Rust, or Go.

**Comment by MrMormon** [comment]
Anything to make this more high-level (since the OSPRay plugins aren't really alpha yet). I'm with IntelLabs on rooting for Julia the most.

**Comment by svenwoop** [comment]
I dont fully understand what you are asking for. Are you looking for a Julia binding of the Embree Ray Tracing Kernels or the OSPray Visualization Toolkit?

**Comment by MrMormon** [comment]
Embree. OSPRay has its own repo.

**Comment by svenwoop** [comment]
Implementing bindings for different programming languages is not on our agenda. All of our customers use C++ as they need optimal performance.

**Comment by MrMormon** [comment]
We'll see if I get there one day then.

**Comment by MrMormon** [comment]
Python is huge in the scientific computing world, so what about its compiled variants?
