### ISSUE TITLE
Normals of instanced objects are in the wrong space

### ISSUE THREAD

**Issue by darkhorse64** [embree/embree#60]
This can be seen in the instanced_geometry tutorial.
Replace lines 281-283 by these lines:
```C++
  xfm.l.vx = Vec3fa(cos(time), 0, sin(time));
  xfm.l.vy = Vec3fa(0, 1, 0);
  xfm.l.vz = Vec3fa(-sin(time), 0, cos(time));
```
You will see lighting "rotating" on the spheres.

The reason is that Ng is computed in "object" space but is not transformed back to "world" space. May be there should be an intersect epilog for instances.

**Comment by svenwoop** [comment]
Thanks for reporting, I juse fixed this in the devel branch.
