### ISSUE TITLE
Embree won't compile if XEON_ISA set to AVX512

### ISSUE THREAD

**Issue by shengfuintel** [embree/embree#61]
I got compile error when I set XEON_ISA=AVX512 for master branch, and XEON_ISA=AVX512KNL for devel branch. The error is the following:

 Building CXX object kernels/xeon/CMakeFiles/embree_avx512.dir/bvh/bvh_builder.avx512.cpp.o
": internal error: 04010002_0

compilation aborted for /usr/pic1/ws/git/test/embree/kernels/xeon/bvh/bvh_builder.avx512.cpp (code 4)
make[2]: *** [kernels/xeon/CMakeFiles/embree_avx512.dir/bvh/bvh_builder.avx512.cpp.o] Error 4
make[1]: *** [kernels/xeon/CMakeFiles/embree_avx512.dir/all] Error 2

The following are how I ran cmake:

/usr/pic1/cmake-3.4.0-Linux-x86_64/bin/cmake                     \
      -DCMAKE_BUILD_TYPE=Debug                                   \
      -DCMAKE_INSTALL_PREFIX=/usr/pic1/ws/git/embree/install-knl \
      -DENABLE_ISPC_SUPPORT=FALSE                                \
      -DXEON_ISA=AVX512KNL                                       \
      -DCMAKE_CXX_COMPILER=/opt/intel/composerxe/bin/icpc        \
      -DCMAKE_C_COMPILER=/opt/intel/composerxe/bin/icc           \
      ..

My ICC is 15.0.3.

**Comment by cbenthin** [comment]
This is an ICC bug in 15.0.x which only gets triggered in DEBUG mode (RELEASE mode seems  to work fine). In general AVX512 code in the devel branch currently requires ICC 16.0.x.
