### ISSUE TITLE
Can not build Release version for branch devel

### ISSUE THREAD

**Issue by shengfuintel** [embree/embree#62]
I tried to build the code in devel branch for KNL. I got the following compile error:

../../libembree.so.2.7.2: undefined reference to `__intel_avx_rep_memset'
../../libembree.so.2.7.2: undefined reference to `__intel_avx_rep_memcpy'

This is for Release mode, Debug mode is ok.

The following is how I run cmake:

/usr/pic1/cmake-3.4.0-Linux-x86_64/bin/cmake                     \
      -DCMAKE_BUILD_TYPE=Release                                 \
      -DCMAKE_INSTALL_PREFIX=/usr/pic1/ws/git/embree/install-knl \
      -DENABLE_ISPC_SUPPORT=FALSE                                \
      -DXEON_ISA=AVX512KNL                                       \
      -DCMAKE_CXX_COMPILER=/opt/intel/compilers_and_libraries_2016/linux/bin/intel64/icpc        \
      -DCMAKE_C_COMPILER=/opt/intel/compilers_and_libraries_2016/linux/bin/intel64/icc           \
      ..
My icc version is : icpc (ICC) 16.0.1 20151021

**Comment by cbenthin** [comment]
Maybe some compiler paths are not correctly set, did you execute a "source /opt/intel/compilers_and_libraries_2016/Linux/bin/compilervars.sh intel64" before?

**Comment by cbenthin** [comment]
Based on Sheng's findings it seems that for this particular OS/compiler combination libirc.a needs to be added as a linker dependency.
