### ISSUE TITLE
GCC update script issue

### ISSUE THREAD

**Issue by ucmsuri** [embree/embree#63]
Hi,
       As given in the manual I tried running scripts/install_linux_gcc.sh to update gcc but it failed with the following. Hopefully this needs a fix.

embree$ ./scripts/install_linux_gcc.sh 
Installing gcc in /home/surya/devtools-2
.fetching RPM list
gzip: primary.xml.gz: No such file or directory
.looking for devtoolset-2-binutils
...fetching

**Comment by johguenther** [comment]
The first download is not working for you. Do you have `wget` installed? Also, do you have the right proxy settings? Try, whether this works:

    wget -c http://people.centos.org/tru/devtools-2/6/x86_64/RPMS/repodata/primary.xml.gz
