### ISSUE TITLE
compilation failed: loadu is not a member of embree::vint8

### ISSUE THREAD

**Issue by khumarahn** [embree/embree#67]
Hi, I am trying to compile embree on linux with gcc-4.9. Compilation fails with
```
scene_subdiv_mesh_avx.cpp:150:30: error: ‘loadu’ is not a member of ‘embree::vint8 {aka embree::vint<8>}’
         if (valid) valid1 &= vint8::loadu(&valid[i]) == vint8(-1);
```

**Comment by khumarahn** [comment]
Details: I run
```
export CFLAGS="-O2 -pipe -march=native"
export CXXFLAGS="${CFLAGS}"

cmake -DENABLE_ISPC_SUPPORT=OFF ..

make
```

There are no problems without "-O2 -pipe -march=native"...

**Comment by svenwoop** [comment]
Embree compiles different files for different ISAs. If you force the compiler to some ISA some Embree files will not compile, thus please compile without the -match=native flag. Embree will automatically select the optimal codepath during runtime. To limit the highest supported ISA set the XEON_ISA flag.

**Comment by khumarahn** [comment]
ok, thank you for the explanation!
