### ISSUE TITLE
master 1 commit behind release

### ISSUE THREAD

**Issue by MrMormon** [embree/embree#68]
Does master have a purpose anymore? Devel and release seem to be the important branches.

**Comment by cbenthin** [comment]
"master" is always in sync with the latest released version. Takes care that a simple embree checkout gives you the latest version.

**Comment by MrMormon** [comment]
Why did release receive a commit that isn't synced with master?

**Comment by MrMormon** [comment]
Bump

**Comment by svenwoop** [comment]
The release branch is used to branch out a release for internal testing. When the code is tested we create the release and bring the master branch in sync.
