### ISSUE TITLE
Embree doesn't install .a libraries.

### ISSUE THREAD

**Issue by ciechowoj** [embree/embree#72]
`make install` doesn't copy `.a` library files to system directory.

**Comment by svenwoop** [comment]
The .a files are not necessary to use Embree, only the .so file is required.

**Comment by ciechowoj** [comment]
Well, so why I'm getting linker errors?

**Comment by svenwoop** [comment]
What is your link error? Do you link against libembree.so?

**Comment by ciechowoj** [comment]
I compiled embree with following commands:

    mkdir build
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=/usr ..
    make -j4
    make install

The I compile my binary with `-lembree` switch. And I get following errors:

    /usr/bin/ld: cannot find -lembree
    /usr/bin/ld: cannot find -lsys
    /usr/bin/ld: cannot find -lsimd
    /usr/bin/ld: cannot find -llexers
    collect2: error: ld returned 1 exit status
    make: *** [build/master/master.bin] Error 1

**Comment by svenwoop** [comment]
You can only install Embree when using as a shared library. Your link error indicate you use it as a static library.

make install seems to not generate the link from /usr/lib64/libembree.so.2 to /usr/lib64/libembree.so. Just create that link automatically, or specify the path to /usr/lib64/libembree.so.2 when linking. We will fix that issue in the next release.

If you want to use CMake when building your application, then please also have a look at the find_embree tutorial. This uses FIND_PACKAGE to find and links against an installed Embree.

**Comment by ciechowoj** [comment]
> You can only install Embree when using as a shared library. Your link error indicate you use it as a static library.

So, am I supposed to load appropriate function calls from shared library manually (e.g. with `dlopen`, `dlsym`)? 

> make install seems to not generate the link from /usr/lib64/libembree.so.2 to /usr/lib64/libembree.so. Just create that link automatically, or specify the path to /usr/lib64/libembree.so.2 when linking. We will fix that issue in the next release.

In my case (Linux Mint/Ubuntu 14.04) `libembree.so.2` is installed to `/usr/lib`, which I think is sufficient for it be found by dynamic linker.

> If you want to use CMake when building your application, then please also have a look at the find_embree tutorial. This uses FIND_PACKAGE to find and links against an installed Embree.

I'm not using CMake (to build my whole project), but thanks for suggestion.

**Comment by svenwoop** [comment]
You do not have to use dlopen and dlsym to access library functions. Just include the embree2/rtcore.h header and use the API functions.

If you link with -lembree the libembree.so link has to be present for the linker to find the library.
