### ISSUE TITLE
Latest master branch not building under MSVC2013-x64

### ISSUE THREAD

**Issue by etheory** [embree/embree#76]
Hi there,

From the latest embree2 master branch, when I compile with cmake using MSVC2013 (64bit), I get the following compilation error:

> embree\kernels\common\subdiv\bezier_curve.h(180) : fatal error C1001: An internal error has occurred in the compiler.

It appears that the template types used here (line 180 of the above file):

`const Vec4vf4 pi = eval0(vbool4(true),0,4);`

Are just too awesome for MSVC to handle.

Has this been tested on MSVC2013? If so, are there any flags I should be setting to get rid of this? (aside from turning off optimization entirely, which I don't really want to do?)

Thanks!

Luke

**Comment by etheory** [comment]
VC2015 seems to work OK so I'm not so worried about the VC2013 build issue.

I'll close the ticket thanks
Luke

**Comment by ainaerco** [comment]
Modify docs and wiki please that you support only MSVC2015, people are struggling.

**Comment by svenwoop** [comment]
We are also supporting VS2013 with Update 5.
