### ISSUE TITLE
CMake output directory prevents "clean" build

### ISSUE THREAD

**Issue by sjm324** [embree/embree#77]
When using `embree` as a submodule, it will produce libraries / tests at the top-level binary directory:

```
##############################################################
# Output paths
##############################################################
SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
```

This means that even if a parent CMakeLists.txt adds embree to a different directory (I am adding to an external_build directory), the libraries will be produced at the top level with my executables.  The `CMAKE_BINARY_DIR` can be changed to `CMAKE_CURRENT_BINARY_DIR` to fix it, but I'm hesitant to make a pull request as it will almost certainly have implications for installation / uninstallation.  I'm no cmake expert, but maybe something like the following would be appropriate?

```
# Determine if this CMakeLists.txt is being called from a parent. If so,
# allow embree to install in whatever location the parent may have given.
get_directory_property(EMBREE_HAS_PARENT PARENT_DIRECTORY)
if(EMBREE_HAS_PARENT)
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}")
else()
    SET(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
    SET(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
    SET(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}")
endif()
```

Or maybe just use `CMAKE_CURRENT_BINARY_DIR` and use that variable to determine setup for install / uninstall?

This isn't exactly a major issue...but it would be nice if it's relatively painless to include ;) Thanks!

**Comment by svenwoop** [comment]
I will change Embree to generate libraries in the default CMake location which will fix this issue.
