### ISSUE TITLE
Is it possible to define per-ray user data (or callback) in current version (2.9.0)?

### ISSUE THREAD

**Issue by Apumx** [embree/embree#78]
I'm trying to do alpha blending for transparent materials in direct lighting. If there is a per-ray user data I can use to accumulate the alpha value, it will be a trivial thing to do. Otherwise, I have to call rtcIntersect multiple times to do blending outside embree's bvh which is apparently very inefficient.

I've read the manual, and so far I only find rtcGetUserData & rtcSetUserData to setup per-object user data which is not suitable for my problem. Any help? Thanks in advance.

**Comment by svenwoop** [comment]
You can extend the ray structure with additional data. The ray that is provided to the intersection filters is the same ray pointer you passed to the rtcIntersect/rtcOccluded calls. See the intersection_filter tutorial for an example.
