### ISSUE TITLE
Wrong type of capacity argument in encodeRGB8_to_JPEG()

### ISSUE THREAD

**Issue by danfe** [embree/embree#82]
`encodeRGB8_to_JPEG()` calls libjpeg's `jpeg_mem_dest()`, which is defined as follows:
```
EXTERN(void) jpeg_mem_dest (j_compress_ptr cinfo, unsigned char ** outbuffer,
                            unsigned long * outsize);
```
Notice `unsigned long * outsize`, which is passed as `capacity` argument of `encodeRGB8_to_JPEG()`, which is of type `size_t *`.  I'm not sure why this went unnoticed, perhaps this type mismatch is OK on 64-bit architectures (which I can't verify), but on 32-bit the code does not compile:
```
.../embree-2.10.0/tutorials/common/image/jpeg.cpp:89:9: error: no matching function for
call to 'jpeg_mem_dest'
        jpeg_mem_dest(&cinfo, encoded, capacity);
        ^~~~~~~~~~~~~
/usr/local/include/jpeglib.h:919:14: note: candidate function not viable: no known
conversion from 'size_t *' (aka 'unsigned int *') to 'unsigned long *' for 3rd argument
EXTERN(void) jpeg_mem_dest (j_compress_ptr cinfo, unsigned char ** outbuffer,
                            unsigned long * outsize);
             ^
1 error generated.
```
Consider attached [patch](https://github.com/embree/embree/files/279783/encodeRGB8_to_JPEG-fix.txt) that fixes this problem my making `capacity` type the same as libjpeg expects.

**Comment by cbenthin** [comment]
Thanks for reporting this. I've added the fix to the devel branch.
