### ISSUE TITLE
Fix intrinsics.h linking issues on 32-bit architectures

### ISSUE THREAD

**Issue by danfe** [embree/embree#83]
Some functions in `common/sys/intrinsics.h` are defined in pairs for `size_t` and `unsigned int`, e.g. `__bsf()`, `__bscf()`, `__bsr()`.  On 64-bit architectures these two types are different: `size_t` is 8 byte long while `unsigned int` is 4 byte long.  On 32-bit (i386) they are essentially the same, and this creates linking problem (function redefinition).

Consider attached [patch](https://github.com/embree/embree/files/279867/intrinsics-32-bit-fix.txt) that fixes this problem (and another minor one), making the code both 64-bit and 32-bit happy.

**Comment by cbenthin** [comment]
added to devel branch
