### ISSUE TITLE
How to find  the intersection of a ray with a mesh?

### ISSUE THREAD

**Issue by wguo68** [embree/embree#87]
The ray is from a real camera not from the OpenGL  camera. In a word, I just want to the intersection of a ray with a mesh,how to use the API.

**Comment by cbenthin** [comment]
I would recommend to have a look at the Embree tutorials: http://embree.github.io/tutorials.html . The "Triangle Geometry" tutorial is a simple example on how to setup a mesh and intersect it with rays.
