### ISSUE TITLE
embree-config.cmake on Linux is missing libtbb and libtbbmalloc version numbers

### ISSUE THREAD

**Issue by Twinklebear** [embree/embree#93]
The `embree-2.10.0.x86_64.linux.tar.gz` release includes the version suffixed libs for TBB and TBB malloc, `libtbb.so.2` and `libtbbmalloc.so.2`, but `embree-config.cmake` looks for the non-suffixed ones, `libtbb.so` and `libtbbmalloc.so`. As a result when building a project using Embree it will fail to find the TBB libraries, since it's looking for the wrong filenames.

**Comment by johguenther** [comment]
Fixed in branch `devel`.

**Comment by Twinklebear** [comment]
Is there a way to get the version of the so in CMake? It might be a problem if the TBB version being included changes, unless it will always be suffixed by a 2?

**Comment by johguenther** [comment]
Embree's [`FindTBB.cmake`](https://github.com/embree/embree/blob/devel/common/cmake/FindTBB.cmake#L108) explicitly installs version 2, so I think this is fine for now.

A better approach might be to install and use the found libraries, i.e. `TBB_LIBRARY` and `TBB_LIBRARY_MALLOC`. I could not find out whether there is a reason not to do this.

**Comment by Twinklebear** [comment]
I see, yea that sounds fine then.

Using the system's TBB library if it has one would probably be better and it can fall back to the included TBB if the system is missing it or has an incompatible version or something.

**Comment by cbenthin** [comment]
Fix will be included in the next Embree release.
