### ISSUE TITLE
C++ AMP support?

### ISSUE THREAD

**Issue by acterhd** [embree/embree#94]
Hello. Will you support C++ AMP? I want see Embree on C++ AMP.

**Comment by cbenthin** [comment]
We currently have no plans to support C++ AMP (in particular as there's no demand for it and it doesn't seem to be cross-platform anyway) . Is there a particular reason why you can't use for example the TBB framework?

**Comment by acterhd** [comment]
C++ AMP supports gpu.

**Comment by cbenthin** [comment]
I'm sorry but Embree's focus is on CPU-like architectures and that is unlikely to change. If there's enough demand we might have a look at C++ AMP but for now it is quite unlikely that we'll support it in the near-term.

**Comment by cbenthin** [comment]
That said, you could add C++ AMP yourself. Might be some effort required but should be doable, depending on what you want to do exactly. If you want some guidance on this please contact me directly.
