### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [embree/embree#95]
I would like to point out that identifiers like "[`__RTCDevice`](https://github.com/embree/embree/blob/c28dae141a8f0cb370ce32d9d811f88a630f1c5a/include/embree2/rtcore.h#L75)" and "[`__RTCORE_RAY_H__`](https://github.com/embree/embree/blob/50a8814b5b586416b1e26872828bc54f76010808/include/embree2/rtcore_ray.h#L17)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by cbenthin** [comment]
Hi,
thanks for pointing this out. Everything around the 2.x API is supposed to stay unchanged so we cannot do this changes right now but we'll consider it for the next major version of Embree.

**Comment by elfring** [comment]
* Would it be safer to keep this issue open until it will be really fixed?
* How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?")?

**Comment by cbenthin** [comment]
I'm not sure how this naming convention could cause undefined behavior within Embree. We didn't observe any problems so far regarding the naming convention. If this is really a major issue that will affect our customers I'll reopen again but I need to see some more proof/data.

**Comment by elfring** [comment]
Would you like to take another look at [consequences from the involved naming convention](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Using reserved identifiers?")?

**Comment by cbenthin** [comment]
So far not a single compiler on any OS "complained" about this and we didn't get any feedback that this is causing real trouble in other projects (which build on embree). Maybe the compilers are simply more tolerant that the spec says :). That said, I've added the naming change request to our todo list for future embree releases.

**Comment by elfring** [comment]
* This issue affects "tolerance" also to some degree. It is more a matter on how serious you treat [the avoidance of undefined behaviour in this software](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?"), isn't it?
* How are the chances to improve standard-compliance?
