### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [embree/embree#96]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [cyHairFile](https://github.com/embree/embree/blob/8a28950e8af2088553e0d81b0dbabe67ec5741cf/tutorials/common/scenegraph/cy_hair_loader.cpp#L53 "Destructor for cyHairFile")
* [Distribution2D](https://github.com/embree/embree/blob/8a28950e8af2088553e0d81b0dbabe67ec5741cf/tutorials/convert/distribution2d.cpp#L30 "Destructor for Distribution2D")

**Comment by cbenthin** [comment]
Thanks, the extra checks don't do any harm and are not critical in any way.
