### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [embree/embree#97]
Would you like to [wrap any pointer data members](https://github.com/embree/embree/blob/8a28950e8af2088553e0d81b0dbabe67ec5741cf/kernels/common/raystream_log.cpp#L41 "Update candidate: RayStreamLogger class") with the template class "[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

**Comment by cbenthin** [comment]
Thanks but the (deprecated) ray stream logger support will be removed soon, so I don't think it is worth the effort.
