### ISSUE TITLE
Incorrect result with avx packet tracing and VC 2015

### ISSUE THREAD

**Issue by ivalylo** [embree/embree#98]
First, I didn't compile with cmake, but my build seems to work fine except in this case. The issue happens only when the optimizations are turned on with rtcOccluded8. It runs also suspiciously faster compared to the official binary. The effect is that the result is darker, possibly because of false intersections. I guess this is a VC 2015 bug with too aggressive optimization, but still, if there is a known work-around. I'm using Update 2 and the master embree branch.

**Comment by cbenthin** [comment]
If you don't compile with cmake, did you make sure that all ray packet code is probably activated? Does for example our little test program (verify) run though? Also do the ISPC tutorials work (they will use rtcIntersect8/rtcOccluded8)?  If they all work could you provide us some simple reproducer (code/scene)?

Thanks.

**Comment by ivalylo** [comment]
I verified that my code itself runs fine by using the official builds. Then verified that it runs fine with disabled embree optimizations in the VC build. If you don't know about such issue, I will run the cmake build and check the ispc samples.

**Comment by ivalylo** [comment]
The issue doesn't happen when building with cmake. It's probably happening in my build, because I didn't use separate libs for the different ISA configurations, but tried to cheat by duplicating the files with changed defines.

**Comment by ivalylo** [comment]
The issue seems to happen because of not enabled avx instruction set in the "code generation". I was afraid to turn it on since I want to support older processors, but I guess turning avx on only for the ISA libs is fine.
